
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//					    	ROGUE KITS
//__________________________________________________________________________________
//__________________________________________________________________________________


//_______________________MEISTERSINGER_______________________________________________

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5MEIST~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES_______________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MEIST       0 1 1 0 1 1 1 1~
~D5MEIST       0 1 1 0 1 1 1 1 0 0 0 0 0 0 1 1 0 1 1 0 1 0 1 1 1 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MEIST    	   0   10  0   0   12  12~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MEIST           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MEIST           0   15  0   0   0   15~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MEIST  	       0   15  0   0   0   15~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MEIST           0  1  0  1  1  1  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MEIST           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~npc_ee/kits/meistersinger/d5_meist.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 5~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ba0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @44301
SAY @44302
SAY @44303
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@44304)
		STR_VAR
			kit_name = D5MEIST
			clswpbon = ~0 0 3~
	END
END
//____________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5MEIST~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MEIST       0 3 3 0 3 3 3 3~
~D5MEIST       0 3 3 0 3 3 3 3 0 3 3 3 0 0 3 3 0 3 0 0 3 3 3 3 0 3 0 3 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MEIST    	   0   10  0   0   12  12~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MEIST           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MEIST           0   15  0   0   0   15~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MEIST  	       0   15  0   0   0   15~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MEIST           1  1  0  1  1  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MEIST           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~npc_ee/kits/meistersinger/d5_meist.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 5~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ba0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @44301
SAY @44302
SAY @44303
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@44304)
		STR_VAR
			kit_name = D5MEIST
			clswpbon = ~1 0 3~
	END
END
//____________________________________________________________________________________

END

//MEISTERSINGER ABILITY FILES_________________________________________________________
//
COPY ~npc_ee/kits/meistersinger/d5_basp1.spl~ ~override~
COPY ~npc_ee/kits/meistersinger/d5_basp2.spl~ ~override~
COPY ~npc_ee/kits/meistersinger/d5_basp3.spl~ ~override~
COPY ~npc_ee/kits/meistersinger/d5_basp4.spl~ ~override~
COPY ~npc_ee/kits/meistersinger/d5_basp5.spl~ ~override~
COPY ~npc_ee/kits/meistersinger/d5_basp6.spl~ ~override~
COPY ~npc_ee/kits/meistersinger/d5_basp7.spl~ ~override~
COPY ~npc_ee/kits/meistersinger/d5_basp8.spl~ ~override~
COPY ~npc_ee/kits/meistersinger/d5_luckp.spl~ ~override~
	SAY NAME1 @44305
	SAY UNIDENTIFIED_DESC @44305
COPY_EXISTING ~sppr103.spl~ ~override/d5_mei11.spl~
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~sppr105.spl~ ~override/d5_mei12.spl~
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~sppr109.spl~ ~override/d5_mei13.spl~
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~sppr110.spl~ ~override/d5_mei14.spl~
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~sppr202.spl~ ~override/d5_mei21.spl~
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~sppr210.spl~ ~override/d5_mei22.spl~
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~sppr212.spl~ ~override/d5_mei23.spl~
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~sppr204.spl~ ~override/d5_mei24.spl~
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~sppr308.spl~ ~override/d5_mei31.spl~
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~sppr317.spl~ ~override/d5_mei32.spl~
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~sppr318.spl~ ~override/d5_mei33.spl~
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~sppr319.spl~ ~override/d5_mei34.spl~
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~sppr401.spl~ ~override/d5_mei41.spl~
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~sppr410.spl~ ~override/d5_mei42.spl~
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~sppr417.spl~ ~override/d5_mei43.spl~
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~sppr514.spl~ ~override/d5_mei51.spl~
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~sppr508.spl~ ~override/d5_mei52.spl~
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~sppr517.spl~ ~override/d5_mei53.spl~
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~sppr602.spl~ ~override/d5_mei61.spl~
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~sppr609.spl~ ~override/d5_mei62.spl~
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~sppr707.spl~ ~override/d5_mei71.spl~
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~sppr720.spl~ ~override/d5_mei72.spl~
	WRITE_SHORT 0x1c 1
COPY ~npc_ee/kits/meistersinger/d5_meiss.spl~ ~override~
COPY ~npc_ee/kits/meistersinger/d5_meisa.spl~ ~override~
COPY ~npc_ee/kits/meistersinger/d5_meisu.spl~ ~override~
ACTION_IF FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ THEN BEGIN
	COPY_EXISTING ~sppr120.spl~ ~override/d5_meis1.spl~
		WRITE_SHORT 0x1c 1
END
ACTION_IF FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ THEN BEGIN
	COPY_EXISTING ~sppr220.spl~ ~override/d5_meis2.spl~
		WRITE_SHORT 0x1c 1
END
ACTION_IF FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ THEN BEGIN
	COPY_EXISTING ~sppr320.spl~ ~override/d5_meis3.spl~
		WRITE_SHORT 0x1c 1
END
ACTION_IF FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ THEN BEGIN
	COPY_EXISTING ~sppr402.spl~ ~override/d5_meis4.spl~
		WRITE_SHORT 0x1c 1
END
ACTION_IF FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ THEN BEGIN
	COPY_EXISTING ~sppr501.spl~ ~override/d5_meis5.spl~
		WRITE_SHORT 0x1c 1
END
ACTION_IF FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ THEN BEGIN
	COPY_EXISTING ~sppr602.spl~ ~override/d5_meis6.spl~
		WRITE_SHORT 0x1c 1
END
	COPY_EXISTING ~d5_meist.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~npc_ee/kits/meistersinger/meistsummon.txt~
ACTION_IF FILE_EXISTS_IN_GAME ~d5_skspl.d5~ THEN BEGIN
	COPY_EXISTING ~d5_meist.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~npc_ee/kits/meistersinger/baspl1.txt~
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5_taspl.d5~ THEN BEGIN
	COPY_EXISTING ~d5_meist.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~npc_ee/kits/meistersinger/baspl2.txt~
END
//__________________________________________________________________________________
