// v2.4 - classes var fix fix


//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION set_lang RET game_lang BEGIN

ACTION_IF !(VARIABLE_IS_SET %EE_LANGUAGE%) BEGIN
  COPY_EXISTING ~spwi101.spl~ ~override~
	READ_STRREF 0x50 description_string
  BUT_ONLY
  ACTION_FOR_EACH lang IN ~en_US~ /*~fr_FR~ ~pl_PL~ ~de_DE~ ~es_ES~ ~cs_CZ~ ~ru_RU~ ~ko_KR~*/ BEGIN
	WITH_TRA ~%MOD_FOLDER%/lib/dialprof/%lang%/dialprof.tra~ BEGIN
	  OUTER_SPRINT duration_lang @10 
	END	
	ACTION_IF !(~%description_string%~ STRING_CONTAINS_REGEXP ~%duration_lang%~) BEGIN
	  OUTER_SPRINT game_lang ~%lang%~
	END
  END
END
ACTION_IF (VARIABLE_IS_SET %EE_LANGUAGE%) BEGIN
  OUTER_SPRINT ee_lang ~%EE_LANGUAGE%~
  ACTION_IF (FILE_EXISTS ~%MOD_FOLDER%/lib/dialprof/%ee_lang%/dialprof.tra~) BEGIN
	OUTER_SPRINT game_lang ~%EE_LANGUAGE%~
  END
END
ACTION_IF !(VARIABLE_IS_SET %game_lang%) BEGIN
	OUTER_SPRINT game_lang ~en_US~
END

END		//	end define function


//__________________________________________________________________________________
//__________________________________________________________________________________


//SET UP PROFICIENCY DIALOGUE________________________________________________________
//
DEFINE_ACTION_MACRO PROF_DIALOGUE BEGIN

// this is not a function BUT: some important variables to consider seting when running this:

//  - %prof_script_name% - SPRINT to a ~5-6 letter string that you will then call from a spell or item or something

//    ^^^ SIX LETTERS MAX LENGTH!

//  - %script_level_one% - SET to 1 to include 1st-level prof  points

//  - %script_higher_levels% - SET to 1 to include prof points for levels higher than 1

//  - ...if both of those last two are 0, it will only let you advance one prof once

//  - %class_dlgs% - SPRINT to "all" or to a string containing the first two letters of desired classes, e.g. "fi_ra_pa"

/*
//COPY MARKER FILE__________________________________________________________________
//
COPY ~%MOD_FOLDER%/lib/dialprof/d5__dialprof.d5~ ~override~
//__________________________________________________________________________________
*/

//find game install language_________________________________________________________
//
LAF set_lang RET game_lang END

WITH_TRA ~%MOD_FOLDER%/lib/dialprof/%game_lang%/dialprof.tra~ BEGIN

//macro defaults____________________________________________________________________
//
ACTION_IF !(VARIABLE_IS_SET %prof_script_name%) BEGIN
  OUTER_SPRINT prof_script_name ~d5cprf~
END

ACTION_IF !(VARIABLE_IS_SET %script_level_one%) BEGIN
  OUTER_SET script_level_one = 0
END

ACTION_IF !(VARIABLE_IS_SET %script_higher_levels%) BEGIN
  OUTER_SET script_higher_levels = 0
END

ACTION_IF !(VARIABLE_IS_SET %class_dlgs%) BEGIN
  OUTER_SET fighter_dlg = 1
  OUTER_SET ranger_dlg = 1
  OUTER_SET paladin_dlg = 1
  OUTER_SET cleric_dlg = 1
  OUTER_SET druid_dlg = 1
  OUTER_SET shaman_dlg = 1
  OUTER_SET thief_dlg = 1
  OUTER_SET bard_dlg = 1
  OUTER_SET mage_dlg = 1
  OUTER_SET sorcerer_dlg = 1
  OUTER_SET monk_dlg = 1
END
ACTION_IF (VARIABLE_IS_SET %class_dlgs%) BEGIN
 ACTION_IF (~%class_dlgs%~ STRING_CONTAINS_REGEXP ~fi~ = 0) BEGIN
  OUTER_SET fighter_dlg = 1
 END ELSE BEGIN
  OUTER_SET fighter_dlg = 0
 END
 ACTION_IF (~%class_dlgs%~ STRING_CONTAINS_REGEXP ~ra~ = 0) BEGIN
  OUTER_SET ranger_dlg = 1
 END ELSE BEGIN
  OUTER_SET ranger_dlg = 0
 END
 ACTION_IF (~%class_dlgs%~ STRING_CONTAINS_REGEXP ~pa~ = 0) BEGIN
  OUTER_SET paladin_dlg = 1
 END ELSE BEGIN
  OUTER_SET paladin_dlg = 0
 END
 ACTION_IF (~%class_dlgs%~ STRING_CONTAINS_REGEXP ~cl~ = 0) BEGIN
  OUTER_SET cleric_dlg = 1
 END ELSE BEGIN
  OUTER_SET cleric_dlg = 0
 END
 ACTION_IF (~%class_dlgs%~ STRING_CONTAINS_REGEXP ~dr~ = 0) BEGIN
  OUTER_SET druid_dlg = 1
 END ELSE BEGIN
  OUTER_SET druid_dlg = 0
 END
 ACTION_IF (~%class_dlgs%~ STRING_CONTAINS_REGEXP ~sh~ = 0) BEGIN
  OUTER_SET shaman_dlg = 1
 END ELSE BEGIN
  OUTER_SET shaman_dlg = 0
 END
 ACTION_IF (~%class_dlgs%~ STRING_CONTAINS_REGEXP ~th~ = 0) BEGIN
  OUTER_SET thief_dlg = 1
 END ELSE BEGIN
  OUTER_SET thief_dlg = 0
 END
 ACTION_IF (~%class_dlgs%~ STRING_CONTAINS_REGEXP ~ba~ = 0) BEGIN
  OUTER_SET bard_dlg = 1
 END ELSE BEGIN
  OUTER_SET bard_dlg = 0
 END
 ACTION_IF (~%class_dlgs%~ STRING_CONTAINS_REGEXP ~ma~ = 0) BEGIN
  OUTER_SET mage_dlg = 1
 END ELSE BEGIN
  OUTER_SET mage_dlg = 0
 END
 ACTION_IF (~%class_dlgs%~ STRING_CONTAINS_REGEXP ~so~ = 0) BEGIN
  OUTER_SET sorcerer_dlg = 1
 END ELSE BEGIN
  OUTER_SET sorcerer_dlg = 0
 END
 ACTION_IF (~%class_dlgs%~ STRING_CONTAINS_REGEXP ~mo~ = 0) BEGIN
  OUTER_SET monk_dlg = 1
 END ELSE BEGIN
  OUTER_SET monk_dlg = 0
 END
 ACTION_IF (~%class_dlgs%~ STRING_CONTAINS_REGEXP ~all~ = 0) BEGIN
  OUTER_SET fighter_dlg = 1
  OUTER_SET ranger_dlg = 1
  OUTER_SET paladin_dlg = 1
  OUTER_SET cleric_dlg = 1
  OUTER_SET druid_dlg = 1
  OUTER_SET shaman_dlg = 1
  OUTER_SET thief_dlg = 1
  OUTER_SET bard_dlg = 1
  OUTER_SET mage_dlg = 1
  OUTER_SET sorcerer_dlg = 1
  OUTER_SET monk_dlg = 1
 END
END

//read weapprof_____________________________________________________________________
//
COPY_EXISTING ~weapprof.2da~ ~override~
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS 5 rows
  FOR (row = 7; row < rows; ++row) BEGIN
    READ_2DA_ENTRY row 1 cols stat
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~89~) BEGIN
      READ_2DA_ENTRY row 2 cols name_89
      READ_2DA_ENTRY row 3 cols desc_89
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~90~) BEGIN
      READ_2DA_ENTRY row 2 cols name_90
      READ_2DA_ENTRY row 3 cols desc_90
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~91~) BEGIN
      READ_2DA_ENTRY row 2 cols name_91
      READ_2DA_ENTRY row 3 cols desc_91
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~92~) BEGIN
      READ_2DA_ENTRY row 2 cols name_92
      READ_2DA_ENTRY row 3 cols desc_92
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~93~) BEGIN
      READ_2DA_ENTRY row 2 cols name_93
      READ_2DA_ENTRY row 3 cols desc_93
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~94~) BEGIN
      READ_2DA_ENTRY row 2 cols name_94
      READ_2DA_ENTRY row 3 cols desc_94
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~95~) BEGIN
      READ_2DA_ENTRY row 2 cols name_95
      READ_2DA_ENTRY row 3 cols desc_95
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~96~) BEGIN
      READ_2DA_ENTRY row 2 cols name_96
      READ_2DA_ENTRY row 3 cols desc_96
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~97~) BEGIN
      READ_2DA_ENTRY row 2 cols name_97
      READ_2DA_ENTRY row 3 cols desc_97
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~98~) BEGIN
      READ_2DA_ENTRY row 2 cols name_98
      READ_2DA_ENTRY row 3 cols desc_98
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~99~) BEGIN
      READ_2DA_ENTRY row 2 cols name_99
      READ_2DA_ENTRY row 3 cols desc_99
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~100~) BEGIN
      READ_2DA_ENTRY row 2 cols name_100
      READ_2DA_ENTRY row 3 cols desc_100
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~101~) BEGIN
      READ_2DA_ENTRY row 2 cols name_101
      READ_2DA_ENTRY row 3 cols desc_101
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~102~) BEGIN
      READ_2DA_ENTRY row 2 cols name_102
      READ_2DA_ENTRY row 3 cols desc_102
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~103~) BEGIN
      READ_2DA_ENTRY row 2 cols name_103
      READ_2DA_ENTRY row 3 cols desc_103
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~104~) BEGIN
      READ_2DA_ENTRY row 2 cols name_104
      READ_2DA_ENTRY row 3 cols desc_104
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~105~) BEGIN
      READ_2DA_ENTRY row 2 cols name_105
      READ_2DA_ENTRY row 3 cols desc_105
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~106~) BEGIN
      READ_2DA_ENTRY row 2 cols name_106
      READ_2DA_ENTRY row 3 cols desc_106
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~107~) BEGIN
      READ_2DA_ENTRY row 2 cols name_107
      READ_2DA_ENTRY row 3 cols desc_107
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~108~) BEGIN
      READ_2DA_ENTRY row 2 cols name_108
      READ_2DA_ENTRY row 3 cols desc_108
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~109~) BEGIN
      READ_2DA_ENTRY row 2 cols name_109
      READ_2DA_ENTRY row 3 cols desc_109
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~110~) BEGIN
      READ_2DA_ENTRY row 2 cols name_110
      READ_2DA_ENTRY row 3 cols desc_110
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~111~) BEGIN
      READ_2DA_ENTRY row 2 cols name_111
      READ_2DA_ENTRY row 3 cols desc_111
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~112~) BEGIN
      READ_2DA_ENTRY row 2 cols name_112
      READ_2DA_ENTRY row 3 cols desc_112
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~113~) BEGIN
      READ_2DA_ENTRY row 2 cols name_113
      READ_2DA_ENTRY row 3 cols desc_113
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~114~) BEGIN
      READ_2DA_ENTRY row 2 cols name_114
      READ_2DA_ENTRY row 3 cols desc_114
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~115~) BEGIN
      READ_2DA_ENTRY row 2 cols name_115
      READ_2DA_ENTRY row 3 cols desc_115
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~124~) BEGIN
      READ_2DA_ENTRY row 2 cols name_124
      READ_2DA_ENTRY row 3 cols desc_124
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~127~) BEGIN
      READ_2DA_ENTRY row 2 cols name_127
      READ_2DA_ENTRY row 3 cols desc_127
    END
    PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~134~) BEGIN
      READ_2DA_ENTRY row 2 cols name_134
      READ_2DA_ENTRY row 3 cols desc_134
    END
  END
BUT_ONLY

ACTION_IF !(VARIABLE_IS_SET %name_89%) BEGIN
  OUTER_SET name_89 = RESOLVE_STR_REF (~stat_89 ~)
  OUTER_SET desc_89 = RESOLVE_STR_REF (~stat_89 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_90%) BEGIN
  OUTER_SET name_90 = RESOLVE_STR_REF (~stat_90 ~)
  OUTER_SET desc_90 = RESOLVE_STR_REF (~stat_90 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_91%) BEGIN
  OUTER_SET name_91 = RESOLVE_STR_REF (~stat_91 ~)
  OUTER_SET desc_91 = RESOLVE_STR_REF (~stat_91 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_92%) BEGIN
  OUTER_SET name_92 = RESOLVE_STR_REF (~stat_92 ~)
  OUTER_SET desc_92 = RESOLVE_STR_REF (~stat_92 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_93%) BEGIN
  OUTER_SET name_93 = RESOLVE_STR_REF (~stat_93 ~)
  OUTER_SET desc_93 = RESOLVE_STR_REF (~stat_93 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_94%) BEGIN
  OUTER_SET name_94 = RESOLVE_STR_REF (~stat_94 ~)
  OUTER_SET desc_94 = RESOLVE_STR_REF (~stat_94 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_95%) BEGIN
  OUTER_SET name_95 = RESOLVE_STR_REF (~stat_95 ~)
  OUTER_SET desc_95 = RESOLVE_STR_REF (~stat_95 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_96%) BEGIN
  OUTER_SET name_96 = RESOLVE_STR_REF (~stat_96 ~)
  OUTER_SET desc_96 = RESOLVE_STR_REF (~stat_96 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_97%) BEGIN
  OUTER_SET name_97 = RESOLVE_STR_REF (~stat_97 ~)
  OUTER_SET desc_97 = RESOLVE_STR_REF (~stat_97 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_98%) BEGIN
  OUTER_SET name_98 = RESOLVE_STR_REF (~stat_98 ~)
  OUTER_SET desc_98 = RESOLVE_STR_REF (~stat_98 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_99%) BEGIN
  OUTER_SET name_99 = RESOLVE_STR_REF (~stat_99 ~)
  OUTER_SET desc_99 = RESOLVE_STR_REF (~stat_99 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_100%) BEGIN
  OUTER_SET name_100 = RESOLVE_STR_REF (~stat_100 ~)
  OUTER_SET desc_100 = RESOLVE_STR_REF (~stat_100 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_101%) BEGIN
  OUTER_SET name_101 = RESOLVE_STR_REF (~stat_101 ~)
  OUTER_SET desc_101 = RESOLVE_STR_REF (~stat_101 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_102%) BEGIN
  OUTER_SET name_102 = RESOLVE_STR_REF (~stat_102 ~)
  OUTER_SET desc_102 = RESOLVE_STR_REF (~stat_102 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_103%) BEGIN
  OUTER_SET name_103 = RESOLVE_STR_REF (~stat_103 ~)
  OUTER_SET desc_103 = RESOLVE_STR_REF (~stat_103 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_104%) BEGIN
  OUTER_SET name_104 = RESOLVE_STR_REF (~stat_104 ~)
  OUTER_SET desc_104 = RESOLVE_STR_REF (~stat_104 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_105%) BEGIN
  OUTER_SET name_105 = RESOLVE_STR_REF (~stat_105 ~)
  OUTER_SET desc_105 = RESOLVE_STR_REF (~stat_105 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_106%) BEGIN
  OUTER_SET name_106 = RESOLVE_STR_REF (~stat_106 ~)
  OUTER_SET desc_106 = RESOLVE_STR_REF (~stat_106 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_107%) BEGIN
  OUTER_SET name_107 = RESOLVE_STR_REF (~stat_107 ~)
  OUTER_SET desc_107 = RESOLVE_STR_REF (~stat_107 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_108%) BEGIN
  OUTER_SET name_108 = RESOLVE_STR_REF (~stat_108 ~)
  OUTER_SET desc_108 = RESOLVE_STR_REF (~stat_108 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_109%) BEGIN
  OUTER_SET name_109 = RESOLVE_STR_REF (~stat_109 ~)
  OUTER_SET desc_109 = RESOLVE_STR_REF (~stat_109 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_110%) BEGIN
  OUTER_SET name_110 = RESOLVE_STR_REF (~stat_110 ~)
  OUTER_SET desc_110 = RESOLVE_STR_REF (~stat_110 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_111%) BEGIN
  OUTER_SET name_111 = RESOLVE_STR_REF (~stat_111 ~)
  OUTER_SET desc_111 = RESOLVE_STR_REF (~stat_111 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_112%) BEGIN
  OUTER_SET name_112 = RESOLVE_STR_REF (~stat_112 ~)
  OUTER_SET desc_112 = RESOLVE_STR_REF (~stat_112 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_113%) BEGIN
  OUTER_SET name_113 = RESOLVE_STR_REF (~stat_113 ~)
  OUTER_SET desc_113 = RESOLVE_STR_REF (~stat_113 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_114%) BEGIN
  OUTER_SET name_114 = RESOLVE_STR_REF (~stat_114 ~)
  OUTER_SET desc_114 = RESOLVE_STR_REF (~stat_114 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_115%) BEGIN
  OUTER_SET name_115 = RESOLVE_STR_REF (~stat_115 ~)
  OUTER_SET desc_115 = RESOLVE_STR_REF (~stat_115 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_124%) BEGIN
  OUTER_SET name_124 = RESOLVE_STR_REF (~stat_124 ~)
  OUTER_SET desc_124 = RESOLVE_STR_REF (~stat_124 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_127%) BEGIN
  OUTER_SET name_127 = RESOLVE_STR_REF (~stat_127 ~)
  OUTER_SET desc_127 = RESOLVE_STR_REF (~stat_127 ~)
END
ACTION_IF !(VARIABLE_IS_SET %name_134%) BEGIN
  OUTER_SET name_134 = RESOLVE_STR_REF (~stat_134 ~)
  OUTER_SET desc_134 = RESOLVE_STR_REF (~stat_134 ~)
END

//__________________________________________________________________________________

<<<<<<<< d5/d5_cprf_temp.baf

>>>>>>>>

COPY ~d5/d5_cprf_temp.baf~ ~weidu_external/%MOD_FOLDER%/dialprof/%prof_script_name%_temp.baf~


//initial proficiencies______________________________________________________________
//
COPY_EXISTING ~profs.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW ~profs~ cols
  FOR (row = 0; row < profs; ++row) BEGIN
    READ_2DA_ENTRY_FORMER profs row 0 prof_class
    READ_2DA_ENTRY_FORMER profs row 1 init_profs
    READ_2DA_ENTRY_FORMER profs row 2 prof_rate
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~FIGHTER~) BEGIN
      SET fighter_init_profs = init_profs
      SPRINT $class_init_profs(~fi~)~%fighter_init_profs%~
      SET fighter_prof_rate = prof_rate
    END
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~RANGER~) BEGIN
      SET ranger_init_profs = init_profs
      SET ranger_prof_rate = prof_rate
    END
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~PALADIN~) BEGIN
      SET paladin_init_profs = init_profs
      SET paladin_prof_rate = prof_rate
    END
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~CLERIC~) BEGIN
      SET cleric_init_profs = init_profs
      SET cleric_prof_rate = prof_rate
    END
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~DRUID~) BEGIN
      SET druid_init_profs = init_profs
      SET druid_prof_rate = prof_rate
    END
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~SHAMAN~) BEGIN
      SET shaman_init_profs = init_profs
      SET shaman_prof_rate = prof_rate
    END
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~THIEF~) BEGIN
      SET thief_init_profs = init_profs
      SET thief_prof_rate = prof_rate
    END
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~BARD~) BEGIN
      SET bard_init_profs = init_profs
      SET bard_prof_rate = prof_rate
    END
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~MAGE~) BEGIN
      SET mage_init_profs = init_profs
      SET mage_prof_rate = prof_rate
    END
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~SORCERER~) BEGIN
      SET sorcerer_init_profs = init_profs
      SET sorcerer_prof_rate = prof_rate
    END
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~MONK~) BEGIN
      SET monk_init_profs = init_profs
      SET monk_prof_rate = prof_rate
    END
  END
BUT_ONLY

//__________________________________________________________________________________

ACTION_IF (script_level_one = 1) BEGIN
  APPEND_OUTER ~weidu_external/%MOD_FOLDER%/dialprof/%prof_script_name%_temp.baf~
~
IF
	Global("D5PRSET","GLOBAL",0)
	Class(LastSummonerOf(Myself),FIGHTER)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",%fighter_init_profs%)
END
IF
	Global("D5PRSET","GLOBAL",0)
	Class(LastSummonerOf(Myself),FIGHTER_CLERIC)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",%ranger_init_profs%)
END
IF
	Global("D5PRSET","GLOBAL",0)
	Class(LastSummonerOf(Myself),FIGHTER_DRUID)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",%ranger_init_profs%)
END
IF
	Global("D5PRSET","GLOBAL",0)
	Class(LastSummonerOf(Myself),FIGHTER_MAGE)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",%ranger_init_profs%)
END
IF
	Global("D5PRSET","GLOBAL",0)
	Class(LastSummonerOf(Myself),FIGHTER_THIEF)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",%fighter_init_profs%)
END
IF
	Global("D5PRSET","GLOBAL",0)
	Class(LastSummonerOf(Myself),FIGHTER_MAGE_THIEF)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",%ranger_init_profs%)
END
IF
	Global("D5PRSET","GLOBAL",0)
	Class(LastSummonerOf(Myself),FIGHTER_MAGE_CLERIC)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",%ranger_init_profs%)
END

IF
	Global("D5PRSET","GLOBAL",0)
	Class(LastSummonerOf(Myself),RANGER)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",%ranger_init_profs%)
END
IF
	Global("D5PRSET","GLOBAL",0)
	Class(LastSummonerOf(Myself),CLERIC_RANGER)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",%ranger_init_profs%)
END

IF
	Global("D5PRSET","GLOBAL",0)
	Class(LastSummonerOf(Myself),PALADIN)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",%paladin_init_profs%)
END

IF
	Global("D5PRSET","GLOBAL",0)
	Class(LastSummonerOf(Myself),CLERIC)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",%cleric_init_profs%)
END
IF
	Global("D5PRSET","GLOBAL",0)
	Class(LastSummonerOf(Myself),CLERIC_THIEF)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",%cleric_init_profs%)
END
IF
	Global("D5PRSET","GLOBAL",0)
	Class(LastSummonerOf(Myself),CLERIC_MAGE)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",%cleric_init_profs%)
END

IF
	Global("D5PRSET","GLOBAL",0)
	Class(LastSummonerOf(Myself),DRUID)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",%druid_init_profs%)
END

IF
	Global("D5PRSET","GLOBAL",0)
	Class(LastSummonerOf(Myself),SHAMAN)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",%shaman_init_profs%)
END

IF
	Global("D5PRSET","GLOBAL",0)
	Class(LastSummonerOf(Myself),THIEF)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",%thief_init_profs%)
END
IF
	Global("D5PRSET","GLOBAL",0)
	Class(LastSummonerOf(Myself),MAGE_THIEF)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",%thief_init_profs%)
END

IF
	Global("D5PRSET","GLOBAL",0)
	Class(LastSummonerOf(Myself),BARD)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",%bard_init_profs%)
END

IF
	Global("D5PRSET","GLOBAL",0)
	Class(LastSummonerOf(Myself),MAGE)
	!Class(LastSummonerOf(Myself),SORCERER)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",%mage_init_profs%)
END

IF
	Global("D5PRSET","GLOBAL",0)
	Class(LastSummonerOf(Myself),SORCERER)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",%sorcerer_init_profs%)
END

IF
	Global("D5PRSET","GLOBAL",0)
	Class(LastSummonerOf(Myself),MONK)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",%monk_init_profs%)
END
~ KEEP_CRLF
END

//__________________________________________________________________________________

/* don't need to do this anymore
COPY ~d5/d5_cprf_temp.baf~ ~weidu_external/%MOD_FOLDER%/dialprof/%prof_script_name%_temp.baf~
  REPLACE_TEXTUALLY ~fighter_init_profs~ ~%fighter_init_profs%~
  REPLACE_TEXTUALLY ~ranger_init_profs~ ~%ranger_init_profs%~
  REPLACE_TEXTUALLY ~paladin_init_profs~ ~%paladin_init_profs%~
  REPLACE_TEXTUALLY ~cleric_init_profs~ ~%cleric_init_profs%~
  REPLACE_TEXTUALLY ~druid_init_profs~ ~%druid_init_profs%~
  REPLACE_TEXTUALLY ~shaman_init_profs~ ~%shaman_init_profs%~
  REPLACE_TEXTUALLY ~thief_init_profs~ ~%thief_init_profs%~
  REPLACE_TEXTUALLY ~bard_init_profs~ ~%bard_init_profs%~
  REPLACE_TEXTUALLY ~mage_init_profs~ ~%mage_init_profs%~
  REPLACE_TEXTUALLY ~sorcerer_init_profs~ ~%sorcerer_init_profs%~
  REPLACE_TEXTUALLY ~monk_init_profs~ ~%monk_init_profs%~
*/

//__________________________________________________________________________________

ACTION_IF (script_higher_levels = 1) BEGIN
  OUTER_FOR (lvl = 1; lvl < 25; ++lvl) BEGIN
    OUTER_SET more_fighter_profs = (lvl/%fighter_prof_rate%)
    OUTER_SET more_ranger_profs = (lvl/%ranger_prof_rate%)
    OUTER_SET more_paladin_profs = (lvl/%paladin_prof_rate%)
    OUTER_SET more_cleric_profs = (lvl/%cleric_prof_rate%)
    OUTER_SET more_druid_profs = (lvl/%druid_prof_rate%)
    OUTER_SET more_shaman_profs = (lvl/%shaman_prof_rate%)
    OUTER_SET more_thief_profs = (lvl/%thief_prof_rate%)
    OUTER_SET more_bard_profs = (lvl/%bard_prof_rate%)
    OUTER_SET more_mage_profs = (lvl/%mage_prof_rate%)
    OUTER_SET more_sorcerer_profs = (lvl/%sorcerer_prof_rate%)
    OUTER_SET more_monk_profs = (lvl/%monk_prof_rate%)
    APPEND_OUTER ~weidu_external/%MOD_FOLDER%/dialprof/%prof_script_name%_temp.baf~
~IF
	Global("D5PRSET","GLOBAL",1)
	Global("D5PRMOR","GLOBAL",0)
	Level(LastSummonerOf(Myself),%lvl%)
	Class(LastSummonerOf(Myself),FIGHTER)
THEN
	RESPONSE #100
	SetGlobal("D5PRMOR","GLOBAL",1)
	IncrementGlobal("D5_KIT_PRF","GLOBAL",%more_fighter_profs%)
END
IF
	Global("D5PRSET","GLOBAL",1)
	Global("D5PRMOR","GLOBAL",0)
	Level(LastSummonerOf(Myself),%lvl%)
	Class(LastSummonerOf(Myself),THIEF)
THEN
	RESPONSE #100
	SetGlobal("D5PRMOR","GLOBAL",1)
	IncrementGlobal("D5_KIT_PRF","GLOBAL",%more_thief_profs%)
END
IF
	Global("D5PRSET","GLOBAL",1)
	Global("D5PRMOR","GLOBAL",0)
	Level(LastSummonerOf(Myself),%lvl%)
	Class(LastSummonerOf(Myself),PALADIN)
THEN
	RESPONSE #100
	SetGlobal("D5PRMOR","GLOBAL",1)
	IncrementGlobal("D5_KIT_PRF","GLOBAL",%more_paladin_profs%)
END
IF
	Global("D5PRSET","GLOBAL",1)
	Global("D5PRMOR","GLOBAL",0)
	Level(LastSummonerOf(Myself),%lvl%)
	Class(LastSummonerOf(Myself),RANGER)
THEN
	RESPONSE #100
	SetGlobal("D5PRMOR","GLOBAL",1)
	IncrementGlobal("D5_KIT_PRF","GLOBAL",%more_ranger_profs%)
END
IF
	Global("D5PRSET","GLOBAL",1)
	Global("D5PRMOR","GLOBAL",0)
	Level(LastSummonerOf(Myself),%lvl%)
	Class(LastSummonerOf(Myself),CLERIC)
THEN
	RESPONSE #100
	SetGlobal("D5PRMOR","GLOBAL",1)
	IncrementGlobal("D5_KIT_PRF","GLOBAL",%more_cleric_profs%)
END
IF
	Global("D5PRSET","GLOBAL",1)
	Global("D5PRMOR","GLOBAL",0)
	Level(LastSummonerOf(Myself),%lvl%)
	Class(LastSummonerOf(Myself),DRUID)
THEN
	RESPONSE #100
	SetGlobal("D5PRMOR","GLOBAL",1)
	IncrementGlobal("D5_KIT_PRF","GLOBAL",%more_druid_profs%)
END
IF
	Global("D5PRSET","GLOBAL",1)
	Global("D5PRMOR","GLOBAL",0)
	Level(LastSummonerOf(Myself),%lvl%)
	Class(LastSummonerOf(Myself),BARD)
THEN
	RESPONSE #100
	SetGlobal("D5PRMOR","GLOBAL",1)
	IncrementGlobal("D5_KIT_PRF","GLOBAL",%more_bard_profs%)
END
IF
	Global("D5PRSET","GLOBAL",1)
	Global("D5PRMOR","GLOBAL",0)
	Level(LastSummonerOf(Myself),%lvl%)
	Class(LastSummonerOf(Myself),MAGE)
THEN
	RESPONSE #100
	SetGlobal("D5PRMOR","GLOBAL",1)
	IncrementGlobal("D5_KIT_PRF","GLOBAL",%more_mage_profs%)
END
IF
	Global("D5PRSET","GLOBAL",1)
	Global("D5PRMOR","GLOBAL",0)
	Level(LastSummonerOf(Myself),%lvl%)
	Class(LastSummonerOf(Myself),SORCERER)
THEN
	RESPONSE #100
	SetGlobal("D5PRMOR","GLOBAL",1)
	IncrementGlobal("D5_KIT_PRF","GLOBAL",%more_sorcerer_profs%)
END
IF
	Global("D5PRSET","GLOBAL",1)
	Global("D5PRMOR","GLOBAL",0)
	Level(LastSummonerOf(Myself),%lvl%)
	Class(LastSummonerOf(Myself),MONK)
THEN
	RESPONSE #100
	SetGlobal("D5PRMOR","GLOBAL",1)
	IncrementGlobal("D5_KIT_PRF","GLOBAL",%more_monk_profs%)
END
IF
	Global("D5PRSET","GLOBAL",1)
	Global("D5PRMOR","GLOBAL",0)
	Level(LastSummonerOf(Myself),%lvl%)
	Class(LastSummonerOf(Myself),FIGHTER_MAGE)
THEN
	RESPONSE #100
	SetGlobal("D5PRMOR","GLOBAL",1)
	IncrementGlobal("D5_KIT_PRF","GLOBAL",%more_fighter_profs%)
END
IF
	Global("D5PRSET","GLOBAL",1)
	Global("D5PRMOR","GLOBAL",0)
	Level(LastSummonerOf(Myself),%lvl%)
	Class(LastSummonerOf(Myself),FIGHTER_CLERIC)
THEN
	RESPONSE #100
	SetGlobal("D5PRMOR","GLOBAL",1)
	IncrementGlobal("D5_KIT_PRF","GLOBAL",%more_fighter_profs%)
END
IF
	Global("D5PRSET","GLOBAL",1)
	Global("D5PRMOR","GLOBAL",0)
	Level(LastSummonerOf(Myself),%lvl%)
	Class(LastSummonerOf(Myself),FIGHTER_THIEF)
THEN
	RESPONSE #100
	SetGlobal("D5PRMOR","GLOBAL",1)
	IncrementGlobal("D5_KIT_PRF","GLOBAL",%more_fighter_profs%)
END
IF
	Global("D5PRSET","GLOBAL",1)
	Global("D5PRMOR","GLOBAL",0)
	Level(LastSummonerOf(Myself),%lvl%)
	Class(LastSummonerOf(Myself),FIGHTER_DRUID)
THEN
	RESPONSE #100
	SetGlobal("D5PRMOR","GLOBAL",1)
	IncrementGlobal("D5_KIT_PRF","GLOBAL",%more_fighter_profs%)
END
IF
	Global("D5PRSET","GLOBAL",1)
	Global("D5PRMOR","GLOBAL",0)
	Level(LastSummonerOf(Myself),%lvl%)
	Class(LastSummonerOf(Myself),CLERIC_RANGER)
THEN
	RESPONSE #100
	SetGlobal("D5PRMOR","GLOBAL",1)
	IncrementGlobal("D5_KIT_PRF","GLOBAL",%more_ranger_profs%)
END
IF
	Global("D5PRSET","GLOBAL",1)
	Global("D5PRMOR","GLOBAL",0)
	Level(LastSummonerOf(Myself),%lvl%)
	Class(LastSummonerOf(Myself),CLERIC_THIEF)
THEN
	RESPONSE #100
	SetGlobal("D5PRMOR","GLOBAL",1)
	IncrementGlobal("D5_KIT_PRF","GLOBAL",%more_thief_profs%)
END
IF
	Global("D5PRSET","GLOBAL",1)
	Global("D5PRMOR","GLOBAL",0)
	Level(LastSummonerOf(Myself),%lvl%)
	Class(LastSummonerOf(Myself),MAGE_THIEF)
THEN
	RESPONSE #100
	SetGlobal("D5PRMOR","GLOBAL",1)
	IncrementGlobal("D5_KIT_PRF","GLOBAL",%more_thief_profs%)
END
IF
	Global("D5PRSET","GLOBAL",1)
	Global("D5PRMOR","GLOBAL",0)
	Level(LastSummonerOf(Myself),%lvl%)
	Class(LastSummonerOf(Myself),FIGHTER_MAGE_CLERIC)
THEN
	RESPONSE #100
	SetGlobal("D5PRMOR","GLOBAL",1)
	IncrementGlobal("D5_KIT_PRF","GLOBAL",%more_fighter_profs%)
END
IF
	Global("D5PRSET","GLOBAL",1)
	Global("D5PRMOR","GLOBAL",0)
	Level(LastSummonerOf(Myself),%lvl%)
	Class(LastSummonerOf(Myself),FIGHTER_MAGE_THIEF)
THEN
	RESPONSE #100
	SetGlobal("D5PRMOR","GLOBAL",1)
	IncrementGlobal("D5_KIT_PRF","GLOBAL",%more_fighter_profs%)
END
~ KEEP_CRLF
  END
END

//__________________________________________________________________________________

ACTION_IF (%script_level_one% = 0) AND (%script_higher_levels% = 0) BEGIN
  APPEND_OUTER ~weidu_external/%MOD_FOLDER%/dialprof/%prof_script_name%_temp.baf~
~
IF
	Global("D5PRSET","GLOBAL",0)
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",1)
	SetGlobal("D5_KIT_PRF","GLOBAL",1)
END
~ KEEP_CRLF
END

//__________________________________________________________________________________

ACTION_DEFINE_ASSOCIATIVE_ARRAY d5_kits_profs BEGIN
 MAGE , class , MAGE					=> 	3
 FIGHTER , class , FIGHTER 				=> 	4
 CLERIC , class , CLERIC 				=> 	5
 THIEF , class , THIEF 					=> 	6
 BARD , class , BARD 					=> 	7
 PALADIN , class , PALADIN 				=> 	8
 DRUID , class , DRUID 					=> 	9
 RANGER , class , RANGER 				=> 	10
 FIGHTER_MAGE , class , FIGHTER_MAGE 		=> 	11
 FIGHTER_CLERIC , class , FIGHTER_CLERIC 	=> 	12
 FIGHTER_THIEF , class , FIGHTER_THIEF 		=> 	13
 FIGHTER_MAGE_THIEF , class , FIGHTER_MAGE_THIEF 	=> 	14
 MAGE_THIEF , class , MAGE_THIEF 			=> 	15
 CLERIC_MAGE , class , CLERIC_MAGE 			=> 	16
 CLERIC_THIEF , class , CLERIC_THIEF 		=> 	17
 FIGHTER_DRUID , class , FIGHTER_DRUID 		=> 	18
 FIGHTER_MAGE_CLERIC , class , FIGHTER_MAGE_CLERIC => 	19
 CLERIC_RANGER , class , CLERIC_RANGER 		=> 	20
 MONK , class , MONK 					=> 	50
END

ACTION_IF (FILE_EXISTS_IN_GAME ~clabshgs.2da~) OR (FILE_EXISTS_IN_GAME ~clabsh01.2da~) BEGIN
  OUTER_SPRINT $d5_kits_profs(~SHAMAN~ ~class~) ~59~
END

COPY_EXISTING ~kitlist.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW ~r2en_kitlist~ cols
  FOR (row = 1; row < r2en_kitlist; row += 1) BEGIN
	READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 6 prof_col
	READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 8 classids_num
	READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 9 kitids_num
	LOOKUP_IDS_SYMBOL_OF_INT kitids_name ~kit~ %kitids_num%
	LOOKUP_IDS_SYMBOL_OF_INT classids_name ~class~ %classids_num%
	PATCH_IF (classids_num = 1) BEGIN
	  SPRINT short_class ~ma~
	END
	PATCH_IF (classids_num = 2) OR (classids_num = 7) OR (classids_num = 8) OR (classids_num = 9) OR (classids_num = 10) OR (classids_num = 16) OR (classids_num = 17) BEGIN
	  SPRINT short_class ~fi~
	END
	PATCH_IF (classids_num = 3) OR (classids_num = 14) OR (classids_num = 15) BEGIN
	  SPRINT short_class ~cl~
	END
	PATCH_IF (classids_num = 4) OR (classids_num = 13) BEGIN
	  SPRINT short_class ~th~
	END
	PATCH_IF (classids_num = 5) BEGIN
	  SPRINT short_class ~ba~
	END
	PATCH_IF (classids_num = 6) BEGIN
	  SPRINT short_class ~pa~
	END
	PATCH_IF (classids_num = 11) BEGIN
	  SPRINT short_class ~dr~
	END
	PATCH_IF (classids_num = 12) OR (classids_num = 18) BEGIN
	  SPRINT short_class ~ra~
	END
	PATCH_IF (classids_num = 19) BEGIN
	  SPRINT short_class ~so~
	END
	PATCH_IF (classids_num = 20) BEGIN
	  SPRINT short_class ~mo~
	END
	PATCH_IF (classids_num = 21) BEGIN
	  SPRINT short_class ~sh~
	END
	PATCH_IF (VARIABLE_IS_SET %kitids_name%) AND (VARIABLE_IS_SET %classids_name%) BEGIN
	  SPRINT $d5_kits_profs(~%kitids_name%~ ~kit~ ~%classids_name%~ ~%short_class%~) ~%prof_col%~
	END
  END

ACTION_PHP_EACH d5_kits_profs AS kitidsname => profcol BEGIN
//  PRINT ~%kitidsname% = %kitidsname_1% = column %profcol%~
  ACTION_IF (~%kitidsname_1%~ STRING_EQUAL_CASE ~kit~) BEGIN
	APPEND_OUTER ~weidu_external/%MOD_FOLDER%/dialprof/%prof_script_name%_temp.baf~ ~
IF
	Global("D5PRSET","GLOBAL",1)
	GlobalGT("D5_KIT_PRF","GLOBAL",0)
	Kit(LastSummonerOf(Myself),%kitidsname%)
	Class(LastSummonerOf(Myself),%kitidsname_2%)
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	IncrementGlobal("D5_KIT_PRF","GLOBAL",-1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("%prof_script_name%%kitidsname_3%",Myself))
END
~ KEEP_CRLF
  END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~clabshgs.2da~) OR (FILE_EXISTS_IN_GAME ~clabsh01.2da~) BEGIN

  APPEND_OUTER ~weidu_external/%MOD_FOLDER%/dialprof/%prof_script_name%_temp.baf~ ~
IF
	Global("D5PRSET","GLOBAL",1)
	GlobalGT("D5_KIT_PRF","GLOBAL",0)
	Class(LastSummonerOf(Myself),SHAMAN)
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_SHAMAN_PRF","LOCALS",1))
	IncrementGlobal("D5_KIT_PRF","GLOBAL",-1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("%prof_script_name%sh",Myself))
END
~ KEEP_CRLF

END

APPEND_OUTER ~weidu_external/%MOD_FOLDER%/dialprof/%prof_script_name%_temp.baf~ ~
IF
	Global("D5PRSET","GLOBAL",1)
	GlobalGT("D5_KIT_PRF","GLOBAL",0)
	Class(LastSummonerOf(Myself),MAGE)
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_MAGE_PRF","LOCALS",1))
	IncrementGlobal("D5_KIT_PRF","GLOBAL",-1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("%prof_script_name%ma",Myself))
END

IF
	Global("D5PRSET","GLOBAL",1)
	GlobalGT("D5_KIT_PRF","GLOBAL",0)
	Class(LastSummonerOf(Myself),FIGHTER)
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_FIGHTER_PRF","LOCALS",1))
	IncrementGlobal("D5_KIT_PRF","GLOBAL",-1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("%prof_script_name%fi",Myself))
END

IF
	Global("D5PRSET","GLOBAL",1)
	GlobalGT("D5_KIT_PRF","GLOBAL",0)
	Class(LastSummonerOf(Myself),CLERIC)
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_CLERIC_PRF","LOCALS",1))
	IncrementGlobal("D5_KIT_PRF","GLOBAL",-1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("%prof_script_name%cl",Myself))
END

IF
	Global("D5PRSET","GLOBAL",1)
	GlobalGT("D5_KIT_PRF","GLOBAL",0)
	Class(LastSummonerOf(Myself),THIEF)
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_THIEF_PRF","LOCALS",1))
	IncrementGlobal("D5_KIT_PRF","GLOBAL",-1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("%prof_script_name%th",Myself))
END

IF
	Global("D5PRSET","GLOBAL",1)
	GlobalGT("D5_KIT_PRF","GLOBAL",0)
	Class(LastSummonerOf(Myself),BARD)
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_BARD_PRF","LOCALS",1))
	IncrementGlobal("D5_KIT_PRF","GLOBAL",-1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("%prof_script_name%ba",Myself))
END

IF
	Global("D5PRSET","GLOBAL",1)
	GlobalGT("D5_KIT_PRF","GLOBAL",0)
	Class(LastSummonerOf(Myself),PALADIN)
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PALADIN_PRF","LOCALS",1))
	IncrementGlobal("D5_KIT_PRF","GLOBAL",-1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("%prof_script_name%pa",Myself))
END

IF
	Global("D5PRSET","GLOBAL",1)
	GlobalGT("D5_KIT_PRF","GLOBAL",0)
	Class(LastSummonerOf(Myself),DRUID)
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_DRUID_PRF","LOCALS",1))
	IncrementGlobal("D5_KIT_PRF","GLOBAL",-1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("%prof_script_name%dr",Myself))
END

IF
	Global("D5PRSET","GLOBAL",1)
	GlobalGT("D5_KIT_PRF","GLOBAL",0)
	Class(LastSummonerOf(Myself),RANGER)
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_RANGER_PRF","LOCALS",1))
	IncrementGlobal("D5_KIT_PRF","GLOBAL",-1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("%prof_script_name%ra",Myself))
END

IF
	Global("D5PRSET","GLOBAL",1)
	GlobalGT("D5_KIT_PRF","GLOBAL",0)
	Class(LastSummonerOf(Myself),FIGHTER_MAGE)
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_FIGHTER_MAGE_PRF","LOCALS",1))
	IncrementGlobal("D5_KIT_PRF","GLOBAL",-1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("%prof_script_name%fi",Myself))
END

IF
	Global("D5PRSET","GLOBAL",1)
	GlobalGT("D5_KIT_PRF","GLOBAL",0)
	Class(LastSummonerOf(Myself),FIGHTER_CLERIC)
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_FIGHTER_CLERIC_PRF","LOCALS",1))
	IncrementGlobal("D5_KIT_PRF","GLOBAL",-1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("%prof_script_name%fi",Myself))
END

IF
	Global("D5PRSET","GLOBAL",1)
	GlobalGT("D5_KIT_PRF","GLOBAL",0)
	Class(LastSummonerOf(Myself),FIGHTER_THIEF)
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_FIGHTER_THIEF_PRF","LOCALS",1))
	IncrementGlobal("D5_KIT_PRF","GLOBAL",-1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("%prof_script_name%fi",Myself))
END

IF
	Global("D5PRSET","GLOBAL",1)
	GlobalGT("D5_KIT_PRF","GLOBAL",0)
	Class(LastSummonerOf(Myself),FIGHTER_MAGE_THIEF)
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_FIGHTER_MAGE_THIEF_PRF","LOCALS",1))
	IncrementGlobal("D5_KIT_PRF","GLOBAL",-1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("%prof_script_name%fi",Myself))
END

IF
	Global("D5PRSET","GLOBAL",1)
	GlobalGT("D5_KIT_PRF","GLOBAL",0)
	Class(LastSummonerOf(Myself),MAGE_THIEF)
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_MAGE_THIEF_PRF","LOCALS",1))
	IncrementGlobal("D5_KIT_PRF","GLOBAL",-1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("%prof_script_name%th",Myself))
END

IF
	Global("D5PRSET","GLOBAL",1)
	GlobalGT("D5_KIT_PRF","GLOBAL",0)
	Class(LastSummonerOf(Myself),CLERIC_MAGE)
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_CLERIC_MAGE_PRF","LOCALS",1))
	IncrementGlobal("D5_KIT_PRF","GLOBAL",-1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("%prof_script_name%cl",Myself))
END

IF
	Global("D5PRSET","GLOBAL",1)
	GlobalGT("D5_KIT_PRF","GLOBAL",0)
	Class(LastSummonerOf(Myself),CLERIC_THIEF)
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_CLERIC_THIEF_PRF","LOCALS",1))
	IncrementGlobal("D5_KIT_PRF","GLOBAL",-1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("%prof_script_name%cl",Myself))
END

IF
	Global("D5PRSET","GLOBAL",1)
	GlobalGT("D5_KIT_PRF","GLOBAL",0)
	Class(LastSummonerOf(Myself),FIGHTER_DRUID)
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_FIGHTER_DRUID_PRF","LOCALS",1))
	IncrementGlobal("D5_KIT_PRF","GLOBAL",-1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("%prof_script_name%fi",Myself))
END

IF
	Global("D5PRSET","GLOBAL",1)
	GlobalGT("D5_KIT_PRF","GLOBAL",0)
	Class(LastSummonerOf(Myself),FIGHTER_MAGE_CLERIC)
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_FIGHTER_MAGE_CLERIC_PRF","LOCALS",1))
	IncrementGlobal("D5_KIT_PRF","GLOBAL",-1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("%prof_script_name%fi",Myself))
END

IF
	Global("D5PRSET","GLOBAL",1)
	GlobalGT("D5_KIT_PRF","GLOBAL",0)
	Class(LastSummonerOf(Myself),CLERIC_RANGER)
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_CLERIC_RANGER_PRF","LOCALS",1))
	IncrementGlobal("D5_KIT_PRF","GLOBAL",-1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("%prof_script_name%ra",Myself))
END

IF
	Global("D5PRSET","GLOBAL",1)
	GlobalGT("D5_KIT_PRF","GLOBAL",0)
	Class(LastSummonerOf(Myself),MONK)
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_MONK_PRF","LOCALS",1))
	IncrementGlobal("D5_KIT_PRF","GLOBAL",-1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("%prof_script_name%mo",Myself))
END

IF
	True()
THEN
	RESPONSE #100
	SetGlobal("D5PRSET","GLOBAL",0)
	SetGlobal("D5_KIT_PRF","GLOBAL",0)
	SetGlobal("D5_PROF_89","LOCALS",0)
	SetGlobal("D5_PROF_90","LOCALS",0)
	SetGlobal("D5_PROF_91","LOCALS",0)
	SetGlobal("D5_PROF_92","LOCALS",0)
	SetGlobal("D5_PROF_93","LOCALS",0)
	SetGlobal("D5_PROF_94","LOCALS",0)
	SetGlobal("D5_PROF_95","LOCALS",0)
	SetGlobal("D5_PROF_96","LOCALS",0)
	SetGlobal("D5_PROF_97","LOCALS",0)
	SetGlobal("D5_PROF_115","LOCALS",0)
	SetGlobal("D5_PROF_98","LOCALS",0)
	SetGlobal("D5_PROF_99","LOCALS",0)
	SetGlobal("D5_PROF_100","LOCALS",0)
	SetGlobal("D5_PROF_101","LOCALS",0)
	SetGlobal("D5_PROF_102","LOCALS",0)
	SetGlobal("D5_PROF_103","LOCALS",0)
	SetGlobal("D5_PROF_104","LOCALS",0)
	SetGlobal("D5_PROF_105","LOCALS",0)
	SetGlobal("D5_PROF_106","LOCALS",0)
	SetGlobal("D5_PROF_107","LOCALS",0)
	SetGlobal("D5_PROF_111","LOCALS",0)
	SetGlobal("D5_PROF_112","LOCALS",0)
	SetGlobal("D5_PROF_113","LOCALS",0)
	SetGlobal("D5_PROF_114","LOCALS",0)
	SetNumTimesTalkedTo(0)
	DestroySelf()
END
~ KEEP_CRLF

// *****  need to find/replace all those variables ^^ and vv with stat numbers

COPY ~weidu_external/%MOD_FOLDER%/dialprof/%prof_script_name%_temp.baf~ ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%.baf~
  PHP_EACH d5_kits_profs AS kitidsname => profcol BEGIN
    INNER_ACTION BEGIN
      COPY_EXISTING ~weapprof.2da~ ~override~
        COUNT_2DA_COLS cols
        COUNT_2DA_ROWS 5 rows
        FOR (row = 7; row < rows; ++row) BEGIN
          READ_2DA_ENTRY row 1 cols stat
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~89~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_89
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~90~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_90
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~91~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_91
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~92~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_92
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~93~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_93
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~94~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_94
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~95~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_95
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~96~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_96
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~97~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_97
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~98~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_98
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~99~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_99
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~100~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_100
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~101~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_101
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~102~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_102
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~103~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_103
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~104~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_104
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~105~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_105
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~106~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_106
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~107~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_107
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~108~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_108
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~109~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_109
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~110~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_110
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~111~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_111
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~112~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_112
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~113~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_113
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~114~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_114
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~115~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_115
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~124~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_124
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~127~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_127
          END
          PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~134~) BEGIN
	        READ_2DA_ENTRY row (%profcol% + 1) cols prof_134
          END
        END
      BUT_ONLY
	END
    PATCH_IF !(VARIABLE_IS_SET %prof_89%) BEGIN
      SET prof_89 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_90%) BEGIN
      SET prof_90 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_91%) BEGIN
      SET prof_91 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_92%) BEGIN
      SET prof_92 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_93%) BEGIN
      SET prof_93 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_94%) BEGIN
      SET prof_94 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_95%) BEGIN
      SET prof_95 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_96%) BEGIN
      SET prof_96 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_97%) BEGIN
      SET prof_97 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_98%) BEGIN
      SET prof_98 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_99%) BEGIN
      SET prof_99 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_100%) BEGIN
      SET prof_100 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_101%) BEGIN
      SET prof_101 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_102%) BEGIN
      SET prof_102 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_103%) BEGIN
      SET prof_103 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_104%) BEGIN
      SET prof_104 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_105%) BEGIN
      SET prof_105 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_106%) BEGIN
      SET prof_106 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_107%) BEGIN
      SET prof_107 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_108%) BEGIN
      SET prof_108 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_109%) BEGIN
      SET prof_109 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_110%) BEGIN
      SET prof_110 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_111%) BEGIN
      SET prof_111 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_112%) BEGIN
      SET prof_112 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_113%) BEGIN
      SET prof_113 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_114%) BEGIN
      SET prof_114 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_115%) BEGIN
      SET prof_115 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_124%) BEGIN
      SET prof_124 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_127%) BEGIN
      SET prof_127 = 0
    END
    PATCH_IF !(VARIABLE_IS_SET %prof_134%) BEGIN
      SET prof_134 = 0
    END
	PATCH_IF (%prof_134% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_134","LOCALS",%prof_134%))~
	END
	PATCH_IF (%prof_127% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_127","LOCALS",%prof_127%))~
	END
	PATCH_IF (%prof_124% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_124","LOCALS",%prof_124%))~
	END
	PATCH_IF (%prof_115% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_115","LOCALS",%prof_115%))~
	END
	PATCH_IF (%prof_114% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_114","LOCALS",%prof_114%))~
	END
	PATCH_IF (%prof_113% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_113","LOCALS",%prof_113%))~
	END
	PATCH_IF (%prof_112% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_112","LOCALS",%prof_112%))~
	END
	PATCH_IF (%prof_111% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_111","LOCALS",%prof_111%))~
	END
	PATCH_IF (%prof_110% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_110","LOCALS",%prof_110%))~
	END
	PATCH_IF (%prof_109% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_109","LOCALS",%prof_109%))~
	END
	PATCH_IF (%prof_108% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_108","LOCALS",%prof_108%))~
	END
	PATCH_IF (%prof_107% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_107","LOCALS",%prof_107%))~
	END
	PATCH_IF (%prof_106% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_106","LOCALS",%prof_106%))~
	END
	PATCH_IF (%prof_105% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_105","LOCALS",%prof_105%))~
	END
	PATCH_IF (%prof_104% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_104","LOCALS",%prof_104%))~
	END
	PATCH_IF (%prof_103% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_103","LOCALS",%prof_103%))~
	END
	PATCH_IF (%prof_102% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_102","LOCALS",%prof_102%))~
	END
	PATCH_IF (%prof_101% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_101","LOCALS",%prof_101%))~
	END
	PATCH_IF (%prof_100% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_100","LOCALS",%prof_100%))~
	END
	PATCH_IF (%prof_99% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_99","LOCALS",%prof_99%))~
	END
	PATCH_IF (%prof_98% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_98","LOCALS",%prof_98%))~
	END
	PATCH_IF (%prof_97% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_97","LOCALS",%prof_97%))~
	END
	PATCH_IF (%prof_96% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_96","LOCALS",%prof_96%))~
	END
	PATCH_IF (%prof_95% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_95","LOCALS",%prof_95%))~
	END
	PATCH_IF (%prof_94% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_94","LOCALS",%prof_94%))~
	END
	PATCH_IF (%prof_93% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_93","LOCALS",%prof_93%))~
	END
	PATCH_IF (%prof_92% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_92","LOCALS",%prof_92%))~
	END
	PATCH_IF (%prof_91% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_91","LOCALS",%prof_91%))~
	END
	PATCH_IF (%prof_90% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_90","LOCALS",%prof_90%))~
	END
	PATCH_IF (%prof_89% > 0) BEGIN
	  REPLACE_TEXTUALLY ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))~ ~	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_%kitidsname%_PRF","LOCALS",1))
	ActionOverride(LastSummonerOf(Myself),SetGlobal("D5_PROF_89","LOCALS",%prof_89%))~
	END
  END

//__________________________________________________________________________________

COPY_EXISTING ~profsmax.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW ~profsmax~ cols
  FOR (row = 0; row < profsmax; ++row) BEGIN
    READ_2DA_ENTRY_FORMER profsmax row 0 prof_class
    READ_2DA_ENTRY_FORMER profsmax row 1 level_1_max
    READ_2DA_ENTRY_FORMER profsmax row 2 overall_max
    READ_2DA_ENTRY_FORMER profsmax row 3 level_3_max
    READ_2DA_ENTRY_FORMER profsmax row 4 level_6_max
    READ_2DA_ENTRY_FORMER profsmax row 5 level_9_max
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~fighter~) BEGIN
      PATCH_IF (~%level_1_max%~ = 2) OR (~%level_1_max%~ > 2) BEGIN
        SET fighter_sp_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 2) BEGIN
        SET fighter_sp_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 2) BEGIN
        SET fighter_sp_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 2) BEGIN
         SET fighter_sp_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ < 2) BEGIN
        SET fighter_sp_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ > 1) BEGIN
        SET fighter_sp_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 3) OR (~%level_1_max%~ > 3) BEGIN
        SET fighter_ma_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 3) BEGIN
        SET fighter_ma_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 3) BEGIN
        SET fighter_ma_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 3) BEGIN
        SET fighter_ma_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ < 3) BEGIN
        SET fighter_ma_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ > 2) BEGIN
        SET fighter_ma_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 4) OR (~%level_1_max%~ > 4) BEGIN
        SET fighter_hi_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 4) BEGIN
        SET fighter_hi_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 4) BEGIN
        SET fighter_hi_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 4) BEGIN
        SET fighter_hi_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ < 4) BEGIN
        SET fighter_hi_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ > 3) BEGIN
        SET fighter_hi_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 5) OR (~%level_1_max%~ > 5) BEGIN
        SET fighter_gm_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 5) BEGIN
        SET fighter_gm_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 5) BEGIN
        SET fighter_gm_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 5) BEGIN
        SET fighter_gm_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ < 5) BEGIN
        SET fighter_gm_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ > 4) BEGIN
        SET fighter_gm_min_level = 9
      END
    END
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~ranger~) BEGIN
      PATCH_IF (~%level_1_max%~ = 2) OR (~%level_1_max%~ > 2) BEGIN
        SET ranger_sp_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 2) BEGIN
        SET ranger_sp_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 2) BEGIN
        SET ranger_sp_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 2) BEGIN
         SET ranger_sp_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ < 2) BEGIN
        SET ranger_sp_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ > 1) BEGIN
        SET ranger_sp_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 3) OR (~%level_1_max%~ > 3) BEGIN
        SET ranger_ma_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 3) BEGIN
        SET ranger_ma_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 3) BEGIN
        SET ranger_ma_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 3) BEGIN
        SET ranger_ma_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ < 3) BEGIN
        SET ranger_ma_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ > 2) BEGIN
        SET ranger_ma_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 4) OR (~%level_1_max%~ > 4) BEGIN
        SET ranger_hi_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 4) BEGIN
        SET ranger_hi_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 4) BEGIN
        SET ranger_hi_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 4) BEGIN
        SET ranger_hi_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ < 4) BEGIN
        SET ranger_hi_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ > 3) BEGIN
        SET ranger_hi_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 5) OR (~%level_1_max%~ > 5) BEGIN
        SET ranger_gm_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 5) BEGIN
        SET ranger_gm_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 5) BEGIN
        SET ranger_gm_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 5) BEGIN
        SET ranger_gm_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ < 5) BEGIN
        SET ranger_gm_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ > 4) BEGIN
        SET ranger_gm_min_level = 9
      END
    END
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~paladin~) BEGIN
      PATCH_IF (~%level_1_max%~ = 2) OR (~%level_1_max%~ > 2) BEGIN
        SET paladin_sp_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 2) BEGIN
        SET paladin_sp_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 2) BEGIN
        SET paladin_sp_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 2) BEGIN
         SET paladin_sp_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ < 2) BEGIN
        SET paladin_sp_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ > 1) BEGIN
        SET paladin_sp_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 3) OR (~%level_1_max%~ > 3) BEGIN
        SET paladin_ma_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 3) BEGIN
        SET paladin_ma_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 3) BEGIN
        SET paladin_ma_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 3) BEGIN
        SET paladin_ma_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ < 3) BEGIN
        SET paladin_ma_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ > 2) BEGIN
        SET paladin_ma_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 4) OR (~%level_1_max%~ > 4) BEGIN
        SET paladin_hi_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 4) BEGIN
        SET paladin_hi_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 4) BEGIN
        SET paladin_hi_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 4) BEGIN
        SET paladin_hi_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ < 4) BEGIN
        SET paladin_hi_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ > 3) BEGIN
        SET paladin_hi_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 5) OR (~%level_1_max%~ > 5) BEGIN
        SET paladin_gm_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 5) BEGIN
        SET paladin_gm_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 5) BEGIN
        SET paladin_gm_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 5) BEGIN
        SET paladin_gm_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ < 5) BEGIN
        SET paladin_gm_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ > 4) BEGIN
        SET paladin_gm_min_level = 9
      END
    END
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~cleric~) BEGIN
      PATCH_IF (~%level_1_max%~ = 2) OR (~%level_1_max%~ > 2) BEGIN
        SET cleric_sp_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 2) BEGIN
        SET cleric_sp_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 2) BEGIN
        SET cleric_sp_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 2) BEGIN
         SET cleric_sp_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ < 2) BEGIN
        SET cleric_sp_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ > 1) BEGIN
        SET cleric_sp_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 3) OR (~%level_1_max%~ > 3) BEGIN
        SET cleric_ma_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 3) BEGIN
        SET cleric_ma_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 3) BEGIN
        SET cleric_ma_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 3) BEGIN
        SET cleric_ma_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ < 3) BEGIN
        SET cleric_ma_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ > 2) BEGIN
        SET cleric_ma_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 4) OR (~%level_1_max%~ > 4) BEGIN
        SET cleric_hi_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 4) BEGIN
        SET cleric_hi_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 4) BEGIN
        SET cleric_hi_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 4) BEGIN
        SET cleric_hi_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ < 4) BEGIN
        SET cleric_hi_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ > 3) BEGIN
        SET cleric_hi_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 5) OR (~%level_1_max%~ > 5) BEGIN
        SET cleric_gm_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 5) BEGIN
        SET cleric_gm_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 5) BEGIN
        SET cleric_gm_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 5) BEGIN
        SET cleric_gm_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ < 5) BEGIN
        SET cleric_gm_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ > 4) BEGIN
        SET cleric_gm_min_level = 9
      END
    END
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~druid~) BEGIN
      PATCH_IF (~%level_1_max%~ = 2) OR (~%level_1_max%~ > 2) BEGIN
        SET druid_sp_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 2) BEGIN
        SET druid_sp_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 2) BEGIN
        SET druid_sp_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 2) BEGIN
         SET druid_sp_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ < 2) BEGIN
        SET druid_sp_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ > 1) BEGIN
        SET fighter_sp_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 3) OR (~%level_1_max%~ > 3) BEGIN
        SET fighter_sp_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 3) BEGIN
        SET druid_ma_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 3) BEGIN
        SET druid_ma_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 3) BEGIN
        SET druid_ma_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ < 3) BEGIN
        SET druid_ma_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ > 2) BEGIN
        SET druid_ma_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 4) OR (~%level_1_max%~ > 4) BEGIN
        SET druid_hi_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 4) BEGIN
        SET druid_hi_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 4) BEGIN
        SET druid_hi_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 4) BEGIN
        SET druid_hi_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ < 4) BEGIN
        SET druid_hi_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ > 3) BEGIN
        SET druid_hi_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 5) OR (~%level_1_max%~ > 5) BEGIN
        SET druid_gm_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 5) BEGIN
        SET druid_gm_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 5) BEGIN
        SET druid_gm_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 5) BEGIN
        SET druid_gm_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ < 5) BEGIN
        SET druid_gm_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ > 4) BEGIN
        SET druid_gm_min_level = 9
      END
    END
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~shaman~) BEGIN
      PATCH_IF (~%level_1_max%~ = 2) OR (~%level_1_max%~ > 2) BEGIN
        SET shaman_sp_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 2) BEGIN
        SET shaman_sp_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 2) BEGIN
        SET shaman_sp_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 2) BEGIN
         SET shaman_sp_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ < 2) BEGIN
        SET shaman_sp_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ > 1) BEGIN
        SET shaman_sp_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 3) OR (~%level_1_max%~ > 3) BEGIN
        SET shaman_ma_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 3) BEGIN
        SET shaman_ma_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 3) BEGIN
        SET shaman_ma_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 3) BEGIN
        SET shaman_ma_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ < 3) BEGIN
        SET shaman_ma_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ > 2) BEGIN
        SET shaman_ma_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 4) OR (~%level_1_max%~ > 4) BEGIN
        SET shaman_hi_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 4) BEGIN
        SET shaman_hi_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 4) BEGIN
        SET shaman_hi_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 4) BEGIN
        SET shaman_hi_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ < 4) BEGIN
        SET shaman_hi_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ > 3) BEGIN
        SET shaman_hi_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 5) OR (~%level_1_max%~ > 5) BEGIN
        SET shaman_gm_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 5) BEGIN
        SET shaman_gm_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 5) BEGIN
        SET shaman_gm_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 5) BEGIN
        SET shaman_gm_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ < 5) BEGIN
        SET shaman_gm_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ > 4) BEGIN
        SET shaman_gm_min_level = 9
      END
    END
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~thief~) BEGIN
      PATCH_IF (~%level_1_max%~ = 2) OR (~%level_1_max%~ > 2) BEGIN
        SET thief_sp_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 2) BEGIN
        SET thief_sp_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 2) BEGIN
        SET thief_sp_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 2) BEGIN
         SET thief_sp_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ < 2) BEGIN
        SET thief_sp_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ > 1) BEGIN
        SET thief_sp_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 3) OR (~%level_1_max%~ > 3) BEGIN
        SET thief_ma_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 3) BEGIN
        SET thief_ma_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 3) BEGIN
        SET thief_ma_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 3) BEGIN
        SET thief_ma_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ < 3) BEGIN
        SET thief_ma_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ > 2) BEGIN
        SET thief_ma_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 4) OR (~%level_1_max%~ > 4) BEGIN
        SET thief_hi_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 4) BEGIN
        SET thief_hi_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 4) BEGIN
        SET thief_hi_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 4) BEGIN
        SET thief_hi_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ < 4) BEGIN
        SET thief_hi_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ > 3) BEGIN
        SET thief_hi_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 5) OR (~%level_1_max%~ > 5) BEGIN
        SET thief_gm_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 5) BEGIN
        SET thief_gm_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 5) BEGIN
        SET thief_gm_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 5) BEGIN
        SET thief_gm_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ < 5) BEGIN
        SET thief_gm_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ > 4) BEGIN
        SET thief_gm_min_level = 9
      END
    END
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~bard~) BEGIN
      PATCH_IF (~%level_1_max%~ = 2) OR (~%level_1_max%~ > 2) BEGIN
        SET bard_sp_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 2) BEGIN
        SET bard_sp_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 2) BEGIN
        SET bard_sp_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 2) BEGIN
         SET bard_sp_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ < 2) BEGIN
        SET bard_sp_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ > 1) BEGIN
        SET bard_sp_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 3) OR (~%level_1_max%~ > 3) BEGIN
        SET bard_ma_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 3) BEGIN
        SET bard_ma_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 3) BEGIN
        SET bard_ma_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 3) BEGIN
        SET bard_ma_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ < 3) BEGIN
        SET bard_ma_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ > 2) BEGIN
        SET bard_ma_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 4) OR (~%level_1_max%~ > 4) BEGIN
        SET bard_hi_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 4) BEGIN
        SET bard_hi_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 4) BEGIN
        SET bard_hi_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 4) BEGIN
        SET bard_hi_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ < 4) BEGIN
        SET bard_hi_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ > 3) BEGIN
        SET bard_hi_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 5) OR (~%level_1_max%~ > 5) BEGIN
        SET bard_gm_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 5) BEGIN
        SET bard_gm_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 5) BEGIN
        SET bard_gm_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 5) BEGIN
        SET bard_gm_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ < 5) BEGIN
        SET bard_gm_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ > 4) BEGIN
        SET bard_gm_min_level = 9
      END
    END
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~mage~) BEGIN
      PATCH_IF (~%level_1_max%~ = 2) OR (~%level_1_max%~ > 2) BEGIN
        SET mage_sp_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 2) BEGIN
        SET mage_sp_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 2) BEGIN
        SET mage_sp_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 2) BEGIN
         SET mage_sp_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ < 2) BEGIN
        SET mage_sp_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ > 1) BEGIN
        SET mage_sp_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 3) OR (~%level_1_max%~ > 3) BEGIN
        SET mage_ma_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 3) BEGIN
        SET mage_ma_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 3) BEGIN
        SET mage_ma_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 3) BEGIN
        SET mage_ma_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ < 3) BEGIN
        SET mage_ma_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ > 2) BEGIN
        SET fighter_ma_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 4) OR (~%level_1_max%~ > 4) BEGIN
        SET mage_hi_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 4) BEGIN
        SET mage_hi_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 4) BEGIN
        SET mage_hi_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 4) BEGIN
        SET mage_hi_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ < 4) BEGIN
        SET mage_hi_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ > 3) BEGIN
        SET mage_hi_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 5) OR (~%level_1_max%~ > 5) BEGIN
        SET fighter_hi_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 5) BEGIN
        SET mage_gm_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 5) BEGIN
        SET mage_gm_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 5) BEGIN
        SET mage_gm_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ < 5) BEGIN
        SET mage_gm_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ > 4) BEGIN
        SET mage_gm_min_level = 9
      END
    END
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~sorcerer~) BEGIN
      PATCH_IF (~%level_1_max%~ = 2) OR (~%level_1_max%~ > 2) BEGIN
        SET sorcerer_sp_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 2) BEGIN
        SET sorcerer_sp_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 2) BEGIN
        SET sorcerer_sp_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 2) BEGIN
         SET sorcerer_sp_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ < 2) BEGIN
        SET sorcerer_sp_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ > 1) BEGIN
        SET sorcerer_sp_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 3) OR (~%level_1_max%~ > 3) BEGIN
        SET sorcerer_ma_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 3) BEGIN
        SET sorcerer_ma_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 3) BEGIN
        SET sorcerer_ma_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 3) BEGIN
        SET sorcerer_ma_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ < 3) BEGIN
        SET sorcerer_ma_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ > 2) BEGIN
        SET sorcerer_ma_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 4) OR (~%level_1_max%~ > 4) BEGIN
        SET sorcerer_hi_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 4) BEGIN
        SET sorcerer_hi_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 4) BEGIN
        SET sorcerer_hi_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 4) BEGIN
        SET sorcerer_hi_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ < 4) BEGIN
        SET sorcerer_hi_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ > 3) BEGIN
        SET fighter_hi_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 5) OR (~%level_1_max%~ > 5) BEGIN
        SET sorcerer_hi_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 5) BEGIN
        SET sorcerer_gm_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 5) BEGIN
        SET sorcerer_gm_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 5) BEGIN
        SET sorcerer_gm_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ < 5) BEGIN
        SET sorcerer_gm_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ > 4) BEGIN
        SET sorcerer_gm_min_level = 9
      END
    END
    PATCH_IF (~%prof_class%~ STRING_EQUAL_CASE ~monk~) BEGIN
      PATCH_IF (~%level_1_max%~ = 2) OR (~%level_1_max%~ > 2) BEGIN
        SET monk_sp_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 2) BEGIN
        SET monk_sp_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 2) BEGIN
        SET monk_sp_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 2) BEGIN
         SET monk_sp_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ < 2) BEGIN
        SET monk_sp_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 2) AND !(~%level_6_max%~ = 2) AND !(~%level_9_max%~ = 2) AND (~%overall_max%~ > 1) BEGIN
        SET monk_sp_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 3) OR (~%level_1_max%~ > 3) BEGIN
        SET monk_ma_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 3) BEGIN
        SET monk_ma_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 3) BEGIN
        SET monk_ma_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 3) BEGIN
        SET monk_ma_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ < 3) BEGIN
        SET monk_ma_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 3) AND !(~%level_6_max%~ = 3) AND !(~%level_9_max%~ = 3) AND (~%overall_max%~ > 2) BEGIN
        SET monk_ma_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 4) OR (~%level_1_max%~ > 4) BEGIN
        SET monk_hi_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 4) BEGIN
        SET monk_hi_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 4) BEGIN
        SET monk_hi_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 4) BEGIN
        SET monk_hi_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ < 4) BEGIN
        SET monk_hi_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 4) AND !(~%level_6_max%~ = 4) AND !(~%level_9_max%~ = 4) AND (~%overall_max%~ > 3) BEGIN
        SET monk_hi_min_level = 9
      END
      PATCH_IF (~%level_1_max%~ = 5) OR (~%level_1_max%~ > 5) BEGIN
        SET monk_gm_min_level = 0
      END
      PATCH_IF (~%level_3_max%~ = 5) BEGIN
        SET monk_gm_min_level = 1
      END
      PATCH_IF (~%level_6_max%~ = 5) BEGIN
        SET monk_gm_min_level = 4
      END
      PATCH_IF (~%level_9_max%~ = 5) BEGIN
        SET monk_gm_min_level = 8
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ < 5) BEGIN
        SET monk_gm_min_level = 50
      END
      PATCH_IF !(~%level_3_max%~ = 5) AND !(~%level_6_max%~ = 5) AND !(~%level_9_max%~ = 5) AND (~%overall_max%~ > 4) BEGIN
        SET monk_gm_min_level = 9
      END
    END
  END
BUT_ONLY

OUTER_SET no_set = RESOLVE_STR_REF (~no stat~)

DEFINE_PATCH_MACRO prof_name_replacements BEGIN
	REPLACE_TEXTUALLY ~name_89~ ~%name_89%~
	REPLACE_TEXTUALLY ~desc_89~ ~%desc_89%~
	REPLACE_TEXTUALLY ~name_90~ ~%name_90%~
	REPLACE_TEXTUALLY ~desc_90~ ~%desc_90%~
	REPLACE_TEXTUALLY ~name_91~ ~%name_91%~
	REPLACE_TEXTUALLY ~desc_91~ ~%desc_91%~
	REPLACE_TEXTUALLY ~name_92~ ~%name_92%~
	REPLACE_TEXTUALLY ~desc_92~ ~%desc_92%~
	REPLACE_TEXTUALLY ~name_93~ ~%name_93%~
	REPLACE_TEXTUALLY ~desc_93~ ~%desc_93%~
	REPLACE_TEXTUALLY ~name_94~ ~%name_94%~
	REPLACE_TEXTUALLY ~desc_94~ ~%desc_94%~
	REPLACE_TEXTUALLY ~name_95~ ~%name_95%~
	REPLACE_TEXTUALLY ~desc_95~ ~%desc_95%~
	REPLACE_TEXTUALLY ~name_96~ ~%name_96%~
	REPLACE_TEXTUALLY ~desc_96~ ~%desc_96%~
	REPLACE_TEXTUALLY ~name_97~ ~%name_97%~
	REPLACE_TEXTUALLY ~desc_97~ ~%desc_97%~
	REPLACE_TEXTUALLY ~name_98~ ~%name_98%~
	REPLACE_TEXTUALLY ~desc_98~ ~%desc_98%~
	REPLACE_TEXTUALLY ~name_99~ ~%name_99%~
	REPLACE_TEXTUALLY ~desc_99~ ~%desc_99%~
	REPLACE_TEXTUALLY ~name_100~ ~%name_100%~
	REPLACE_TEXTUALLY ~desc_100~ ~%desc_100%~
	REPLACE_TEXTUALLY ~name_101~ ~%name_101%~
	REPLACE_TEXTUALLY ~desc_101~ ~%desc_101%~
	REPLACE_TEXTUALLY ~name_102~ ~%name_102%~
	REPLACE_TEXTUALLY ~desc_102~ ~%desc_102%~
	REPLACE_TEXTUALLY ~name_103~ ~%name_103%~
	REPLACE_TEXTUALLY ~desc_103~ ~%desc_103%~
	REPLACE_TEXTUALLY ~name_104~ ~%name_104%~
	REPLACE_TEXTUALLY ~desc_104~ ~%desc_104%~
	REPLACE_TEXTUALLY ~name_105~ ~%name_105%~
	REPLACE_TEXTUALLY ~desc_105~ ~%desc_105%~
	REPLACE_TEXTUALLY ~name_106~ ~%name_106%~
	REPLACE_TEXTUALLY ~desc_106~ ~%desc_106%~
	REPLACE_TEXTUALLY ~name_107~ ~%name_107%~
	REPLACE_TEXTUALLY ~desc_107~ ~%desc_107%~
	REPLACE_TEXTUALLY ~name_108~ ~%name_108%~
	REPLACE_TEXTUALLY ~desc_108~ ~%desc_108%~
	REPLACE_TEXTUALLY ~name_109~ ~%name_109%~
	REPLACE_TEXTUALLY ~desc_109~ ~%desc_109%~
	REPLACE_TEXTUALLY ~name_110~ ~%name_110%~
	REPLACE_TEXTUALLY ~desc_110~ ~%desc_110%~
	REPLACE_TEXTUALLY ~name_111~ ~%name_111%~
	REPLACE_TEXTUALLY ~desc_111~ ~%desc_111%~
	REPLACE_TEXTUALLY ~name_112~ ~%name_112%~
	REPLACE_TEXTUALLY ~desc_112~ ~%desc_112%~
	REPLACE_TEXTUALLY ~name_113~ ~%name_113%~
	REPLACE_TEXTUALLY ~desc_113~ ~%desc_113%~
	REPLACE_TEXTUALLY ~name_114~ ~%name_114%~
	REPLACE_TEXTUALLY ~desc_114~ ~%desc_114%~
	REPLACE_TEXTUALLY ~name_115~ ~%name_115%~
	REPLACE_TEXTUALLY ~desc_115~ ~%desc_115%~
	REPLACE_TEXTUALLY ~name_124~ ~%name_124%~
	REPLACE_TEXTUALLY ~desc_124~ ~%desc_124%~
	REPLACE_TEXTUALLY ~name_127~ ~%name_127%~
	REPLACE_TEXTUALLY ~desc_127~ ~%desc_127%~
	REPLACE_TEXTUALLY ~name_134~ ~%name_134%~
	REPLACE_TEXTUALLY ~desc_134~ ~%desc_134%~
	REPLACE_TEXTUALLY ~4294967296~ ~%no_set%~
END

/* this doesn't work...
ACTION_FOR_EACH class IN ~fighter~ ~ranger~ ~paladin~ ~cleric~ ~druid~ ~shaman~ ~thief~ ~bard~ ~mage~ ~sorcerer~ ~monk~ BEGIN
  SNPRINT 2 shortclass ~%class%~
  COPY ~%MOD_FOLDER%/lib/dialprof/profx.d~ ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%%shortclass%.d~
	REPLACE_TEXTUALLY ~%class%_sp_min_level%~ ~%"class"_sp_min_level%~
	REPLACE_TEXTUALLY ~%class%_ma_min_level%~ ~%"class"_ma_min_level%~
	REPLACE_TEXTUALLY ~%class%_hi_min_level%~ ~%"class"_hi_min_level%~
	REPLACE_TEXTUALLY ~%class%_gm_min_level%~ ~%"class"_gm_min_level%~
    LPM prof_name_replacements
*/

COPY ~%MOD_FOLDER%/lib/dialprof/d5profx.d~ ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%fi.d~
	REPLACE_TEXTUALLY ~d5profx~ ~%prof_script_name%fi~
	REPLACE_TEXTUALLY ~D5PROFX~ ~%prof_script_name%FI~
	REPLACE_TEXTUALLY ~sp_min_level~ ~%fighter_sp_min_level%~
	REPLACE_TEXTUALLY ~ma_min_level~ ~%fighter_ma_min_level%~
	REPLACE_TEXTUALLY ~hi_min_level~ ~%fighter_hi_min_level%~
	REPLACE_TEXTUALLY ~gm_min_level~ ~%fighter_gm_min_level%~
    LPM prof_name_replacements

COPY ~%MOD_FOLDER%/lib/dialprof/d5profx.d~ ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%ra.d~
	REPLACE_TEXTUALLY ~d5profx~ ~%prof_script_name%ra~
	REPLACE_TEXTUALLY ~D5PROFX~ ~%prof_script_name%RA~
	REPLACE_TEXTUALLY ~sp_min_level~ ~%ranger_sp_min_level%~
	REPLACE_TEXTUALLY ~ma_min_level~ ~%ranger_ma_min_level%~
	REPLACE_TEXTUALLY ~hi_min_level~ ~%ranger_hi_min_level%~
	REPLACE_TEXTUALLY ~gm_min_level~ ~%ranger_gm_min_level%~
    LPM prof_name_replacements
	
COPY ~%MOD_FOLDER%/lib/dialprof/d5profx.d~ ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%pa.d~
	REPLACE_TEXTUALLY ~d5profx~ ~%prof_script_name%pa~
	REPLACE_TEXTUALLY ~D5PROFX~ ~%prof_script_name%PA~
	REPLACE_TEXTUALLY ~sp_min_level~ ~%paladin_sp_min_level%~
	REPLACE_TEXTUALLY ~ma_min_level~ ~%paladin_ma_min_level%~
	REPLACE_TEXTUALLY ~hi_min_level~ ~%paladin_hi_min_level%~
	REPLACE_TEXTUALLY ~gm_min_level~ ~%paladin_gm_min_level%~
    LPM prof_name_replacements
	
COPY ~%MOD_FOLDER%/lib/dialprof/d5profx.d~ ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%cl.d~
	REPLACE_TEXTUALLY ~d5profx~ ~%prof_script_name%cl~
	REPLACE_TEXTUALLY ~D5PROFX~ ~%prof_script_name%CL~
	REPLACE_TEXTUALLY ~sp_min_level~ ~%cleric_sp_min_level%~
	REPLACE_TEXTUALLY ~ma_min_level~ ~%cleric_ma_min_level%~
	REPLACE_TEXTUALLY ~hi_min_level~ ~%cleric_hi_min_level%~
	REPLACE_TEXTUALLY ~gm_min_level~ ~%cleric_gm_min_level%~
    LPM prof_name_replacements
	
COPY ~%MOD_FOLDER%/lib/dialprof/d5profx.d~ ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%dr.d~
	REPLACE_TEXTUALLY ~d5profx~ ~%prof_script_name%dr~
	REPLACE_TEXTUALLY ~D5PROFX~ ~%prof_script_name%DR~
	REPLACE_TEXTUALLY ~sp_min_level~ ~%druid_sp_min_level%~
	REPLACE_TEXTUALLY ~ma_min_level~ ~%druid_ma_min_level%~
	REPLACE_TEXTUALLY ~hi_min_level~ ~%druid_hi_min_level%~
	REPLACE_TEXTUALLY ~gm_min_level~ ~%druid_gm_min_level%~
    LPM prof_name_replacements
	
COPY ~%MOD_FOLDER%/lib/dialprof/d5profx.d~ ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%sh.d~
	REPLACE_TEXTUALLY ~d5profx~ ~%prof_script_name%sh~
	REPLACE_TEXTUALLY ~D5PROFX~ ~%prof_script_name%SH~
	REPLACE_TEXTUALLY ~sp_min_level~ ~%shaman_sp_min_level%~
	REPLACE_TEXTUALLY ~ma_min_level~ ~%shaman_ma_min_level%~
	REPLACE_TEXTUALLY ~hi_min_level~ ~%shaman_hi_min_level%~
	REPLACE_TEXTUALLY ~gm_min_level~ ~%shaman_gm_min_level%~
    LPM prof_name_replacements
	
COPY ~%MOD_FOLDER%/lib/dialprof/d5profx.d~ ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%th.d~
	REPLACE_TEXTUALLY ~d5profx~ ~%prof_script_name%th~
	REPLACE_TEXTUALLY ~D5PROFX~ ~%prof_script_name%TH~
	REPLACE_TEXTUALLY ~sp_min_level~ ~%thief_sp_min_level%~
	REPLACE_TEXTUALLY ~ma_min_level~ ~%thief_ma_min_level%~
	REPLACE_TEXTUALLY ~hi_min_level~ ~%thief_hi_min_level%~
	REPLACE_TEXTUALLY ~gm_min_level~ ~%thief_gm_min_level%~
    LPM prof_name_replacements
	
COPY ~%MOD_FOLDER%/lib/dialprof/d5profx.d~ ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%ba.d~
	REPLACE_TEXTUALLY ~d5profx~ ~%prof_script_name%ba~
	REPLACE_TEXTUALLY ~D5PROFX~ ~%prof_script_name%BA~
	REPLACE_TEXTUALLY ~sp_min_level~ ~%bard_sp_min_level%~
	REPLACE_TEXTUALLY ~ma_min_level~ ~%bard_ma_min_level%~
	REPLACE_TEXTUALLY ~hi_min_level~ ~%bard_hi_min_level%~
	REPLACE_TEXTUALLY ~gm_min_level~ ~%bard_gm_min_level%~
    LPM prof_name_replacements
	
COPY ~%MOD_FOLDER%/lib/dialprof/d5profx.d~ ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%ma.d~
	REPLACE_TEXTUALLY ~d5profx~ ~%prof_script_name%ma~
	REPLACE_TEXTUALLY ~D5PROFX~ ~%prof_script_name%MA~
	REPLACE_TEXTUALLY ~sp_min_level~ ~%mage_sp_min_level%~
	REPLACE_TEXTUALLY ~ma_min_level~ ~%mage_ma_min_level%~
	REPLACE_TEXTUALLY ~hi_min_level~ ~%mage_hi_min_level%~
	REPLACE_TEXTUALLY ~gm_min_level~ ~%mage_gm_min_level%~
    LPM prof_name_replacements
	
COPY ~%MOD_FOLDER%/lib/dialprof/d5profx.d~ ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%so.d~
	REPLACE_TEXTUALLY ~d5profx~ ~%prof_script_name%so~
	REPLACE_TEXTUALLY ~D5PROFX~ ~%prof_script_name%SO~
	REPLACE_TEXTUALLY ~sp_min_level~ ~%sorcerer_sp_min_level%~
	REPLACE_TEXTUALLY ~ma_min_level~ ~%sorcerer_ma_min_level%~
	REPLACE_TEXTUALLY ~hi_min_level~ ~%sorcerer_hi_min_level%~
	REPLACE_TEXTUALLY ~gm_min_level~ ~%sorcerer_gm_min_level%~
    LPM prof_name_replacements
	
COPY ~%MOD_FOLDER%/lib/dialprof/d5profx.d~ ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%mo.d~
	REPLACE_TEXTUALLY ~d5profx~ ~%prof_script_name%mo~
	REPLACE_TEXTUALLY ~D5PROFX~ ~%prof_script_name%MO~
	REPLACE_TEXTUALLY ~sp_min_level~ ~%monk_sp_min_level%~
	REPLACE_TEXTUALLY ~ma_min_level~ ~%monk_ma_min_level%~
	REPLACE_TEXTUALLY ~hi_min_level~ ~%monk_hi_min_level%~
	REPLACE_TEXTUALLY ~gm_min_level~ ~%monk_gm_min_level%~
    LPM prof_name_replacements
	

COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P89.spl~
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/D51P90.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 90 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/D51P91.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 91 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P92.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 92 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P93.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 93 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P94.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 94 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P95.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 95 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P96.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 96 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P97.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 97 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P98.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 98 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P99.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 99 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P100.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 100 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P101.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 101 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P102.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 102 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P103.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 103 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P104.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 104 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P105.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 105 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P106.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 106 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P107.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 107 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P108.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 108 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P109.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 109 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P110.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 110 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P111.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 111 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P112.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 112 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P113.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 113 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P114.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 114 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P115.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 115 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P124.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 124 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P127.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 127 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d51P134.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter2 = 134 END

COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P89.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/D52P90.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 90 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/D52P91.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 91 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P92.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 92 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P93.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 93 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P94.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 94 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P95.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 95 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P96.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 96 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P97.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 97 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P98.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 98 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P99.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 99 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P100.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 100 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P101.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 101 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P102.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 102 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P103.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 103 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P104.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 104 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P105.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 105 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P106.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 106 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P107.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 107 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P108.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 108 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P109.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 109 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P110.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 110 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P111.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 111 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P112.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 112 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P113.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 113 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P114.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 114 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P115.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 115 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P124.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 124 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P127.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 127 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d52P134.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 2 parameter2 = 134 END

COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P89.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P90.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 90 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/D53P91.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 91 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P92.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 92 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P93.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 93 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P94.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 94 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P95.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 95 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P96.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 96 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P97.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 97 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P98.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 98 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P99.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 99 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P100.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 100 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P101.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 101 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P102.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 102 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P103.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 103 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P104.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 104 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P105.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 105 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P106.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 106 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P107.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 107 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P108.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 108 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P109.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 109 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P110.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 110 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P111.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 111 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P112.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 112 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P113.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 113 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P114.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 114 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P115.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 115 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P124.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 124 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P127.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 127 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d53P134.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 3 parameter2 = 134 END

COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P89.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P90.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 90 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/D54P91.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 91 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P92.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 92 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P93.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 93 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P94.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 94 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P95.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 95 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P96.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 96 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P97.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 97 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P98.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 98 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P99.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 99 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P100.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 100 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P101.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 101 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P102.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 102 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P103.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 103 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P104.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 104 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P105.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 105 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P106.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 106 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P107.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 107 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P108.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 108 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P109.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 109 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P110.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 110 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P111.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 111 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P112.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 112 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P113.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 113 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P114.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 114 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P115.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 115 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P124.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 124 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P127.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 127 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d54P134.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 4 parameter2 = 134 END

COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P89.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P90.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 90 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P91.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 91 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P92.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 92 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P93.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 93 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P94.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 94 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P95.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 95 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P96.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 96 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P97.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 97 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P98.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 98 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P99.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 99 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P100.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 100 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P101.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 101 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P102.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 102 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P103.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 103 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P104.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 104 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P105.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 105 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P106.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 106 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P107.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 107 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P108.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 108 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P109.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 109 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P110.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 110 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P111.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 111 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P112.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 112 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P113.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 113 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P114.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 114 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P115.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 115 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P124.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 124 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P127.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 127 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d55P134.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 5 parameter2 = 134 END

COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P89.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P90.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 90 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P91.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 91 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P92.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 92 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P93.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 93 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P94.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 94 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P95.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 95 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P96.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 96 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P97.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 97 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P98.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 98 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P99.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 99 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P100.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 100 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P101.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 101 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P102.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 102 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P103.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 103 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P104.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 104 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P105.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 105 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P106.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 106 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P107.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 107 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P108.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 108 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P109.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 109 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P110.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 110 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P111.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 111 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P112.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 112 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P113.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 113 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P114.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 114 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P115.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 115 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P124.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 124 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P127.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 127 END
COPY ~%MOD_FOLDER%/lib/dialprof/d5_1prf.spl~ ~override/d56P134.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = 6 parameter2 = 134 END

COPY ~%MOD_FOLDER%/lib/dialprof/d5_prof.bam~ ~override~
COPY ~%MOD_FOLDER%/lib/dialprof/d5_cprf.eff~ ~override/%prof_script_name%.eff~
  WRITE_EVALUATED_ASCII 0x30 ~%prof_script_name%~ #8
COPY ~%MOD_FOLDER%/lib/dialprof/d5_cprf.cre~ ~override/%prof_script_name%.cre~
  WRITE_EVALUATED_ASCII 0x248 ~%prof_script_name%~ #8

COPY ~%MOD_FOLDER%/lib/dialprof/d5_base.spl~ ~override/%prof_script_name%1.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR target = 1 opcode = 171 timing = 1 STR_VAR resource = EVAL ~%prof_script_name%a~ END

COPY ~%MOD_FOLDER%/lib/dialprof/d5_base.spl~ ~override/%prof_script_name%a.spl~
  SAY NAME1 @2091
  SAY UNIDENTIFIED_DESC @2091
  WRITE_ASCII 0x3a ~d5_prof~ #8
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~d5_prof~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 1 duration = 30 STR_VAR resource = EVAL ~%prof_script_name%~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 1 STR_VAR resource = EVAL ~%prof_script_name%a~ END

COMPILE ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%.baf~
ACTION_IF (fighter_dlg = 1) BEGIN
  COMPILE ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%fi.d~
END
ACTION_IF (ranger_dlg = 1) BEGIN
  COMPILE ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%ra.d~
END
ACTION_IF (paladin_dlg = 1) BEGIN
  COMPILE ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%pa.d~
END
ACTION_IF (cleric_dlg = 1) BEGIN
  COMPILE ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%cl.d~
END
ACTION_IF (druid_dlg = 1) BEGIN
  COMPILE ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%dr.d~
END
ACTION_IF (shaman_dlg = 1) BEGIN
  COMPILE ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%sh.d~
END
ACTION_IF (thief_dlg = 1) BEGIN
  COMPILE ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%th.d~
END
ACTION_IF (bard_dlg = 1) BEGIN
  COMPILE ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%ba.d~
END
ACTION_IF (mage_dlg = 1) BEGIN
  COMPILE ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%ma.d~
END
ACTION_IF (sorcerer_dlg = 1) BEGIN
  COMPILE ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%so.d~
END
ACTION_IF (monk_dlg = 1) BEGIN
  COMPILE ~weidu_external/%MOD_FOLDER%/compile/%prof_script_name%mo.d~
END

OUTER_SPRINT prof_script_name ~______~
OUTER_SET script_level_one = 0
OUTER_SET script_higher_levels = 0
OUTER_SPRINT class_dlgs ~all~

END	//	end with_tra

END	//	end define macro

//
