
// v11.4

/*

functions in this file:

- sorcerer_spell_learning - line 
    creates spell & item to learn any sorcerer-valid spell via kjeron's spell-learning UI
    NB: this is in use and also works for alternate, coexisting versions

- semi_sorcerer_casting - line 
    applies sorcerer casting mechanics to all spells in sorcerer_spell_learning
    NB: variables must match those used in sorcerer_spell_learning

- add_sorcerer_spells - line 
    input an array, any spells in the array get added to the sorcerer spell-learning
    NB: variables must match those used in sorcerer_spell_learning
    NB: even if sorcerer casting is already initialized, must "LAF semi_sorcerer_casting" again

*/


INCLUDE ~%MOD_FOLDER%/lib/semi_spont/semi_misc_functions.tpa~


//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION sorcerer_spell_learning STR_VAR menu_suffix = ~W~ 	spl_list = ~d5xsorc~ itm_name = ~d5xsorc~ itm_ga_spl = ~d5xsor1~ spl_ap_spl = ~d5xsor2~ spl_tbl = ~SPLSRCKN~ BEGIN


//find game install language__________________________________________________________
//
LAF set_lang RET game_lang END

WITH_TRA ~%MOD_FOLDER%/lib/semi_spont/%game_lang%/semi_spont.tra~ BEGIN

 ACTION_IF !(FILE_EXISTS_IN_GAME ~%spl_list%.2da~) BEGIN

<<<<<<<<  d5/d5xsorc.2da
2DA V1.0
****
            	     ResRef   Type>>>>>>>>

   COPY ~d5/d5xsorc.2da~ ~override/%spl_list%.2da~
   
 END	//	end spell list doesn't exist

  OUTER_SPRINT $exclude_spls(~spwi000~)~0~

 ACTION_IF !(FILE_EXISTS_IN_GAME ~%itm_name%.spl~) BEGIN

  COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
    PATCH_IF (%SOURCE_SIZE% > 0x71) BEGIN
      READ_SHORT 0x1c spell_type 
      READ_BYTE 0x25 spell_school
      READ_LONG 0x34 spell_level
      PATCH_IF (~%SOURCE_RES%~ STRING_MATCHES_REGEXP ~^[Ss][Pp][Ww][Ii][1-9][0-4][0-9]$~ = 0) OR (~%SOURCE_RES%~ STRING_MATCHES_REGEXP ~^[Ss][Pp][Ww][Ii][1-9]50$~ = 0) BEGIN 
        PATCH_IF (spell_type = 1) AND !(spell_school = 10) AND !(~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI908~) AND !(~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI124~) BEGIN
	      PATCH_IF !(FILE_CONTAINS_EVALUATED (~hidespl.2da~ ~%SOURCE_RES%~)) BEGIN
            SPRINT $sorcerer_spells(~%SOURCE_RES%~) ~1~
          END
        END
      END
    END
  BUT_ONLY
  
  ACTION_PHP_EACH sorcerer_spells AS sorc_spell => ind BEGIN
    ACTION_PHP_EACH exclude_spls AS nogo => ind BEGIN
      ACTION_IF !(~%sorc_spell%~ STRING_EQUAL_CASE ~%nogo%~) BEGIN
	    APPEND ~%spl_list%.2da~ ~sorcerer	%sorc_spell%	3~ UNLESS ~sorcerer	%sorc_spell%~
	  END
    END
  END

  ACTION_FOR_EACH num IN ~1~ ~2~ ~3~ ~4~ ~5~ ~6~ ~7~ ~8~ ~9~ BEGIN
    ACTION_IF (FILE_EXISTS_IN_GAME ~mewi%num%.txt~) BEGIN
      COPY_EXISTING ~mewi%num%.txt~ ~override~
        COUNT_2DA_ROWS 1 rows
        FOR (row = 0; row < rows; ++row) BEGIN
          READ_2DA_ENTRY row 0 1 me_spl
          PATCH_IF (FILE_EXISTS_IN_GAME ~%me_spl%.spl~) BEGIN
            PATCH_IF !(FILE_CONTAINS_EVALUATED (~%spl_list%.2da~ ~%me_spl%~)) BEGIN
              INNER_ACTION BEGIN
                APPEND ~%spl_list%.2da~ ~sorcerer 	%me_spl%	3~ UNLESS ~sorcerer 	%me_spl%~
              END             
            END
          END
        END
    END
  END

 END	//	end learning spell doesn't exist
  
 COPY_EXISTING ~%spl_list%.2da~ ~override~
    COUNT_2DA_COLS cols
    READ_2DA_ENTRIES_NOW ~r2en_xsorc~ cols
    FOR (row = 0; row < r2en_xsorc; ++row) BEGIN
      READ_2DA_ENTRY_FORMER ~r2en_xsorc~ row 1 mem_spell
      INNER_ACTION BEGIN
	    ACTION_IF (FILE_EXISTS_IN_GAME ~%mem_spell%.spl~) BEGIN
		  ACTION_IF !(FILE_EXISTS_IN_GAME ~%mem_spell%%menu_suffix%.spl~) BEGIN
            COPY_EXISTING ~%mem_spell%.spl~ ~override~
		      READ_STRREF NAME1 spell_name
		      READ_STRREF UNIDENTIFIED_DESC spell_description
		      READ_LONG 0x34 spell_level
		      READ_ASCII 0x3a spell_icon
		    BUT_ONLY
		    COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/%mem_spell%%menu_suffix%.spl~
              SAY NAME1 ~%spell_name%~
              SAY UNIDENTIFIED_DESC ~%spell_description%~
			  WRITE_EVALUATED_ASCII 0x3a ~%spell_icon%~ #8
			  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL ~%spell_icon%~ END
		  	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%mem_spell%~ END
		  END
		END
	  END
	END
 BUT_ONLY
 
  ACTION_IF !(FILE_EXISTS_IN_GAME ~%spl_clon_list%.2da~) BEGIN
<<<<<<<< d5/d5xclons.2da
2DA V1.0 
IND
		MEM 		CAST 		TYPE	PROCESSED
100		#			itm_name		spl_list	spl_tbl
>>>>>>>> 
   COPY ~d5/d5xclons.2da~ ~override/%spl_clon_list%.2da~ 
     REPLACE_TEXTUALLY ~itm_name~ ~%itm_name%~
     REPLACE_TEXTUALLY ~spl_list~ ~%spl_list%~
     REPLACE_TEXTUALLY ~spl_tbl~ ~%spl_tbl%~
  END

  OUTER_SET high_ind = 99
  COPY_EXISTING ~%spl_clon_list%.2da~ ~override~
    COUNT_2DA_COLS cols
    READ_2DA_ENTRIES_NOW ~r2en_xclons~ cols
    FOR (row = 0; row < r2en_xclons; ++row) BEGIN
      READ_2DA_ENTRY_FORMER ~r2en_xclons~ row 0 this_ind
      PATCH_IF (this_ind > high_ind) BEGIN
        SET high_ind = this_ind
      END
    END
  BUT_ONLY

  COPY_EXISTING ~%spl_list%.2da~ ~override~
    COUNT_2DA_COLS cols
    READ_2DA_ENTRIES_NOW ~r2en_xsorc~ cols
    FOR (row = 0; row < r2en_xsorc; ++row) BEGIN
      READ_2DA_ENTRY_FORMER ~r2en_xsorc~ row 1 this_spell
      PATCH_IF (FILE_EXISTS_IN_GAME ~%this_spell%.spl~) BEGIN
        SPRINT $sorcerer_valid_spells(~%this_spell%~) ~1~
      END
    END
  BUT_ONLY

  COPY_EXISTING ~%spl_clon_list%.2da~ ~override~
    COUNT_2DA_COLS cols
    COUNT_2DA_ROWS cols rows
    READ_2DA_ENTRY (rows - 1) 0 cols last_ind
  BUT_ONLY

  ACTION_PHP_EACH sorcerer_valid_spells AS sorc_spell => ind BEGIN
    ACTION_IF (%ind% > 0) BEGIN
      OUTER_SET spl_ind = 0
	  ACTION_IF (FILE_CONTAINS_EVALUATED (~%spl_clon_list%.2da~ ~%sorc_spell%~)) BEGIN
		COPY_EXISTING ~d5xclons.2da~ ~override~
		  COUNT_2DA_COLS cols
	      READ_2DA_ENTRIES_NOW ~r2en_xclons~ cols
	      FOR (row = 0; row < r2en_xclons; ++row) BEGIN
	        READ_2DA_ENTRY_FORMER ~r2en_xclons~ row 0 prev_ind
	        READ_2DA_ENTRY_FORMER ~r2en_xclons~ row 2 cast_spell
	        PATCH_IF (~%sorc_spell%~ STRING_EQUAL_CASE ~%cast_spell%~) BEGIN
	          SET spl_ind = prev_ind
	        END 
	      END
	    BUT_ONLY
      END
      ACTION_IF (spl_ind = 0) BEGIN
        OUTER_SET high_ind = high_ind + 1
	    OUTER_SET spl_ind = high_ind
	  END
      APPEND ~%spl_clon_list%.2da~ ~%spl_ind% 	%sorc_spell% 	%sorc_spell% 	arcane 	no ~ UNLESS ~%sorc_spell% 	%sorc_spell%~
    END
  END

  ACTION_IF (FILE_EXISTS_IN_GAME ~%itm_name%.spl~) BEGIN
    DELETE ~override/%itm_name%.spl~
  END
 
  INCLUDE ~%MOD_FOLDER%/lib/semi_spont/sequencer_menu.tpa~

  OUTER_SET spell_selection = RESOLVE_STR_REF (@211)
  OUTER_SET learn_new_spells = RESOLVE_STR_REF (@212)

  LAF CREATE_SEQUENCER_MENU 
    INT_VAR 
	 name = %spell_selection%
	 tip = %spell_selection%
	 desc = %learn_new_spells%
    STR_VAR 
	 resref = EVAL ~%itm_name%~
	 spelllist = EVAL ~%spl_list%~
	 spelltable = EVAL ~%spl_tbl%~
	 icon = ~spcl919b~
	 title = ~Spell Selection~
	 label = ~Select a spell to learn~
	 subspell = EVAL ~%menu_suffix%~
  END

  COPY_EXISTING ~%spl_list%.2da~ ~override/%spl_list%X.2da~

  COPY ~%MOD_FOLDER%/lib/semi_spont/d5lernwi.bam~ ~override~

  COPY ~%MOD_FOLDER%/lib/semi_spont/d5xsorc.itm~ ~override/%itm_name%.itm~			//	learn spells .itm
    SAY NAME1 @301
    SAY NAME2 @301
    SAY UNIDENTIFIED_DESC @301
    SAY IDENTIFIED_DESC @301
    LPF ALTER_ITEM_HEADER INT_VAR target = 7 speed = 0 STR_VAR icon = ~d5lernwi~ END
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR match_resource = ~d5xsorc~ resource = EVAL ~%itm_name%~ END

//  OUTER_SET strng = RESOLVE_STR_REF (@301)

  OUTER_INNER_PATCH ~1~ BEGIN
    WRITE_BYTE 0 0x09
    READ_ASCII 0 tab (1)  // 0x09, tab
    WRITE_BYTE 0 0x0d
    READ_ASCII 0 mnl (1)  // 0x0d, Mac
  END
  LAF ~ADD_ITEM_TOOLTIPS~ STR_VAR item = EVAL ~%itm_name%~ tooltips = ~@301~ /*EVAL ~%strng%~*/ END

  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_marker.d5~ ~override/d5__sorc_learning.d5~

END		//	end with_tra

END		//	end define function


//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION semi_sorcerer_casting STR_VAR sorc_suffix = ~w~ spl_list = ~d5xsorc~ spl_clon_list = ~d5xclons~ BEGIN
// suffix must match the one in the menu function


//find game install language__________________________________________________________
//
LAF set_lang RET game_lang END

WITH_TRA ~%MOD_FOLDER%/lib/semi_spont/%game_lang%/semi_spont.tra~ BEGIN


//add spell slot stat checks to SPLPROT______________________________________________
//
APPEND ~splprot.2da~ ~D5_WIZ_1_6%TAB%108%TAB%-1%TAB%7~ UNLESS ~D5_WIZ_1_6~
APPEND ~splprot.2da~ ~D5_WIZ=1_6%TAB%108%TAB%-1%TAB%8~ UNLESS ~D5_WIZ=1_6~
APPEND ~splprot.2da~ ~D5_SPL_7_9%TAB%109%TAB%-1%TAB%7~ UNLESS ~D5_SPL_7_9~
APPEND ~splprot.2da~ ~D5_SPL=7_9%TAB%109%TAB%-1%TAB%8~ UNLESS ~D5_SPL=7_9~
APPEND ~splprot.2da~ ~D5_FATIGUE_0%TAB%30%TAB%0%TAB%1~ UNLESS ~D5_FATIGUE_0~
APPEND ~splprot.2da~ ~D5_FATIGUE_1%TAB%30%TAB%1%TAB%4~ UNLESS ~D5_FATIGUE_1~
APPEND ~splprot.2da~ ~D5_KIT_IS%TAB%152%TAB%-1%TAB%1~ UNLESS ~D5_KIT_IS~

COPY_EXISTING ~splprot.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW rows cols
  FOR (row = 1; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 0 ~stat~
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_WIZ_1_6~) BEGIN
	  SET fake_sorc_slots_1_6 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_WIZ=1_6~) BEGIN
	  SET fake_sorc_equal_1_6 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_SPL_7_9~) BEGIN
	  SET fake_spel_slots_7_9 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_SPL=7_9~) BEGIN
	  SET fake_spel_equal_7_9 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_FATIGUE_0~) BEGIN
	  SET fatigue_zero = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_FATIGUE_1~) BEGIN
	  SET fatigue_one = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_KIT_IS~ BEGIN
	  SET kit_is_row = %row%
	END
  END
BUT_ONLY

ACTION_IF (FILE_CONTAINS_EVALUATED (~splstate.ids~ ~D5_SEMI_SORC~)) BEGIN
  COPY_EXISTING ~splstate.ids~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 ~state_name~
	  READ_2DA_ENTRY_FORMER rows row 0 ~state_ind~
	  PATCH_IF (~%state_name%~ STRING_EQUAL_CASE ~D5_SEMI_SORC~) BEGIN
		SET semi_sorc_state = %state_ind%
	  END
	END
  BUT_ONLY
END

ACTION_IF !(VARIABLE_IS_SET %semi_sorc_state%) BEGIN
  LAF d5_resolve_state STR_VAR new_state_id = ~D5_SEMI_SORC~ RET new_state_ind END
  OUTER_SET semi_sorc_state = %new_state_ind%
END

ACTION_IF (FILE_CONTAINS_EVALUATED (~splstate.ids~ ~D5_SEMI_REST~)) BEGIN
  COPY_EXISTING ~splstate.ids~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 ~state_name~
	  READ_2DA_ENTRY_FORMER rows row 0 ~state_ind~
	  PATCH_IF (~%state_name%~ STRING_EQUAL_CASE ~D5_SEMI_REST~) BEGIN
		SET semi_spont_rest = %state_ind%
	  END
	END
  BUT_ONLY
END

ACTION_IF !(VARIABLE_IS_SET %semi_spont_rested%) BEGIN
  LAF d5_resolve_state STR_VAR new_state_id = ~D5_SEMI_REST~ RET new_state_ind END
  OUTER_SET semi_spont_rest = %new_state_ind%
END


ACTION_IF !(FILE_EXISTS_IN_GAME ~d5__semi_sorc_casting.d5~) BEGIN


//disable quickspells and scroll learning____________________________________________
//
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5xnoqk.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xnoqk.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 3 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 4 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 5 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 101 target = 1 parameter2 = 147 timing = 9 END
END


//remove all mage spell slots_________________________________________________________
//
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5x0slt.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5x0slt.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 target = 1 parameter1 = (0 - 1) parameter2 = 511 timing = 9 END
 BUT_ONLY
END


//create advance copies of some spells________________________________________________
//
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xx206.spl~

COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xx172.spl~

COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5x0spl.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~SPWI908~ END
  PATCH_IF !(FILE_EXISTS_IN_GAME ~d5__new_identify.d5~) BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~SPWI110~ END
  END
  PATCH_IF !(MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~55~) BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~SPWI420~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~SPWI710~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~SPWI809~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~SPWI617~ END
  END

COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot1a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot1b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot1c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot1d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot2a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot2b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot2c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot2d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot3a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot3b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot3c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot3d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot4a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot4b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot4c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot4d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot5a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot5b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot5c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot5d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot6a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot6b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot6c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot6d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot7a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot7b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot7c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot7d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot8a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot8b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot8c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot8d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot9a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot9b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot9c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xwot9d.spl~

COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xspls.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 8) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot1a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 8) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot1b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 8) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot1c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 8) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot1d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 12) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot2a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 12) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot2b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 12) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot2c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 12) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot2d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 16) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot3a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 16) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot3b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 16) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot3c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 16) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot3d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 20) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot4a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 20) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot4b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 20) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot4c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 20) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot4d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 24) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot5a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 24) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot5b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 24) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot5c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 24) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot5d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 28) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot6a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 28) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot6b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 28) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot6c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 28) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5xwot6d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 20) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5xwot7a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 20) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5xwot7b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 20) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5xwot7c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 20) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5xwot7d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 24) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5xwot8a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 24) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5xwot8b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 24) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5xwot8c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 24) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5xwot8d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 28) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5xwot9a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 28) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5xwot9b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 28) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5xwot9c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 28) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5xwot9d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5xspls~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 318 insert_point = 0 target = 1 parameter1 = %semi_sorc_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = ~d5xspls~ END

//assign stats for spell slots to each spell level____________________________________
//
// arcane level 1 = 	108 << 8
// arcane level 2 = 	108 << 12
// arcane level 3 = 	108 << 16
// arcane level 4 = 	108 << 20
// arcane level 5 = 	108 << 24
// arcane level 6 = 	108 << 28
// arcane level 7 = 	109 << 20
// arcane level 8 = 	109 << 24
// arcane level 9 = 	109 << 28
//

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src1a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src1%let%.spl~
	  SAY NAME1 @101
	  SAY UNIDENTIFIED_DESC @101
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 8) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src2a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src2%let%.spl~
	  SAY NAME1 @102
	  SAY UNIDENTIFIED_DESC @102
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 12) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src3a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src3%let%.spl~
	  SAY NAME1 @103
	  SAY UNIDENTIFIED_DESC @103
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src4a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src4%let%.spl~
	  SAY NAME1 @104
	  SAY UNIDENTIFIED_DESC @104
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 20) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src5a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src5%let%.spl~
	  SAY NAME1 @105
	  SAY UNIDENTIFIED_DESC @105
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 24) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src6a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src6%let%.spl~
	  SAY NAME1 @106
	  SAY UNIDENTIFIED_DESC @106
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 28) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src7a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src7%let%.spl~
	  SAY NAME1 @107
	  SAY UNIDENTIFIED_DESC @107
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 20) parameter2 = (109 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src8a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src8%let%.spl~
	  SAY NAME1 @108
	  SAY UNIDENTIFIED_DESC @108
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 24) parameter2 = (109 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src9a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src9%let%.spl~
	  SAY NAME1 @109
	  SAY UNIDENTIFIED_DESC @109
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 28) parameter2 = (109 + (0x10000 * 1)) timing = 9 END
  END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src-1.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src-1.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src-2.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src-2.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src-3.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src-3.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src-4.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src-4.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src-5.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src-5.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 24) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src-6.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src-6.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 28) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src-7.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src-7.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src-8.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src-8.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 24) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src-9.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src-9.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 28) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END


//quickly address wondrous recall_____________________________________________________
//
ACTION_IF (MOD_IS_INSTALLED ~d5_random_tweaks.tp2~ ~1611~) BEGIN
  COPY_EXISTING ~sppr611.spl~ ~override~
    LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = ~d5src-1~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = ~d5src-2~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-1~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-2~ END
  BUT_ONLY
  ACTION_IF (FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~) BEGIN
    ACTION_IF (FILE_EXISTS_IN_GAME ~potn43.spl~) BEGIN
//	  COPY_EXISTING ~sppr611.spl~ ~override/potn43.spl~
	  COPY_EXISTING ~potn43.spl~ ~override~
        LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = ~d5src-1~ END
        LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = ~d5src-2~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-1~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-2~ END
	  IF_EXISTS BUT_ONLY
    END
  END
END


//daily spell slot refresh____________________________________________________________
//
COPY ~%MOD_FOLDER%/lib/semi_spont/d5zcast.bam~ ~override~

COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xlotz.spl~
  SAY NAME1 @300
  SAY UNIDENTIFIED_DESC @300
  LPF ALTER_SPELL_HEADER INT_VAR target = 7 STR_VAR icon = ~d5zcast~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~d5xlots~ END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5xlots.eff~) BEGIN
  CREATE EFF ~d5xlots~
	WRITE_LONG 0x10 232
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 0
	WRITE_LONG 0x20 20
	WRITE_LONG 0x24 9
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~d5xlots~ #8
	WRITE_LONG 0x48 102
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5xlots.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xlots.spl~
    LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sorc_state% parameter2 = 111 timing = 1 STR_VAR resource = ~d5xxini~ END
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sorc_state% parameter2 = 111 timing = 1 STR_VAR resource = ~d5xstts~ END
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sorc_state% parameter2 = 111 timing = 1 STR_VAR resource = ~d5xx001~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %fatigue_zero% timing = 1 STR_VAR resource = ~d5xlotf~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %fatigue_one% timing = 1 STR_VAR resource = ~d5xrest~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5xx001.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xx001.spl~
    LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sorc_state% parameter2 = 111 timing = 1 STR_VAR resource = ~d5xxini~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sorc_state% parameter2 = 111 timing = 1 STR_VAR resource = ~d5xstts~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5xstts.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xstts.spl~
//    LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (2 << 24) parameter2 = (115 + (0x10000 * 1)) timing = 9 END
// do that ^ in xsor1.spl in spell learning function, so regular sorcerers get it too
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsorc~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 328 target = 1 special = 1 parameter2 = %semi_sorc_state% timing = 9 END
    LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %semi_sorc_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = ~d5xstts~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5xlotf.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xlotf.spl~
    LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5xnfsh~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_rest% parameter2 = 111 timing = 1 STR_VAR resource = ~d5xrfsh~ END
    LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %semi_sorc_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = ~d5xlotf~ END
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5xrfsh.spl~ BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xrfsh.spl~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5xx172~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_rest% parameter2 = 111 timing = 1 duration = 0 STR_VAR resource = ~d5zrest~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5zz145~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-1~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-2~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-3~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-4~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-5~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-6~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-7~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-8~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-9~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src1z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src2z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src3z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src4z~ END
  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src5z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src6z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src7z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src8z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src9z~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sorc_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5xspls~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zrest.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zrest.spl~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 328 target = 1 special = 1 parameter2 = %semi_spont_rest% timing = 9 END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5xrest.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xrest.spl~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5zrest~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5xxfat.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xxfat.spl~
    LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 1 parameter2 = 1 timing = 4 duration = 6 END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5xnfsh.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xnfsh.spl~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 18 STR_VAR resource = ~d5xrfsh~ END
END

// put this xx000 in the clab tables
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5xx000.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xx000.spl~
    LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
    SAY NAME1 @300
    SAY UNIDENTIFIED_DESC @300
    LPF ALTER_SPELL_HEADER INT_VAR target = 7 STR_VAR icon = ~d5zcast~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 1 parameter2 = 1 timing = 1 END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5xlotz~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~d5xlots~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5zzini~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5xx000~ END
    LPF ADD_SPELL_EFFECT INT_VAR insert_point = 1 opcode = 318 target = 1 parameter1 = 19 parameter2 = 105 timing = 9 STR_VAR resource = ~d5xx000~ END
    LPF ADD_SPELL_EFFECT INT_VAR insert_point = 1 opcode = 318 target = 1 parameter1 = 2 parameter2 = 112 timing = 9 STR_VAR resource = ~d5xx000~ END
    LPF ADD_SPELL_EFFECT INT_VAR insert_point = 1 opcode = 318 target = 1 parameter1 = %semi_sorc_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = ~d5xlotf~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5xxini.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xxini.spl~
    LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5xx206~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5xnoqk~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5x0spl~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5x0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5x0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5x0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5x0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5x0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5x0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5x0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5x0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5x0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5x0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5x0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5x0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5xstts~ END
//    PATCH_IF (FILE_EXISTS_IN_GAME ~d5xsor1.spl~) BEGIN
//      LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5xsor1~ END
//    END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 1 parameter2 = 0 timing = 1 END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5zncast~ END
//    LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 4 END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 3 STR_VAR resource = ~d5xlotf~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5xxini~ END
END


COPY ~%MOD_FOLDER%/lib/semi_spont/d5_marker.d5~ ~override/d5__semi_sorc_casting.d5~


//fix burning hands targeting_______________________________________________________
//
COPY_EXISTING ~spwi103.spl~ ~override~
  READ_LONG 0x08 burning_hands_strref
BUT_ONLY

ACTION_IF (IS_AN_INT %burning_hands_strref%) BEGIN
  COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
	PATCH_IF (%SOURCE_SIZE% > 0x71) BEGIN
	  SET burning_change = 0
	  READ_LONG 0x08 name
	  PATCH_IF (name = burning_hands_strref) BEGIN
		GET_OFFSET_ARRAY ab_array SPL_V10_HEADERS
		PHP_EACH ab_array AS int => ab_off BEGIN
		  PATCH_IF (burning_change = 0) BEGIN
			READ_BYTE (ab_off + 0x0c) target
			PATCH_IF target = 5 BEGIN
			  SET burning_change = 1
			END
		  END
		END
		PATCH_IF (burning_change = 1) BEGIN
		  LPF ALTER_SPELL_HEADER INT_VAR target = 1 END
		  LPF ALTER_EFFECT INT_VAR match_opcode = 148 opcode = 146 target = 2 STR_VAR match_resource = ~spwi103~ END
		  WRITE_BYTE 0x1b (THIS BOR 1)
		END
	  END
	END
  BUT_ONLY
END

//fix black pits 2___________________________________________________________________
//
COPY_EXISTING ~ohbantim.spl~ override
  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 144 match_parameter2 = 13 opcode = 145 parameter2 = 3 END
IF_EXISTS BUT_ONLY

// change BP1 to allow innates too
// EDIT - don't need to!
//__________________________________________________________________________________


END		//	end marker file check


// casting system______________________________________________________________________
//
COPY_EXISTING ~%spl_clon_list%.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW ~r2en_xclons~ cols
  FOR (row = 0; row < r2en_xclons; ++row) BEGIN
    READ_2DA_ENTRY_FORMER ~r2en_xclons~ row 0 x_ind
    READ_2DA_ENTRY_FORMER ~r2en_xclons~ row 1 mem_spell
    READ_2DA_ENTRY_FORMER ~r2en_xclons~ row 2 cast_spell
    READ_2DA_ENTRY_FORMER ~r2en_xclons~ row 3 spell_type
    READ_2DA_ENTRY_FORMER ~r2en_xclons~ row 4 spell_proc
    PATCH_IF (x_ind > 100) AND (~%spell_proc%~ STRING_EQUAL_CASE ~no~) BEGIN
      SPRINT innate_spell ~d5x%x_ind%i~
      SPRINT give_spell ~d5x%x_ind%g~
      SPRINT block_spell ~d5x%x_ind%b~
      SPRINT learn_spell ~d5x%x_ind%l~
      SPRINT switch_spell ~d5x%x_ind%h~
      SPRINT switch_subspell ~d5x%x_ind%w~
      INNER_ACTION BEGIN
        COPY_EXISTING ~%mem_spell%.spl~ ~override~
          SET size = SOURCE_SIZE
          READ_LONG 0x34 level
        IF_EXISTS BUT_ONLY
// create innate spell
       ACTION_IF (size > 155) BEGIN
		COPY_EXISTING ~%cast_spell%.spl~ ~override/%innate_spell%.spl~
//		  SAY NAME1 ~~
//		  SAY UNIDENTIFIED_DESC ~~
		  WRITE_SHORT 0x1c 4
		  WRITE_BYTE 0x27 0									//	no sectype for the innates
		  LPF ALTER_SPELL_HEADER INT_VAR location = 2 END
		  READ_LONG 0x64 abil_offset
		  READ_SHORT 0x68 abil_number
		  READ_BYTE (%abil_offset% + 0x0c) abil_target					
		  READ_SHORT (%abil_offset% + 0x0e) abil_range
		  READ_LONG 0x6a eff_offset
		  WHILE (%abil_number% > 0) BEGIN
			SET abil_number = (%abil_number% - 1)
			WRITE_SHORT (%abil_offset% + 0x26 + (0x28 * %abil_number%)) 1
		  END
		  READ_BYTE (%eff_offset% + 0x02) eff_target
		  LPF DELETE_EFFECT END
		  PATCH_IF (%abil_target% = 4) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 1 power = 0 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%cast_spell%~ END
			PATCH_IF (%abil_range% < 35) BEGIN
			  PATCH_IF (%abil_range% > 4) BEGIN
				LPF ALTER_SPELL_HEADER INT_VAR range = (%abil_range% - 3) END
			  END
			  PATCH_IF (%abil_range% < 5) BEGIN
			 	LPF ALTER_SPELL_HEADER INT_VAR target = 5 END	// might need to carve out exceptions, e.g. burning hands
			  END
			END
		  END
		  ELSE BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 power = 0 parameter2 = 1 timing = 9 STR_VAR resource = EVAL ~%cast_spell%~ END
		  END
// exempt lvl 1 if lv1 1 cantrips
          PATCH_IF (MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~62~) OR (MOD_IS_INSTALLED ~SubtleD_Spell_Tweaks.tp2~ ~62~) BEGIN	//	level 1 cantrips
		    PATCH_IF (%level% > 1) BEGIN
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5src-%level%~ END
		    END
		  END
		  PATCH_IF !(MOD_IS_INSTALLED ~tomeandblood.tp2~ ~62~) AND !(MOD_IS_INSTALLED ~SubtleD_Spell_Tweaks.tp2~ ~62~) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5src-%level%~ END
		  END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5xx172~ END
//		  PF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sorc_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5xspls~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5xspls~ END
          LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %fatigue_zero% timing = 1 STR_VAR resource = ~d5xxfat~ END
// make spells adding the innate spell
		COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/%give_spell%.spl~
          LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%innate_spell%~ END
// make 206 spells preventing the .EFF
	    COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/%block_spell%.spl~
		  WRITE_SHORT 0x1c 4
	  	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%give_spell%~ END
// add 206 spells to CLAB spell
	    COPY_EXISTING ~d5xx206.spl~ ~override~
	      LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = EVAL ~%block_spell%~ END
	      LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = EVAL ~%block_spell%~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%block_spell%~ END
	  	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%block_spell%~ END
// make learn spells canceling the 206
		COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/%learn_spell%.spl~
	  	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%block_spell%~ END
//		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%block_spell%~ END
// add 172 to zz172
	    COPY_EXISTING ~d5xx172.spl~ ~override~
		  LPF ADD_SPELL_EFFECT INT_VAR /*insert_point = 0*/ opcode = 172 target = 1 timing = 1 STR_VAR resource = EVAL ~%innate_spell%~ END
// learn from seq menu
		ACTION_IF (FILE_EXISTS_IN_GAME ~%cast_spell%%sorc_suffix%.spl~) BEGIN
		  COPY_EXISTING ~%cast_spell%%sorc_suffix%.spl~ ~override~
//		    LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%mem_spell%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sorc_state% parameter2 = 110 timing = 1 duration = 0 STR_VAR resource = EVAL ~%learn_spell%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sorc_state% parameter2 = 110 timing = 1 duration = 0 STR_VAR resource = ~d5xx172~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sorc_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5xspls~ END
		END
// enable spell switching
	    ACTION_IF (FILE_EXISTS_IN_GAME ~%switch_spell%.spl~) BEGIN
		  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/%switch_subspell%.spl~
		    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = EVAL ~%learn_spell%~ END 
		    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%block_spell%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sorc_state% parameter2 = 110 timing = 1 duration = 0 STR_VAR resource = ~d5xx172~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sorc_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5xspls~ END
		  COPY_EXISTING ~%switch_spell%.spl~ ~override~
		    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sorc_state% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~%switch_subspell%~ END
		  BUT_ONLY
	    END
// conditionally add 172 to zw172 - use to remove spells upon equipping armor
		ACTION_IF (FILE_EXISTS_IN_GAME ~d5zw172.spl~) BEGIN
	      COPY_EXISTING ~d5zw172.spl~ ~override~
	        LPF DELETE_EFFECT INT_VAR match_opcode = 172 STR_VAR match_resource = EVAL ~%innate_spell%~ END
		    LPF ADD_SPELL_EFFECT INT_VAR /*insert_point = 0*/ opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%innate_spell%~ END
		END
// remove all known spells after chargen
        COPY_EXISTING ~d5x0spl.spl~ ~override~
          LPF DELETE_EFFECT INT_VAR match_opcode = 172 STR_VAR match_resource = EVAL ~%cast_spell%~ END
          LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 1 STR_VAR resource = EVAL ~%cast_spell%~ END
        IF_EXISTS
// generate slot#x spells
		ACTION_IF (FILE_EXISTS_IN_GAME ~d5xwot%level%a.spl~) BEGIN
			COPY_EXISTING ~d5xwot%level%a.spl~ ~override~
		      LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
		END
		ACTION_IF (FILE_EXISTS_IN_GAME ~d5xwot%level%a.spl~) BEGIN
			COPY_EXISTING ~d5xwot%level%b.spl~ ~override~
		      LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
		END
		ACTION_IF (FILE_EXISTS_IN_GAME ~d5xwot%level%a.spl~) BEGIN
			COPY_EXISTING ~d5xwot%level%c.spl~ ~override~
		      LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
		END
		ACTION_IF (FILE_EXISTS_IN_GAME ~d5xwot%level%a.spl~) BEGIN
			COPY_EXISTING ~d5xwot%level%d.spl~ ~override~
		      LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
		END
       END
      END
      SET_2DA_ENTRY row 4 cols ~yes~
    END
  END
BUT_ONLY

/* bard casting installed later now
ACTION_IF (FILE_EXISTS_IN_GAME ~d5zw172.spl~) BEGIN
  COPY_EXISTING ~d5zw172.spl~ ~override/d5zw172l.spl~
    PATCH_IF (MOD_IS_INSTALLED ~tomeandblood.tp2~ ~48~) BEGIN
      LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 5 parameter2 = 105 timing = 0 duration = 1 STR_VAR resource = ~d5zw172l~ END
    END
  COPY_EXISTING ~d5zw172.spl~ ~override/d5zw172c.spl~
  COPY_EXISTING ~d5zw172.spl~ ~override/d5zw172p.spl~
END
*/

END		//	end with_tra


END		//	end define function


//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION add_sorcerer_spells STR_VAR menu_suffix = ~W~ new_list = ~~ spl_list = ~d5xsorc~ BEGIN


//find game install language__________________________________________________________
//
LAF set_lang RET game_lang END

WITH_TRA ~%MOD_FOLDER%/lib/semi_spont/%game_lang%/semi_spont.tra~ BEGIN

  ACTION_IF !(FILE_EXISTS_IN_GAME ~%spl_list%.2da~) BEGIN

<<<<<<<<  d5/d5xsorc.2da
2DA V1.0
****
            	     ResRef   Type>>>>>>>>
   COPY ~d5/d5xsorc.2da~ ~override/%spl_list%.2da~
   
  END	//	end spell list doesn't exist

  ACTION_PHP_EACH ~%new_list%~ AS new_spl => ind BEGIN
    APPEND ~%spl_list%.2da~ ~sorcerer	%new_spl%	3~ UNLESS ~sorcerer	%new_spl%~
  END

  COPY_EXISTING ~%spl_list%.2da~ ~override~
    COUNT_2DA_COLS cols
    READ_2DA_ENTRIES_NOW ~r2en_xsorc~ cols
    FOR (row = 0; row < r2en_xsorc; ++row) BEGIN
      READ_2DA_ENTRY_FORMER ~r2en_xsorc~ row 1 mem_spell
      INNER_ACTION BEGIN
	    ACTION_IF (FILE_EXISTS_IN_GAME ~%mem_spell%.spl~) BEGIN
		  ACTION_IF !(FILE_EXISTS_IN_GAME ~%mem_spell%%menu_suffix%.spl~) BEGIN
            COPY_EXISTING ~%mem_spell%.spl~ ~override~
		      READ_STRREF NAME1 spell_name
		      READ_STRREF UNIDENTIFIED_DESC spell_description
		      READ_LONG 0x34 spell_level
		      READ_ASCII 0x3a spell_icon
		    BUT_ONLY
		    COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/%mem_spell%%menu_suffix%.spl~
              SAY NAME1 ~%spell_name%~
              SAY UNIDENTIFIED_DESC ~%spell_description%~
			  WRITE_EVALUATED_ASCII 0x3a ~%spell_icon%~ #8
			  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL ~%spell_icon%~ END
		  	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%mem_spell%~ END
		  END
		END
	  END
	END
  BUT_ONLY


END		//	end with_tra

END		//	end define function


//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION divine_spell_learning STR_VAR menu_suffix = ~W~ BEGIN


//find game install language__________________________________________________________
//
LAF set_lang RET game_lang END

WITH_TRA ~%MOD_FOLDER%/lib/semi_spont/%game_lang%/semi_spont.tra~ BEGIN


ACTION_IF !(FILE_EXISTS_IN_GAME ~d5__cler_learning.d5~) BEGIN

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5_shmkn.2da~) BEGIN
  COPY_EXISTING ~splshmkn.2da~ ~override/d5_shmkn.2da~
END

// divine spont spell system legend
//
<<<<<<<<  d5/d5ycler.2da
2DA V1.0
****
            	     ResRef   Type>>>>>>>>
  COPY ~d5/d5ycler.2da~ ~override/d5ycler.2da~

 ACTION_IF !(FILE_EXISTS_IN_GAME ~d5yclons.2da~) BEGIN
<<<<<<<< d5/d5yclons.2da
2DA V1.0 
IND
		MEM 		CAST 		TYPE	PROCESSED
100		#			#			#		#
>>>>>>>> 
  COPY ~d5/d5yclons.2da~ ~override/d5yclons.2da~ 
END

//ACTION_IF (FILE_EXISTS_IN_GAME ~d5yclons.2da~) BEGIN

  OUTER_SET high_ind = 99
  COPY_EXISTING ~d5yclons.2da~ ~override~
    COUNT_2DA_COLS cols
    READ_2DA_ENTRIES_NOW ~r2en_yclons~ cols
    FOR (row = 0; row < r2en_yclons; ++row) BEGIN
      READ_2DA_ENTRY_FORMER ~r2en_yclons~ row 0 this_ind
      PATCH_IF (this_ind > high_ind) BEGIN
        SET high_ind = this_ind
      END
    END
  BUT_ONLY

  COPY_EXISTING ~d5yclons.2da~ ~override~
    COUNT_2DA_COLS cols
    COUNT_2DA_ROWS cols rows
    READ_2DA_ENTRY (rows - 1) 0 cols last_ind
  BUT_ONLY

  COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
    PATCH_IF (%SOURCE_SIZE% > 0x71) BEGIN
//    SNPRINT 4 spell_prefix ~%SOURCE_RES%~
      READ_SHORT 0x1c spell_type 
	  READ_BYTE 0x21 ok_cleric
      READ_LONG 0x34 spell_level
      PATCH_IF (~%SOURCE_RES%~ STRING_MATCHES_REGEXP ~[Ss][Pp][Pp][Rr][1-9][0-5][0-9]$~ = 0) && (spell_type = 2) && ((%ok_cleric% BOR 0b10111111) = 0b10111111) BEGIN
	    SNPRINT (0 - 3) spell_num ~%SOURCE_RES%~
	    SET go = 1
	    PATCH_IF (go = 1) && !(FILE_CONTAINS_EVALUATED (~hidespl.2da~ ~%SOURCE_RES%~)) BEGIN
          SPRINT $cleric_spells(~%SOURCE_RES%~) ~1~
        END
      END
    END
  BUT_ONLY
  
  ACTION_PHP_EACH cleric_spells AS cler_spell => ind BEGIN
    ACTION_IF (%ind% > 0) BEGIN
      OUTER_SET spl_ind = 0
	  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5yclons.2da~ ~%cler_spell%~)) BEGIN
		COPY_EXISTING ~d5yclons.2da~ ~override~
		  COUNT_2DA_COLS cols
	      READ_2DA_ENTRIES_NOW ~r2en_yclons~ cols
	      FOR (row = 0; row < r2en_yclons; ++row) BEGIN
	        READ_2DA_ENTRY_FORMER ~r2en_yclons~ row 0 prev_ind
	        READ_2DA_ENTRY_FORMER ~r2en_yclons~ row 2 cast_spell
	        PATCH_IF (~%cler_spell%~ STRING_EQUAL_CASE ~%cast_spell%~) BEGIN
	          SET spl_ind = prev_ind
	        END 
	      END
	    BUT_ONLY
      END
      ACTION_IF (spl_ind = 0) BEGIN
        OUTER_SET high_ind = high_ind + 1
	    OUTER_SET spl_ind = high_ind
	  END
	  APPEND ~d5ycler.2da~ ~cleric  	%cler_spell%	3~
      APPEND ~d5yclons.2da~ ~%spl_ind% 	%cler_spell% 	%cler_spell% 	cleric 	no ~ UNLESS ~%cler_spell% 	%cler_spell%~
    END
  END

  COPY_EXISTING ~d5yclons.2da~ ~override~
    COUNT_2DA_COLS cols
    READ_2DA_ENTRIES_NOW ~r2en_yclons~ cols
    FOR (row = 0; row < r2en_yclons; ++row) BEGIN
      READ_2DA_ENTRY_FORMER ~r2en_yclons~ row 0 x_ind
      READ_2DA_ENTRY_FORMER ~r2en_yclons~ row 1 mem_spell
      INNER_ACTION BEGIN
	    ACTION_IF (FILE_EXISTS_IN_GAME ~%mem_spell%.spl~) BEGIN
          COPY_EXISTING ~%mem_spell%.spl~ ~override~
		    READ_STRREF NAME1 spell_name
		    READ_STRREF UNIDENTIFIED_DESC spell_description
		    READ_LONG 0x34 spell_level
		    READ_ASCII 0x3a spell_icon
		  BUT_ONLY
		  ACTION_IF !(FILE_EXISTS_IN_GAME ~%mem_spell%%menu_suffix%.spl~) BEGIN
		    COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/%mem_spell%%menu_suffix%.spl~
              SAY NAME1 ~%spell_name%~
              SAY UNIDENTIFIED_DESC ~%spell_description%~
			  WRITE_EVALUATED_ASCII 0x3a ~%spell_icon%~ #8
			  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL ~%spell_icon%~ END
		  	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%mem_spell%~ END
		  END
		END
	  END
	END
  BUT_ONLY

  INCLUDE ~%MOD_FOLDER%/lib/semi_spont/sequencer_menu.tpa~

  OUTER_SET spell_selection = RESOLVE_STR_REF (@211)
  OUTER_SET learn_new_spells = RESOLVE_STR_REF (@212)

  LAF CREATE_SEQUENCER_MENU 
    INT_VAR 
	 name = %spell_selection%
	 tip = %spell_selection%
	 desc = %learn_new_spells%
    STR_VAR 
	 resref = ~d5ycler~
	 spelllist = ~d5ycler~
	 spelltable = ~d5_shmkn~
	 icon = ~spcl919b~
	 title = ~Spell Selection~
	 label = ~Select a spell to learn~
	 subspell = EVAL ~%menu_suffix%~
  END

  COPY_EXISTING ~d5ycler.2da~ ~override/d5yclerX.2da~

  COPY ~%MOD_FOLDER%/lib/semi_spont/d5lernwi.bam~ ~override~

  COPY ~%MOD_FOLDER%/lib/semi_spont/d5ycler.itm~ ~override~			//	learn spells .itm
    SAY NAME1 @411
    SAY NAME2 @411
    SAY UNIDENTIFIED_DESC @411
    SAY IDENTIFIED_DESC @411
    LPF ALTER_ITEM_HEADER INT_VAR target = 7 speed = 0 STR_VAR icon = ~d5lernwi~ END

  OUTER_INNER_PATCH ~1~ BEGIN
    WRITE_BYTE 0 0x09
    READ_ASCII 0 tab (1)  // 0x09, tab
    WRITE_BYTE 0 0x0d
    READ_ASCII 0 mnl (1)  // 0x0d, Mac
  END
  LAF ~ADD_ITEM_TOOLTIPS~ STR_VAR item = ~d5ycler~ tooltips = ~@411~ END

  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ycle1.spl~
    SAY NAME1 @99
    SAY UNIDENTIFIED_DESC ~~
    WRITE_SHORT 0x1c 4
    LPF ALTER_SPELL_HEADER INT_VAR target = 5 location = 4 STR_VAR icon = ~d5lernwi~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (2 << 24) parameter2 = (115 + (0x10000 * 1)) timing = 9 END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5ycler~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5ycle1~ END

  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ycle2.spl~
    SAY NAME1 @99
    SAY UNIDENTIFIED_DESC ~~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5ycle1~ END


  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_marker.d5~ ~override/d5__cler_learning.d5~

END		//	end marker file check

END		//	end with_tra


END		//	end define function


//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION shaman_spell_learning STR_VAR menu_suffix = ~W~ BEGIN


//find game install language__________________________________________________________
//
LAF set_lang RET game_lang END

WITH_TRA ~%MOD_FOLDER%/lib/semi_spont/%game_lang%/semi_spont.tra~ BEGIN


ACTION_IF !(FILE_EXISTS_IN_GAME ~d5__sham_learning.d5~) BEGIN

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5_shmkn.2da~) BEGIN
  COPY_EXISTING ~splshmkn.2da~ ~override/d5_shmkn.2da~
END

// shaman spell system legend
//
<<<<<<<<  d5/d5ysham.2da
2DA V1.0
****
            	     ResRef   Type>>>>>>>>
  COPY ~d5/d5ysham.2da~ ~override/d5ysham.2da~

 ACTION_IF !(FILE_EXISTS_IN_GAME ~d5yclons.2da~) BEGIN
<<<<<<<< d5/d5yclons.2da
2DA V1.0 
IND
		MEM 		CAST 		TYPE	PROCESSED
100		#			#			#		#
>>>>>>>> 
  COPY ~d5/d5yclons.2da~ ~override/d5yclons.2da~ 
END

//ACTION_IF (FILE_EXISTS_IN_GAME ~d5yclons.2da~) BEGIN

  OUTER_SET high_ind = 99
  COPY_EXISTING ~d5yclons.2da~ ~override~
    COUNT_2DA_COLS cols
    READ_2DA_ENTRIES_NOW ~r2en_yclons~ cols
    FOR (row = 0; row < r2en_yclons; ++row) BEGIN
      READ_2DA_ENTRY_FORMER ~r2en_yclons~ row 0 this_ind
      PATCH_IF (this_ind > high_ind) BEGIN
        SET high_ind = this_ind
      END
    END
  BUT_ONLY

  COPY_EXISTING ~d5yclons.2da~ ~override~
    COUNT_2DA_COLS cols
    COUNT_2DA_ROWS cols rows
    READ_2DA_ENTRY (rows - 1) 0 cols last_ind
  BUT_ONLY

  COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
    PATCH_IF (%SOURCE_SIZE% > 0x71) BEGIN
//    SNPRINT 4 spell_prefix ~%SOURCE_RES%~
      READ_SHORT 0x1c spell_type 
	  READ_BYTE 0x21 ok_druid
      READ_LONG 0x34 spell_level
      PATCH_IF (~%SOURCE_RES%~ STRING_MATCHES_REGEXP ~[Ss][Pp][Pp][Rr][1-9][0-5][0-9]$~ = 0) && (spell_type = 2) && ((%ok_druid% BOR 0b01111111) = 0b01111111) BEGIN
	    SNPRINT (0 - 3) spell_num ~%SOURCE_RES%~
	    SET go = 1
	    PATCH_IF (go = 1) && !(FILE_CONTAINS_EVALUATED (~hidespl.2da~ ~%SOURCE_RES%~)) BEGIN
          SPRINT $druid_spells(~%SOURCE_RES%~) ~1~
        END
      END
    END
  BUT_ONLY
  
  ACTION_PHP_EACH druid_spells AS druid_spell => ind BEGIN
    ACTION_IF (%ind% > 0) BEGIN
      OUTER_SET spl_ind = 0
	  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5yclons.2da~ ~%sorc_spell%~)) BEGIN
		COPY_EXISTING ~d5yclons.2da~ ~override~
		  COUNT_2DA_COLS cols
	      READ_2DA_ENTRIES_NOW ~r2en_yclons~ cols
	      FOR (row = 0; row < r2en_yclons; ++row) BEGIN
	        READ_2DA_ENTRY_FORMER ~r2en_yclons~ row 0 prev_ind
	        READ_2DA_ENTRY_FORMER ~r2en_yclons~ row 2 cast_spell
	        PATCH_IF (~%druid_spell%~ STRING_EQUAL_CASE ~%cast_spell%~) BEGIN
	          SET spl_ind = prev_ind
	        END 
	      END
	    BUT_ONLY
      END
      ACTION_IF (spl_ind = 0) BEGIN
        OUTER_SET high_ind = high_ind + 1
	    OUTER_SET spl_ind = high_ind
	  END
	  APPEND ~d5ysham.2da~ ~druid   	%druid_spell%	3~
      APPEND ~d5yclons.2da~ ~%spl_ind% 	%druid_spell% 	%druid_spell% 	arcane 	no ~ UNLESS ~%druid_spell% 	%druid_spell%~
    END
  END

  COPY_EXISTING ~d5yclons.2da~ ~override~
    COUNT_2DA_COLS cols
    READ_2DA_ENTRIES_NOW ~r2en_yclons~ cols
    FOR (row = 0; row < r2en_yclons; ++row) BEGIN
      READ_2DA_ENTRY_FORMER ~r2en_yclons~ row 0 x_ind
      READ_2DA_ENTRY_FORMER ~r2en_yclons~ row 1 mem_spell
      INNER_ACTION BEGIN
	    ACTION_IF (FILE_EXISTS_IN_GAME ~%mem_spell%.spl~) BEGIN
          COPY_EXISTING ~%mem_spell%.spl~ ~override~
		    READ_STRREF NAME1 spell_name
		    READ_STRREF UNIDENTIFIED_DESC spell_description
		    READ_LONG 0x34 spell_level
		    READ_ASCII 0x3a spell_icon
		  BUT_ONLY
		  ACTION_IF !(FILE_EXISTS_IN_GAME ~%mem_spell%%menu_suffix%.spl~) BEGIN
		    COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/%mem_spell%%menu_suffix%.spl~
              SAY NAME1 ~%spell_name%~
              SAY UNIDENTIFIED_DESC ~%spell_description%~
			  WRITE_EVALUATED_ASCII 0x3a ~%spell_icon%~ #8
			  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL ~%spell_icon%~ END
		  	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%mem_spell%~ END
		  END
		END
	  END
	END
  BUT_ONLY

  INCLUDE ~%MOD_FOLDER%/lib/semi_spont/sequencer_menu.tpa~

  OUTER_SET spell_selection = RESOLVE_STR_REF (@211)
  OUTER_SET learn_new_spells = RESOLVE_STR_REF (@212)

  LAF CREATE_SEQUENCER_MENU 
    INT_VAR 
	 name = %spell_selection%
	 tip = %spell_selection%
	 desc = %learn_new_spells%
    STR_VAR 
	 resref = ~d5ysham~
	 spelllist = ~d5ysham~
	 spelltable = ~d5_shmkn~
	 icon = ~spcl919b~
	 title = ~Spell Selection~
	 label = ~Select a spell to learn~
	 subspell = EVAL ~%menu_suffix%~
  END

  COPY_EXISTING ~d5ysham.2da~ ~override/d5yshamX.2da~

  COPY ~%MOD_FOLDER%/lib/semi_spont/d5lernwi.bam~ ~override~

  COPY ~%MOD_FOLDER%/lib/semi_spont/d5ysham.itm~ ~override~			//	learn spells .itm
    SAY NAME1 @412
    SAY NAME2 @412
    SAY UNIDENTIFIED_DESC @412
    SAY IDENTIFIED_DESC @412
    LPF ALTER_ITEM_HEADER INT_VAR target = 7 speed = 0 STR_VAR icon = ~d5lernwi~ END

  OUTER_INNER_PATCH ~1~ BEGIN
    WRITE_BYTE 0 0x09
    READ_ASCII 0 tab (1)  // 0x09, tab
    WRITE_BYTE 0 0x0d
    READ_ASCII 0 mnl (1)  // 0x0d, Mac
  END
  LAF ~ADD_ITEM_TOOLTIPS~ STR_VAR item = ~d5ysham~ tooltips = ~@412~ END

  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5yshm1.spl~
    SAY NAME1 @99
    SAY UNIDENTIFIED_DESC ~~
    WRITE_SHORT 0x1c 4
    LPF ALTER_SPELL_HEADER INT_VAR target = 5 location = 4 STR_VAR icon = ~d5lernwi~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (2 << 24) parameter2 = (115 + (0x10000 * 1)) timing = 9 END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5ysham~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5yshm1~ END

  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5yshm2.spl~
    SAY NAME1 @99
    SAY UNIDENTIFIED_DESC ~~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5yshm1~ END


  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_marker.d5~ ~override/d5__sham_learning.d5~

END		//	end marker file check

END		//	end with_tra


END		//	end define function


//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION semi_shaman_casting STR_VAR sham_suffix = ~w~ BEGIN
// suffix must match the one in the menu function


ACTION_IF (FILE_EXISTS_IN_GAME ~5E_casting_settings.ini~) BEGIN
  	INCLUDE ~override/5E_casting_settings.ini~
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~5E_casting_settings.ini~) BEGIN
  	INCLUDE ~%MOD_FOLDER%/lib/semi_spont/5E_casting_settings.ini~
END

LAM 5E_casting_settings


//find game install language__________________________________________________________
//
LAF set_lang RET game_lang END

WITH_TRA ~%MOD_FOLDER%/lib/semi_spont/%game_lang%/semi_spont.tra~ BEGIN


ACTION_IF !(FILE_EXISTS_IN_GAME ~d5__semi_sham_casting.d5~) BEGIN

//disable quickspells and scroll learning____________________________________________
//
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5ynoqk.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ynoqk.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 3 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 4 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 5 timing = 9 END
END


//add spell slot stat checks to SPLPROT______________________________________________
//
APPEND ~splprot.2da~ ~D5_SPL_7_9%TAB%109%TAB%-1%TAB%7~ UNLESS ~D5_SPL_7_9~
APPEND ~splprot.2da~ ~D5_SPL=7_9%TAB%109%TAB%-1%TAB%8~ UNLESS ~D5_SPL=7_9~
APPEND ~splprot.2da~ ~D5_DIV_1_6%TAB%134%TAB%-1%TAB%7~ UNLESS ~D5_DIV_1_6~
APPEND ~splprot.2da~ ~D5_DIV=1_6%TAB%134%TAB%-1%TAB%8~ UNLESS ~D5_DIV=1_6~
APPEND ~splprot.2da~ ~D5_FATIGUE_0%TAB%30%TAB%0%TAB%1~ UNLESS ~D5_FATIGUE_0~
APPEND ~splprot.2da~ ~D5_FATIGUE_1%TAB%30%TAB%1%TAB%4~ UNLESS ~D5_FATIGUE_1~
APPEND ~splprot.2da~ ~D5_KIT_IS%TAB%152%TAB%-1%TAB%1~ UNLESS ~D5_KIT_IS~

COPY_EXISTING ~splprot.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW rows cols
  FOR (row = 1; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 0 ~stat~
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_SPL_7_9~) BEGIN
	  SET fake_spel_slots_7_9 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_SPL=7_9~) BEGIN
	  SET fake_spel_equal_7_9 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_DIV_1_6~) BEGIN
	  SET fake_sham_slots_1_6 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_DIV=1_6~) BEGIN
	  SET fake_sham_equal_1_6 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_FATIGUE_0~) BEGIN
	  SET fatigue_zero = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_FATIGUE_1~) BEGIN
	  SET fatigue_one = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_KIT_IS~ BEGIN
	  SET kit_is_row = %row%
	END
  END
BUT_ONLY

ACTION_IF (FILE_CONTAINS_EVALUATED (~splstate.ids~ ~D5_SEMI_SHAM~)) BEGIN
  COPY_EXISTING ~splstate.ids~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 ~state_name~
	  READ_2DA_ENTRY_FORMER rows row 0 ~state_ind~
	  PATCH_IF (~%state_name%~ STRING_EQUAL_CASE ~D5_SEMI_SHAM~) BEGIN
		SET semi_sham_state = %state_ind%
	  END
	END
  BUT_ONLY
END

ACTION_IF !(VARIABLE_IS_SET %semi_sham_state%) BEGIN
  LAF d5_resolve_state STR_VAR new_state_id = ~D5_SEMI_SHAM~ RET new_state_ind END
  OUTER_SET semi_sham_state = %new_state_ind%
END

ACTION_IF (FILE_CONTAINS_EVALUATED (~splstate.ids~ ~D5_SEMI_REST~)) BEGIN
  COPY_EXISTING ~splstate.ids~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 ~state_name~
	  READ_2DA_ENTRY_FORMER rows row 0 ~state_ind~
	  PATCH_IF (~%state_name%~ STRING_EQUAL_CASE ~D5_SEMI_REST~) BEGIN
		SET semi_spont_rest = %state_ind%
	  END
	END
  BUT_ONLY
END

ACTION_IF !(VARIABLE_IS_SET %semi_spont_rested%) BEGIN
  LAF d5_resolve_state STR_VAR new_state_id = ~D5_SEMI_REST~ RET new_state_ind END
  OUTER_SET semi_spont_rest = %new_state_ind%
END

ACTION_IF (FILE_CONTAINS_EVALUATED (~splstate.ids~ ~D5_SEMI_REST~)) BEGIN
  COPY_EXISTING ~splstate.ids~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 ~state_name~
	  READ_2DA_ENTRY_FORMER rows row 0 ~state_ind~
	  PATCH_IF (~%state_name%~ STRING_EQUAL_CASE ~D5_SEMI_REST~) BEGIN
		SET semi_spont_rest = %state_ind%
	  END
	END
  BUT_ONLY
END

ACTION_IF !(VARIABLE_IS_SET %semi_spont_rested%) BEGIN
  LAF d5_resolve_state STR_VAR new_state_id = ~D5_SEMI_REST~ RET new_state_ind END
  OUTER_SET semi_spont_rest = %new_state_ind%
END


//remove all mage spell slots_________________________________________________________
//
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5y0slt.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5y0slt.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
 BUT_ONLY
END


//create advance copies of some spells________________________________________________
//
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5yy206.spl~

COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5yy172.spl~

COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5y0spl.spl~

COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot1a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot1b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot1c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot1d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot2a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot2b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot2c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot2d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot3a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot3b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot3c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot3d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot4a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot4b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot4c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot4d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot5a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot5b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot5c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot5d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot6a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot6b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot6c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot6d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot7a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot7b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot7c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot7d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot8a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot8b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot8c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot8d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot9a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot9b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot9c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ydot9d.spl~

COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5yspld.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 8) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot1a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 8) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot1b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 8) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot1c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 8) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot1d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 12) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot2a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 12) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot2b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 12) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot2c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 12) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot2d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 16) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot3a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 16) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot3b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 16) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot3c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 16) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot3d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 20) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot4a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 20) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot4b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 20) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot4c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 20) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot4d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 24) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot5a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 24) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot5b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 24) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot5c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 24) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot5d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 28) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot6a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 28) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot6b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 28) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot6c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 28) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5ydot6d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 16) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5ydot7a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 16) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5ydot7b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 16) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5ydot7c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 16) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5ydot7d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5yspld~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 318 insert_point = 0 target = 1 parameter1 = %semi_sham_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = ~d5yspld~ END

//assign stats for spell slots to each spell level____________________________________
//
// divine level 1 = 	134 << 4
// divine level 2 = 	134 << 8
// divine level 3 = 	134 << 12
// divine level 4 = 	134 << 16
// divine level 5 = 	134 << 20
// divine level 6 = 	134 << 24
// divine level 7 = 	134 << 28
//

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm1a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm1%let%.spl~
	  SAY NAME1 @101
	  SAY UNIDENTIFIED_DESC @101
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 8) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm2a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm2%let%.spl~
	  SAY NAME1 @102
	  SAY UNIDENTIFIED_DESC @102
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 12) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm3a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm3%let%.spl~
	  SAY NAME1 @103
	  SAY UNIDENTIFIED_DESC @103
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm4a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm4%let%.spl~
	  SAY NAME1 @104
	  SAY UNIDENTIFIED_DESC@104
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 20) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm5a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm5%let%.spl~
	  SAY NAME1 @105
	  SAY UNIDENTIFIED_DESC @105
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 24) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm6a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm6%let%.spl~
	  SAY NAME1 @106
	  SAY UNIDENTIFIED_DESC @106
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 28) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm7a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm7%let%.spl~
	  SAY NAME1 @107
	  SAY UNIDENTIFIED_DESC @107
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (109 + (0x10000 * 1)) timing = 9 END
  END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm-1.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm-1.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm-2.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm-2.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm-3.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm-3.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm-4.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm-4.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm-5.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm-5.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 24) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm-6.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm-6.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 28) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm-7.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm-7.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END


//quickly address wondrous recall_____________________________________________________
//
ACTION_IF (MOD_IS_INSTALLED ~d5_random_tweaks.tp2~ ~1611~) BEGIN
  COPY_EXISTING ~sppr611.spl~ ~override~
    LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = ~d5shm-1~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = ~d5shm-2~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-1~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-2~ END
  BUT_ONLY
  ACTION_IF (FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~) BEGIN
    ACTION_IF (FILE_EXISTS_IN_GAME ~potn43.spl~) BEGIN
//	  COPY_EXISTING ~sppr611.spl~ ~override/potn43.spl~
	  COPY_EXISTING ~potn43.spl~ ~override~
        LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = ~d5shm-1~ END
        LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = ~d5shm-2~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-1~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-2~ END
	  IF_EXISTS BUT_ONLY
    END
  END
END


//daily spell slot refresh____________________________________________________________
//
COPY ~%MOD_FOLDER%/lib/semi_spont/d5zcast.bam~ ~override~

COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ylotz.spl~
  SAY NAME1 @400
  SAY UNIDENTIFIED_DESC @400
  LPF ALTER_SPELL_HEADER INT_VAR target = 7 STR_VAR icon = ~d5zcast~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~d5ylots~ END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5ylots.eff~) BEGIN
  CREATE EFF ~d5ylots~
	WRITE_LONG 0x10 232
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 0
	WRITE_LONG 0x20 20
	WRITE_LONG 0x24 9
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~d5ylots~ #8
	WRITE_LONG 0x48 102
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5ylots.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ylots.spl~
    LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sorc_state% parameter2 = 111 timing = 1 STR_VAR resource = ~d5yyini~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %fatigue_zero% timing = 1 STR_VAR resource = ~d5ylotf~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %fatigue_one% timing = 1 STR_VAR resource = ~d5xrest~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5yy001.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5yy001.spl~
    LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sham_state% parameter2 = 111 timing = 1 STR_VAR resource = ~d5yyini~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sham_state% parameter2 = 111 timing = 1 STR_VAR resource = ~d5ysttd~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5ysttd.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ysttd.spl~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5ysham~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 328 target = 1 special = 1 parameter2 = %semi_sham_state% timing = 9 END
    LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %semi_sham_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = ~d5ysttd~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5ylotf.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ylotf.spl~
    LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_rest% parameter2 = 111 timing = 1 STR_VAR resource = ~d5yrfsh~ END
    LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %semi_sorc_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = ~d5ylotf~ END
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5yrfsh.spl~ BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5yrfsh.spl~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5yy172~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_rest% parameter2 = 111 timing = 1 duration = 0 STR_VAR resource = ~d5zrest~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-1~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-2~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-3~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-4~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-5~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-6~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-7~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-8~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-9~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm1z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm2z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm3z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm4z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm5z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm6z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm7z~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sham_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5yspld~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zrest.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zrest.spl~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 328 target = 1 special = 1 parameter2 = %semi_spont_rest% timing = 9 END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5yrest.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5yrest.spl~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5zrest~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5yyfat.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5yyfat.spl~
    LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 1 parameter2 = 1 timing = 4 duration = 6 END
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5ynfsh.spl~ BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5ynfsh.spl~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 18 STR_VAR resource = ~d5yrfsh~ END
END

// put this xx000 in the clab tables
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5yy000.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5yy000.spl~
    LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
    SAY NAME1 @400
    SAY UNIDENTIFIED_DESC @400
    LPF ALTER_SPELL_HEADER INT_VAR target = 7 STR_VAR icon = ~d5zcast~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 1 parameter2 = 1 timing = 1 END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5ylotz~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~d5ylots~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5zzini~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5yy000~ END
    LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 21 parameter2 = 105 timing = 9 STR_VAR resource = ~d5yy000~ END
    LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 2 parameter2 = 112 timing = 9 STR_VAR resource = ~d5yy000~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5yyini.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5yyini.spl~
    LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5yy206~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5ynoqk~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5y0spl~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5y0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5y0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5y0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5y0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5y0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5y0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5y0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5y0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5y0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5y0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5y0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5y0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5ysttd~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 1 parameter2 = 0 timing = 1 END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5zncast~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 3 STR_VAR resource = ~d5ylotf~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5yyini~ END
END


COPY ~%MOD_FOLDER%/lib/semi_spont/d5_marker.d5~ ~override/d5__semi_sham_casting.d5~


//fix black pits 2___________________________________________________________________
//
COPY_EXISTING ~ohbantim.spl~ override
  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 144 match_parameter2 = 13 opcode = 145 parameter2 = 3 END
IF_EXISTS BUT_ONLY

// change BP1 to allow innates too
// EDIT - don't need to!
//__________________________________________________________________________________


END		//	end marker file check


// casting system______________________________________________________________________
//
COPY_EXISTING ~d5yclons.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW ~r2en_yclons~ cols
  FOR (row = 0; row < r2en_yclons; ++row) BEGIN
    READ_2DA_ENTRY_FORMER ~r2en_yclons~ row 0 x_ind
    READ_2DA_ENTRY_FORMER ~r2en_yclons~ row 1 mem_spell
    READ_2DA_ENTRY_FORMER ~r2en_yclons~ row 2 cast_spell
    READ_2DA_ENTRY_FORMER ~r2en_yclons~ row 3 spell_type
    READ_2DA_ENTRY_FORMER ~r2en_yclons~ row 4 spell_proc
    PATCH_IF (x_ind > 100) AND (~%spell_proc%~ STRING_EQUAL_CASE ~no~) BEGIN
      SPRINT innate_spell ~d5y%x_ind%i~
      SPRINT give_spell ~d5y%x_ind%g~
      SPRINT block_spell ~d5y%x_ind%b~
      SPRINT learn_spell ~d5y%x_ind%l~
      SPRINT switch_spell ~d5y%x_ind%h~
      SPRINT switch_subspell ~d5y%x_ind%w~
      INNER_ACTION BEGIN
        COPY_EXISTING ~%mem_spell%.spl~ ~override~
          READ_LONG 0x34 level
        IF_EXISTS BUT_ONLY
// create innate spell
		COPY_EXISTING ~%cast_spell%.spl~ ~override/%innate_spell%.spl~
//		  SAY NAME1 ~~
//		  SAY UNIDENTIFIED_DESC ~~
		  WRITE_SHORT 0x1c 4
		  WRITE_BYTE 0x27 0									//	no sectype for the innates
		  LPF ALTER_SPELL_HEADER INT_VAR location = 2 END
		  READ_LONG 0x64 abil_offset
		  READ_SHORT 0x68 abil_number
		  READ_BYTE (%abil_offset% + 0x0c) abil_target					
		  READ_SHORT (%abil_offset% + 0x0e) abil_range
		  READ_LONG 0x6a eff_offset
		  WHILE (%abil_number% > 0) BEGIN
			SET abil_number = (%abil_number% - 1)
			WRITE_SHORT (%abil_offset% + 0x26 + (0x28 * %abil_number%)) 1
		  END
		  READ_BYTE (%eff_offset% + 0x02) eff_target
		  LPF DELETE_EFFECT END
		  PATCH_IF (%abil_target% = 4) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 1 power = 0 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%cast_spell%~ END
			PATCH_IF (%abil_range% < 35) BEGIN
			  PATCH_IF (%abil_range% > 4) BEGIN
				LPF ALTER_SPELL_HEADER INT_VAR range = (%abil_range% - 3) END
			  END
			  PATCH_IF (%abil_range% < 5) BEGIN
			 	LPF ALTER_SPELL_HEADER INT_VAR target = 5 END	// might need to carve out exceptions, e.g. burning hands
			  END
			END
		  END
		  ELSE BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 power = 0 parameter2 = 1 timing = 9 STR_VAR resource = EVAL ~%cast_spell%~ END
		  END
// exempt lvl 1 if lv1 1 cantrips
          PATCH_IF (MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~62~) OR (MOD_IS_INSTALLED ~SubtleD_Spell_Tweaks.tp2~ ~62~) BEGIN	//	level 1 cantrips
		    PATCH_IF (%level% > 1) BEGIN
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5shm-%level%~ END
		    END
		  END
		  PATCH_IF !(MOD_IS_INSTALLED ~tomeandblood.tp2~ ~62~) AND !(MOD_IS_INSTALLED ~SubtleD_Spell_Tweaks.tp2~ ~62~) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5shm-%level%~ END
		  END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5yy172~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sham_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5yspld~ END
//		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5yspld~ END
          LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %fatigue_zero% timing = 1 STR_VAR resource = ~d5yyfat~ END
// make spells adding the innate spell
		COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/%give_spell%.spl~
          LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%innate_spell%~ END
// make 206 spells preventing the .EFF
	    COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/%block_spell%.spl~
		  WRITE_SHORT 0x1c 4
	  	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%give_spell%~ END
// add 206 spells to CLAB spell
	    COPY_EXISTING ~d5yy206.spl~ ~override~
	      LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = EVAL ~%block_spell%~ END
	      LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = EVAL ~%block_spell%~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%block_spell%~ END
	  	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%block_spell%~ END
// make learn spells canceling the 206
		COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/%learn_spell%.spl~
	  	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%block_spell%~ END
//		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%block_spell%~ END
// add 172 to yy172
	    COPY_EXISTING ~d5yy172.spl~ ~override~
		  LPF ADD_SPELL_EFFECT INT_VAR /*insert_point = 0*/ opcode = 172 target = 1 timing = 1 STR_VAR resource = EVAL ~%innate_spell%~ END
// learn from seq menu
		ACTION_IF (FILE_EXISTS_IN_GAME ~%cast_spell%%sorc_suffix%.spl~) BEGIN
		  COPY_EXISTING ~%cast_spell%%sorc_suffix%.spl~ ~override~
//		    LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%mem_spell%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sham_state% parameter2 = 110 timing = 1 duration = 0 STR_VAR resource = EVAL ~%learn_spell%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sham_state% parameter2 = 110 timing = 1 duration = 0 STR_VAR resource = ~d5yy172~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sham_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5yspld~ END
		END
// enable spell switching
	    ACTION_IF (FILE_EXISTS_IN_GAME ~%switch_spell%.spl~) BEGIN
		  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/%switch_subspell%.spl~
		    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = EVAL ~%learn_spell%~ END 
		    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%block_spell%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sham_state% parameter2 = 110 timing = 1 duration = 0 STR_VAR resource = ~d5yy172~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sham_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5yspld~ END
		  COPY_EXISTING ~%switch_spell%.spl~ ~override~
		    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_sham_state% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~%switch_subspell%~ END
		  BUT_ONLY
	    END
// remove all known spells after chargen
        COPY_EXISTING ~d5y0spl.spl~ ~override~
          LPF DELETE_EFFECT INT_VAR match_opcode = 172 STR_VAR match_resource = EVAL ~%cast_spell%~ END
          LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 1 STR_VAR resource = EVAL ~%cast_spell%~ END
        IF_EXISTS
// generate slot#x spells
		ACTION_IF (FILE_EXISTS_IN_GAME ~d5ydot%level%a.spl~) BEGIN
			COPY_EXISTING ~d5ydot%level%a.spl~ ~override~
		      LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
		END
		ACTION_IF (FILE_EXISTS_IN_GAME ~d5ydot%level%a.spl~) BEGIN
			COPY_EXISTING ~d5ydot%level%b.spl~ ~override~
		      LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
		END
		ACTION_IF (FILE_EXISTS_IN_GAME ~d5ydot%level%a.spl~) BEGIN
			COPY_EXISTING ~d5ydot%level%c.spl~ ~override~
		      LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
		END
		ACTION_IF (FILE_EXISTS_IN_GAME ~d5ydot%level%a.spl~) BEGIN
			COPY_EXISTING ~d5ydot%level%d.spl~ ~override~
		      LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
		END
      END
      SET_2DA_ENTRY row 4 cols ~yes~
    END
  END
BUT_ONLY

END		//	end with_tra


END		//	end define function


//__________________________________________________________________________________
//__________________________________________________________________________________

