
// v11.3

/*

functions in this file:

- semi_spontaneous_casting - line 
    sets up structure of the 5E casting system, covers both arcane and divine spells

- semi_divine_spells - line 
    adds all spells valid for divine casters to the 5E system
    NB: this works for vanilla cleric/druid spells, and for Faiths & Powers sphere systems
    ...therefore this should be run the first time *after* Faiths & Powers is installed

- semi_arcane_spells - line 
    adds all spells learnable from scrolls and valid for sorcerers to the 5E system
    NB: this also runs semi_armor_casting

- process_semi_spells - line 
    applies 5E memorization and casting mechanics to the relevant spells

- add_semi_spells - line 
    add a spell to the 5E system if it was not already captured by the functions above
    NB: even if 5E has already been processed, must "LAF process_semi_spells" again after this

- free_cast_spells - line 
    input a free_spell (can run multiple free_spells for the same list_spell)
    outputs a list_spell that makes the free_spells castable regardless of being memorized
    ...list-spell can then be applied in a kit ability table

- find_zclons_spell - line 
    input a spell that gets memorized, output its 5E index #, the spell it casts, and type
    ...just a little helper function

*/


INCLUDE ~%MOD_FOLDER%/lib/semi_spont/semi_misc_functions.tpa~


//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION semi_spontaneous_casting BEGIN


//find game install language__________________________________________________________
//
LAF set_lang RET game_lang END

WITH_TRA ~%MOD_FOLDER%/lib/semi_spont/%game_lang%/semi_spont.tra~ BEGIN


//semi spont spellstates______________________________________________________________
//
ACTION_IF (FILE_CONTAINS_EVALUATED (~splstate.ids~ ~D5_SEMI_ARCANE~)) BEGIN
  COPY_EXISTING ~splstate.ids~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 ~state_name~
	  READ_2DA_ENTRY_FORMER rows row 0 ~state_ind~
	  PATCH_IF (~%state_name%~ STRING_EQUAL_CASE ~D5_SEMI_ARCANE~) BEGIN
		SET semi_spont_arcane = %state_ind%
	  END
	END
  BUT_ONLY
END

ACTION_IF !(VARIABLE_IS_SET %semi_spont_arcane%) BEGIN
  LAF d5_resolve_state STR_VAR new_state_id = ~D5_SEMI_ARCANE~ RET new_state_ind END
  OUTER_SET semi_spont_arcane = %new_state_ind%
END

ACTION_IF (FILE_CONTAINS_EVALUATED (~splstate.ids~ ~D5_SEMI_DIVINE~)) BEGIN
  COPY_EXISTING ~splstate.ids~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 ~state_name~
	  READ_2DA_ENTRY_FORMER rows row 0 ~state_ind~
	  PATCH_IF (~%state_name%~ STRING_EQUAL_CASE ~D5_SEMI_DIVINE~) BEGIN
		SET semi_spont_divine = %state_ind%
	  END
	END
  BUT_ONLY
END

ACTION_IF !(VARIABLE_IS_SET %semi_spont_divine%) BEGIN
  LAF d5_resolve_state STR_VAR new_state_id = ~D5_SEMI_DIVINE~ RET new_state_ind END
  OUTER_SET semi_spont_divine = %new_state_ind%
END

ACTION_IF (FILE_CONTAINS_EVALUATED (~splstate.ids~ ~D5_SEMI_REST~)) BEGIN
  COPY_EXISTING ~splstate.ids~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 ~state_name~
	  READ_2DA_ENTRY_FORMER rows row 0 ~state_ind~
	  PATCH_IF (~%state_name%~ STRING_EQUAL_CASE ~D5_SEMI_REST~) BEGIN
		SET semi_spont_rest = %state_ind%
	  END
	END
  BUT_ONLY
END

ACTION_IF !(VARIABLE_IS_SET %semi_spont_rested%) BEGIN
  LAF d5_resolve_state STR_VAR new_state_id = ~D5_SEMI_REST~ RET new_state_ind END
  OUTER_SET semi_spont_rest = %new_state_ind%
END


//prepared spells spellstate__________________________________________________________
//
ACTION_IF (FILE_CONTAINS_EVALUATED (~splstate.ids~ ~D5_SPL_PREP~)) BEGIN
  COPY_EXISTING ~splstate.ids~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 ~state_name~
	  READ_2DA_ENTRY_FORMER rows row 0 ~state_ind~
	  PATCH_IF (~%state_name%~ STRING_EQUAL_CASE ~D5_SPL_PREP~) BEGIN
		SET prepared_spells_state = %state_ind%
	  END
	END
  BUT_ONLY
END

ACTION_IF !(VARIABLE_IS_SET %prepared_spells_state%) BEGIN
  LAF d5_resolve_state STR_VAR new_state_id = ~D5_SPL_PREP~ RET new_state_ind END
  OUTER_SET prepared_spells_state = %new_state_ind%
END


//add spell slot stat checks to SPLPROT______________________________________________
//
APPEND ~splprot.2da~ ~D5_WIZ_1_6%TAB%108%TAB%-1%TAB%7~ UNLESS ~D5_WIZ_1_6~
APPEND ~splprot.2da~ ~D5_WIZ=1_6%TAB%108%TAB%-1%TAB%8~ UNLESS ~D5_WIZ=1_6~
APPEND ~splprot.2da~ ~D5_SPL_7_9%TAB%109%TAB%-1%TAB%7~ UNLESS ~D5_SPL_7_9~
APPEND ~splprot.2da~ ~D5_SPL=7_9%TAB%109%TAB%-1%TAB%8~ UNLESS ~D5_SPL=7_9~
APPEND ~splprot.2da~ ~D5_DIV_1_6%TAB%134%TAB%-1%TAB%7~ UNLESS ~D5_DIV_1_6~
APPEND ~splprot.2da~ ~D5_DIV=1_6%TAB%134%TAB%-1%TAB%8~ UNLESS ~D5_DIV=1_6~
APPEND ~splprot.2da~ ~D5_FATIGUE_0%TAB%30%TAB%0%TAB%1~ UNLESS ~D5_FATIGUE_0~
APPEND ~splprot.2da~ ~D5_FATIGUE_1%TAB%30%TAB%1%TAB%4~ UNLESS ~D5_FATIGUE_1~
APPEND ~splprot.2da~ ~D5_FATIGUE_3%TAB%30%TAB%3%TAB%4~ UNLESS ~D5_FATIGUE_3~
APPEND ~splprot.2da~ ~D5_PREP_SPLZ%TAB%0x112%TAB%%prepared_spells_state%%TAB%1~ UNLESS ~D5_PREP_SPLZ~
APPEND ~splprot.2da~ ~D5_NOT_PREP%TAB%0x112%TAB%%prepared_spells_state%%TAB%5~ UNLESS ~D5_NOT_PREP~
APPEND ~splprot.2da~ ~D5_KIT_IS%TAB%152%TAB%-1%TAB%1~ UNLESS ~D5_KIT_IS~

COPY_EXISTING ~splprot.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW rows cols
  FOR (row = 1; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 0 ~stat~
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_WIZ_1_6~) BEGIN
	  SET fake_sorc_slots_1_6 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_WIZ=1_6~) BEGIN
	  SET fake_sorc_equal_1_6 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_SPL_7_9~) BEGIN
	  SET fake_spel_slots_7_9 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_SPL=7_9~) BEGIN
	  SET fake_spel_equal_7_9 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_DIV_1_6~) BEGIN
	  SET fake_sham_slots_1_6 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_DIV=1_6~) BEGIN
	  SET fake_sham_equal_1_6 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_FATIGUE_0~) BEGIN
	  SET fatigue_zero = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_FATIGUE_1~) BEGIN
	  SET fatigue_one = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_FATIGUE_3~) BEGIN
	  SET fatigue_three = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_PREP_SPLZ~) BEGIN
	  SET prep_spells_row = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_NOT_PREP~) BEGIN
	  SET not_prep_row = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_KIT_IS~ BEGIN
	  SET kit_is_row = %row%
	END
  END
BUT_ONLY


//disable quickspell buttons__________________________________________________________
//
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5znoqk.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5znoqk.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 3 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 4 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 5 timing = 9 END
END


//remove spell slots pending sleep_____________________________________________________
//
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5z17wz.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5z17wz.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5z89wz.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5z89wz.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 target = 1 parameter1 = (0 - 1) parameter2 = 384 timing = 9 END
END

// this is for... what? 
// to eliminate kitted mage bonus slots
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5z0slt.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5z0slt.spl~ 
  PATCH_IF (MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~62~) OR (MOD_IS_INSTALLED ~SubtleD_Spell_Tweaks.tp2~ ~62~) BEGIN	//	level 1 cantrips
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 target = 1 parameter1 = (0 - 1) parameter2 = 510 /*126*/ timing = 9 END // cover all lvls 2-9 spls
  END
  PATCH_IF !(MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~62~) AND !(MOD_IS_INSTALLED ~SubtleD_Spell_Tweaks.tp2~ ~62~) BEGIN	//	level 1 cantrips
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 target = 1 parameter1 = (0 - 1) parameter2 = 511 /*127*/ timing = 9 END // cover all lvls 1-9 spls
  END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5z0slt~ END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 0 parameter2 = %kit_is_row% timing = 0 duration = 1 STR_VAR resource = ~d5z0slt~ END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 16384 parameter2 = %kit_is_row% timing = 0 duration = 1  STR_VAR resource = ~d5z0slt~ END
END

/* I think this is only applied once, no need for 2nd copy
COPY_EXISTING ~d5z0slt.spl~ ~override/d5z1slt.spl~
  LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = ~d500slt~ resource = ~d501slt~ END
*/

// what is this one vv for...?  L1Cantrips
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5z2slt.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5z2slt.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 2 target = 1 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5z2slt~ END
END

// here are spells for use with TnB/SoB abil score bonus slots
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zislt.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zislt.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5zislt~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zjslt.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zjslt.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5zjslt~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5z17dv.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5z17dv.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
END


ACTION_IF !(FILE_EXISTS_IN_GAME ~d5__semi_spont.d5~) BEGIN


//create advance copies of some spells________________________________________________
//
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zz206.spl~

COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zz172.spl~

COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zz145.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 145 target = 1 parameter2 = 0 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 145 target = 1 parameter2 = 1 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5zspld~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5zspla~ END

COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5z0spl.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~SPWI908~ END
  PATCH_IF !(FILE_EXISTS_IN_GAME ~d5__new_identify.d5~) BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~SPWI110~ END
  END
  PATCH_IF !(MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~55~) BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~SPWI420~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~SPWI710~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~SPWI809~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~SPWI617~ END
  END

COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot1a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot1b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot1c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot1d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot2a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot2b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot2c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot2d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot3a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot3b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot3c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot3d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot4a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot4b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot4c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot4d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot5a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot5b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot5c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot5d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot6a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot6b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot6c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot6d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot7a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot7b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot7c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot7d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot8a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot8b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot8c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot8d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot9a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot9b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot9c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zwot9d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot1a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot1b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot1c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot1d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot2a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot2b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot2c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot2d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot3a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot3b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot3c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot3d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot4a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot4b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot4c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot4d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot5a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot5b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot5c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot5d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot6a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot6b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot6c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot6d.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot7a.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot7b.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot7c.spl~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zdot7d.spl~

COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zspld.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 8) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot1a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 8) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot1b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 8) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot1c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 8) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot1d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 12) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot2a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 12) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot2b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 12) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot2c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 12) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot2d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 16) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot3a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 16) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot3b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 16) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot3c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 16) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot3d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 20) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot4a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 20) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot4b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 20) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot4c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 20) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot4d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 24) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot5a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 24) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot5b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 24) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot5c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 24) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot5d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 28) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot6a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 28) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot6b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 28) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot6c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 28) parameter2 = %fake_sham_slots_1_6% timing = 1 STR_VAR resource = ~d5zdot6d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 16) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5zdot7a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 16) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5zdot7b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 16) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5zdot7c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 16) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5zdot7d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5zspld~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 318 insert_point = 0 target = 1 parameter1 = %semi_spont_divine% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = ~d5zspld~ END

COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zspla.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 8) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot1a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 8) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot1b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 8) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot1c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 8) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot1d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 12) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot2a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 12) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot2b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 12) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot2c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 12) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot2d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 16) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot3a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 16) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot3b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 16) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot3c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 16) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot3d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 20) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot4a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 20) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot4b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 20) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot4c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 20) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot4d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 24) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot5a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 24) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot5b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 24) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot5c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 24) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot5d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 28) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot6a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 28) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot6b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 28) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot6c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 28) parameter2 = %fake_sorc_slots_1_6% timing = 1 STR_VAR resource = ~d5zwot6d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 20) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5zwot7a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 20) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5zwot7b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 20) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5zwot7c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 20) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5zwot7d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 24) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5zwot8a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 24) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5zwot8b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 24) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5zwot8c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 24) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5zwot8d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 28) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5zwot9a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 28) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5zwot9b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 28) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5zwot9c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 28) parameter2 = %fake_spel_slots_7_9% timing = 1 STR_VAR resource = ~d5zwot9d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5zspla~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 318 insert_point = 0 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = ~d5zspla~ END

//assign stats for spell slots to each spell level____________________________________
//
// arcane level 1 = 	108 << 8
// arcane level 2 = 	108 << 12
// arcane level 3 = 	108 << 16
// arcane level 4 = 	108 << 20
// arcane level 5 = 	108 << 24
// arcane level 6 = 	108 << 28
// arcane level 7 = 	109 << 20
// arcane level 8 = 	109 << 24
// arcane level 9 = 	109 << 28
// divine level 1 = 	134 << 8
// divine level 2 = 	134 << 12
// divine level 3 = 	134 << 16
// divine level 4 = 	134 << 20
// divine level 5 = 	134 << 24
// divine level 6 = 	134 << 28
// divine level 7 = 	109 << 16
//

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src1a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src1%let%.spl~
	  SAY NAME1 @101
	  SAY UNIDENTIFIED_DESC @101
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 8) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src2a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src2%let%.spl~
	  SAY NAME1 @102
	  SAY UNIDENTIFIED_DESC @102
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 12) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src3a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src3%let%.spl~
	  SAY NAME1 @103
	  SAY UNIDENTIFIED_DESC @103
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src4a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src4%let%.spl~
	  SAY NAME1 @104
	  SAY UNIDENTIFIED_DESC @104
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 20) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src5a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src5%let%.spl~
	  SAY NAME1 @105
	  SAY UNIDENTIFIED_DESC @105
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 24) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src6a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src6%let%.spl~
	  SAY NAME1 @106
	  SAY UNIDENTIFIED_DESC @106
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 28) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src7a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src7%let%.spl~
	  SAY NAME1 @107
	  SAY UNIDENTIFIED_DESC @107
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 20) parameter2 = (109 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src8a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src8%let%.spl~
	  SAY NAME1 @108
	  SAY UNIDENTIFIED_DESC @108
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 24) parameter2 = (109 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src9a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src9%let%.spl~
	  SAY NAME1 @109
	  SAY UNIDENTIFIED_DESC @109
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 28) parameter2 = (109 + (0x10000 * 1)) timing = 9 END
  END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm1a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm1%let%.spl~
	  SAY NAME1 @101
	  SAY UNIDENTIFIED_DESC @101
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 8) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm2a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm2%let%.spl~
	  SAY NAME1 @102
	  SAY UNIDENTIFIED_DESC @102
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 12) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm3a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm3%let%.spl~
	  SAY NAME1 @103
	  SAY UNIDENTIFIED_DESC @103
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm4a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm4%let%.spl~
	  SAY NAME1 @104
	  SAY UNIDENTIFIED_DESC@104
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 20) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm5a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm5%let%.spl~
	  SAY NAME1 @105
	  SAY UNIDENTIFIED_DESC @105
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 24) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm6a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm6%let%.spl~
	  SAY NAME1 @106
	  SAY UNIDENTIFIED_DESC @106
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 28) parameter2 = (134 + (0x10000 * 1)) timing = 9 END
  END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm7a.spl~) BEGIN
  ACTION_FOR_EACH let IN ~a~ ~z~ BEGIN
	COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm7%let%.spl~
	  SAY NAME1 @107
	  SAY UNIDENTIFIED_DESC @107
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (109 + (0x10000 * 1)) timing = 9 END
  END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src-1.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src-1.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src-2.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src-2.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src-3.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src-3.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src-4.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src-4.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src-5.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src-5.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 24) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src-6.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src-6.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 28) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src-7.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src-7.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src-8.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src-8.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 24) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5src-9.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5src-9.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 28) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm-1.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm-1.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm-2.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm-2.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm-3.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm-3.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm-4.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm-4.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm-5.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm-5.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 24) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm-6.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm-6.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 28) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5shm-7.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5shm-7.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END


//quickly address wondrous recall_____________________________________________________
//

ACTION_IF (MOD_IS_INSTALLED ~d5_random_tweaks.tp2~ ~1611~) BEGIN
  COPY_EXISTING ~sppr611.spl~ ~override~
    LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = ~d5shm-1~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = ~d5shm-2~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = ~d5src-1~ END
    LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = ~d5src-2~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-1~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-2~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-1~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-2~ END
  BUT_ONLY
  ACTION_IF (FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~) BEGIN
    ACTION_IF (FILE_EXISTS_IN_GAME ~potn43.spl~) BEGIN
//	  COPY_EXISTING ~sppr611.spl~ ~override/potn43.spl~
	  COPY_EXISTING ~potn43.spl~ ~override~
        LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = ~d5shm-1~ END
        LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = ~d5shm-2~ END
        LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = ~d5src-1~ END
        LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = ~d5src-2~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-1~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-2~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-1~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-2~ END
	  IF_EXISTS BUT_ONLY
    END
  END
END


//prepare prepare spells spell________________________________________________________
//
OUTER_SET prep_message = RESOLVE_STR_REF(@203)
COPY ~%MOD_FOLDER%/lib/semi_spont/d5zwtch.bam~ ~override~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5zprep.bam~ ~override~
COPY ~%MOD_FOLDER%/lib/semi_spont/d5zgren.bam~ ~override~

COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zprp.spl~
  SAY NAME1 @201
  SAY UNIDENTIFIED_DESC @202
  WRITE_ASCII 0x3a ~d5zgren~ #8
  LPF ALTER_SPELL_HEADER INT_VAR target = 7 STR_VAR icon = ~d5zgren~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 1 parameter2 = 0 timing = 1 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_rest% parameter2 = 110 timing = 1 duration = 0 STR_VAR resource = ~d5xrest~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5z17wz~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5z89wz~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5z17dv~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = ~d5zz145~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = ~d5zz206~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = ~d5zprp1~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 139 target = 1 parameter1 = %prep_message% timing = 1 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 111 timing = 1 STR_VAR resource = ~d5zz010~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 111 timing = 1 STR_VAR resource = ~d5zz020~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5zz172~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 1 STR_VAR resource = ~d5zprp~ END

COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zprp0.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5zprp~ END

COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zprp1.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 328 target = 1 special = 1 parameter2 = %prepared_spells_state% timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 126144000 STR_VAR resource = ~d5zarmr~ END


//daily spell slot refresh____________________________________________________________
//
COPY ~%MOD_FOLDER%/lib/semi_spont/d5zcast.bam~ ~override~

COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zlotz.spl~
  SAY NAME1 @100
  SAY UNIDENTIFIED_DESC @100
  LPF ALTER_SPELL_HEADER INT_VAR target = 7 STR_VAR icon = ~d5zcast~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~d5zlots~ END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zlots.eff~) BEGIN
  CREATE EFF ~d5zlots~
	WRITE_LONG 0x10 232
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 0
	WRITE_LONG 0x20 20
	WRITE_LONG 0x24 9
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~d5zlots~ #8
	WRITE_LONG 0x48 102
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zlots.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zlots.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 111 timing = 1 STR_VAR resource = ~d5zz001~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %fatigue_zero% timing = 1 STR_VAR resource = ~d5zlotf~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %fatigue_one% timing = 1 STR_VAR resource = ~d5xrest~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zlotf.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zlotf.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %prep_spells_row% timing = 1 STR_VAR resource = ~d5zlotr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %not_prep_row% timing = 1 STR_VAR resource = ~d5zrfsh~ END
    LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %semi_spont_rest% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = ~d5zlotf~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zlotr.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zlotr.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 0 duration = 12 STR_VAR resource = ~d5zlotr~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 316 target = 1 timing = 1 END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zlotr.eff~) BEGIN
  CREATE EFF ~d5zlotr~
	WRITE_LONG 0x10 67
	WRITE_LONG 0x14 1
	WRITE_LONG 0x28 12
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~d5zlotr~ #8
	WRITE_ASCII 0x70 ~shskull~ #8
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zlotr.cre~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5zlotr.cre~ ~override~
	WRITE_ASCII 0x248 ~D5ZLOTR~ #8
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zrest.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zrest.spl~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 328 target = 1 special = 1 parameter2 = %semi_spont_rest% timing = 9 END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5xrest.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5xrest.spl~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5zrest~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zzfat.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zzfat.spl~
    LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 1 parameter2 = 1 timing = 4 duration = 6 END
END


// spell to simply refresh spell slots________________________________________________
//
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zrfsh.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zrfsh.spl~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_rest% parameter2 = 111 timing = 1 duration = 0 STR_VAR resource = ~d5zrest~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5zz145~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src-1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src-2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src-3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src-4~ END
  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src-5~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src-6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src-7~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src-8~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src-9~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm-1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm-2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm-3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm-4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm-5~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm-6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm-7~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src1z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src2z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src3z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src4z~ END
  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src5z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src6z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src7z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src8z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src9z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm1z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm2z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm3z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm4z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm5z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm6z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm7z~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5zz172~ END
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5zsplz~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5zspld~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5zspla~ END
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5zspld~ END
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5zspla~ END
END


END		//	end marker file check


// spell to set prepped spells and then refresh slots_________________________________
//
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zprpd.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zprpd.spl~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_rest% parameter2 = 111 timing = 1 duration = 0 STR_VAR resource = ~d5zrest~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z89wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z89wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z89wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z89wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z89wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z89wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z89wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z89wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z89wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z89wz~ END
	 LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5zprp1~ END
//    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5zz145~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-4~ END
  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-5~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-7~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-8~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-9~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-5~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5shm-7~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src1z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src2z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src3z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src4z~ END
  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src5z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src6z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src7z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src8z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5src9z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm1z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm2z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm3z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm4z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm5z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm6z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5shm7z~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 279 target = 1 parameter2 = 2 timing = 9 END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 4 duration = 6 STR_VAR resource = ~d5zprp~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5zz172~ END
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5zsplz~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5zspld~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 4 duration = 1  STR_VAR resource = ~d5zspla~ END
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5zspld~ END
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5zspla~ END
END

/*
ACTION_IF (FILE_EXISTS_IN_GAME ~d5zprpd.spl~) BEGIN
  COPY_EXISTING ~d5zprpd.spl~ ~override~
    PATCH_IF (include_arcane = 1) BEGIN
     LPF DELETE_EFFECT INT_VAR match_opcode = 326 STR_VAR match_resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z89wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z89wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z89wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z89wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z89wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z89wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z89wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z89wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z89wz~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z89wz~ END
    END
    PATCH_IF (include_divine = 1) BEGIN
     LPF DELETE_EFFECT INT_VAR match_opcode = 326 STR_VAR match_resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
     LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 1 STR_VAR resource = ~d5z17dv~ END
    END
END
*/


// 5E system initialization___________________________________________________________
//
/*
ACTION_IF (FILE_EXISTS_IN_GAME ~qdtnb_mcsrc.qd~) BEGIN
 COPY_EXISTING ~kit.ids~ ~override~
  COUNT_2DA_COLS cols 
  READ_2DA_ENTRIES_NOW rows cols 
  FOR (row = 1; row < rows; ++row) BEGIN 
    READ_2DA_ENTRY_FORMER rows row 1 ~kit_name~ 
    PATCH_IF ~%kit_name%~ STRING_EQUAL_CASE ~D5_FIGHTER_SORCERER~ BEGIN
      SET fighter_sorcerer_row = %row%
      READ_2DA_ENTRY_FORMER rows fighter_sorcerer_row 0 fighter_sorcerer_code
    END
    PATCH_IF ~%kit_name%~ STRING_EQUAL_CASE ~D5_SORCERER_CLERIC~ BEGIN
      SET sorcerer_cleric_row = %row%
      READ_2DA_ENTRY_FORMER rows sorcerer_cleric_row 0 sorcerer_cleric_code
    END
    PATCH_IF ~%kit_name%~ STRING_EQUAL_CASE ~D5_SORCERER_THIEF~ BEGIN
      SET sorcerer_thief_row = %row%
      READ_2DA_ENTRY_FORMER rows sorcerer_thief_row 0 sorcerer_thief_code
    END
  END
 BUT_ONLY
END
*/

// put this zz000 in the clab tables
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zz000.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zz000.spl~
    SAY NAME1 @100
    SAY UNIDENTIFIED_DESC @100
    LPF ALTER_SPELL_HEADER INT_VAR target = 7 STR_VAR icon = ~d5zcast~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 1 parameter2 = 1 timing = 1 END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5zlotz~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~d5zlots~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5xxini~ END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5zz000~ END
    LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 19 parameter2 = 105 timing = 9 STR_VAR resource = ~d5zz000~ END
    LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 2 parameter2 = 112 timing = 9 STR_VAR resource = ~d5zz000~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zz001.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zz001.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 111 timing = 1 STR_VAR resource = ~d5zzini~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zzini.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zzini.spl~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 1 parameter2 = 105 timing = 1 STR_VAR resource = ~d5z0slt~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5zz206~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5znoqk~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 111 timing = 1 STR_VAR resource = ~d5zz010~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 111 timing = 1 STR_VAR resource = ~d5zz020~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5zncast~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5zprp~ END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 1 parameter2 = 0 timing = 1 END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 6 STR_VAR resource = ~d5zlotr~ END
// 	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5zzini~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zz010.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zz010.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 3 parameter2 = 105 timing = 1 STR_VAR resource = ~d5zsttd~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = 105 timing = 1 STR_VAR resource = ~d5zsttd~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 8 parameter2 = 105 timing = 1 STR_VAR resource = ~d5zsttd~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 11 parameter2 = 105 timing = 1 STR_VAR resource = ~d5zsttd~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 12 parameter2 = 105 timing = 1 STR_VAR resource = ~d5zsttd~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 14 parameter2 = 105 timing = 1 STR_VAR resource = ~d5zsttd~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 15 parameter2 = 105 timing = 1 STR_VAR resource = ~d5zsttd~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 16 parameter2 = 105 timing = 1 STR_VAR resource = ~d5zsttd~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 17 parameter2 = 105 timing = 1 STR_VAR resource = ~d5zsttd~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 18 parameter2 = 105 timing = 1 STR_VAR resource = ~d5zsttd~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zz020.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zz020.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 1 parameter2 = 105 timing = 1 STR_VAR resource = ~d5zstta~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = 105 timing = 1 STR_VAR resource = ~d5zstta~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 7 parameter2 = 105 timing = 1 STR_VAR resource = ~d5zstta~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = 105 timing = 1 STR_VAR resource = ~d5zstta~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 13 parameter2 = 105 timing = 1 STR_VAR resource = ~d5zstta~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 14 parameter2 = 105 timing = 1 STR_VAR resource = ~d5zstta~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 17 parameter2 = 105 timing = 1 STR_VAR resource = ~d5zstta~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zsttd.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zsttd.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 328 target = 1 special = 1 parameter2 = %semi_spont_divine% timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = ~d5zsttd~ END
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zstta.spl~) BEGIN
 COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zstta.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 328 target = 1 special = 1 parameter2 = %semi_spont_arcane% timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = ~d5zstta~ END
END


// generate zclons.2da________________________________________________________________
//
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zclons.2da~) BEGIN

<<<<<<<< d5/d5zclons.2da
2DA V1.0 
IND
		MEM 		CAST 		TYPE 	PROCESSED
100		#			#			#		#
>>>>>>>> 

  COPY ~d5/d5zclons.2da~ ~override/d5zclons.2da~ 

END

// 206/blocking spell = d5zb[ind]
// 171/granting .eff  = d5zg[ind]
// 321/learning spell = d5zl[ind]
// 146/innate spell   = d5zi[ind]


//remove wiz bonus slots______________________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5absp1.spl~) BEGIN
  COPY_EXISTING ~d5absp1.spl~ ~override~
    LPF DELETE_EFFECT INT_VAR match_opcode = 177 STR_VAR match_resource = ~d5abspw~ END
  BUT_ONLY
END

ACTION_IF (FILE_EXISTS_IN_GAME ~d5abspw.spl~) BEGIN
  COPY_EXISTING ~d5abspw.spl~ ~override~
    LPF DELETE_EFFECT END
  BUT_ONLY
END

//fix burning hands targeting_______________________________________________________
//
COPY_EXISTING ~spwi103.spl~ ~override~
  READ_LONG 0x50 burning_hands_strref
BUT_ONLY

ACTION_IF (IS_AN_INT %burning_hands_strref%) BEGIN
  COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
	PATCH_IF (%SOURCE_SIZE% > 0x71) BEGIN
	  SET burning_change = 0
	  READ_LONG 0x50 desc
	  PATCH_IF (desc = burning_hands_strref) BEGIN
		GET_OFFSET_ARRAY ab_array SPL_V10_HEADERS
		PHP_EACH ab_array AS int => ab_off BEGIN
		  PATCH_IF (burning_change = 0) BEGIN
			READ_BYTE (ab_off + 0x0c) target
			PATCH_IF target = 5 BEGIN
			  SET burning_change = 1
			END
		  END
		END
		PATCH_IF (burning_change = 1) BEGIN
		  LPF ALTER_SPELL_HEADER INT_VAR target = 1 END
		  LPF ALTER_EFFECT INT_VAR match_opcode = 148 opcode = 146 target = 2 STR_VAR match_resource = ~spwi103~ END
		  WRITE_BYTE 0x1b (THIS BOR 1)
		END
	  END
	END
  BUT_ONLY
END


//fix black pits 2___________________________________________________________________
//
COPY_EXISTING ~ohbantim.spl~ override
  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 144 match_parameter2 = 13 opcode = 145 parameter2 = 3 END
IF_EXISTS BUT_ONLY

// change BP1 to allow innates too
// EDIT - don't need to!

//____________________________________________________________________________________


//fix external fatigue effects________________________________________________________
//
CREATE EFF ~d5zifat9~
	WRITE_LONG 0x10 232
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 0
	WRITE_LONG 0x20 20
	WRITE_LONG 0x24 9
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~d5zifat~ #8
	WRITE_LONG 0x48 102

CREATE EFF ~d5zifat2~
	WRITE_LONG 0x10 232
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 0
	WRITE_LONG 0x20 20
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~d5zifat~ #8
	WRITE_LONG 0x48 102


COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zifat.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 2 parameter2 = 1 timing = 1 END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5zifat~ END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter2 = %fatigue_three% timing = 0 duration = 1 STR_VAR resource = ~d5zifat~ END

 
ACTION_FOR_EACH fatigue_spell IN ~spcl939~ ~cdidrif~ BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%fatigue_spell%.spl~) BEGIN
    COPY_EXISTING ~%fatigue_spell%.spl~ ~override~
      LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 93 match_parameter1 = 0 match_paramater2 = 1 parameter1 = 2 END
      LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 101 match_parameter2 = 93 match_timing = 9 opcode = 177 parameter1 = 0 parameter2 = 2 STR_VAR resource = ~d5zifat9~ END
    BUT_ONLY
  END
END

ACTION_FOR_EACH fatigue_item IN ~bdamul12~ BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%fatigue_item%.itm~) BEGIN
    COPY_EXISTING ~%fatigue_item%.itm~ ~override~
      LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 93 match_parameter1 = 0 match_paramater2 = 1 parameter1 = 2 END
      LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 101 match_parameter2 = 93 match_timing = 2 opcode = 177 parameter1 = 0 parameter2 = 2 STR_VAR resource = ~d5zifat2~ END
    BUT_ONLY
  END
END

OUTER_SET spell_ids = IDS_OF_SYMBOL (~spell~ ~CLERIC_UNFAILING_ENDURANCE~)
ACTION_IF !(spell_ids = 0 - 1) BEGIN
  LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~CLERIC_UNFAILING_ENDURANCE~ RET spell_res END
  COPY_EXISTING ~%spell_res%.spl~ ~override~
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 93 match_parameter1 = 0 match_paramater2 = 1 parameter1 = 1 END
  BUT_ONLY
END 

//____________________________________________________________________________________


COPY ~%MOD_FOLDER%/lib/semi_spont/d5_marker.d5~ ~override/d5__semi_spont.d5~


/*
ACTION_IF (FILE_EXISTS_IN_GAME ~d5zzini.spl~) BEGIN
  COPY_EXISTING ~d5zzini.spl~ ~override~
	PATCH_IF (include_divine = 1) BEGIN
	  LPF DELETE_EFFECT INT_VAR match_opcode = 326 match_parameter1 = %semi_spont_divine% match_parameter2 = 111 STR_VAR match_resource = ~d5zz010~ END
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 5 opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 111 timing = 1 STR_VAR resource = ~d5zz010~ END
	END
	PATCH_IF (include_arcane = 1) BEGIN
	  LPF DELETE_EFFECT INT_VAR match_opcode = 326 match_parameter1 = %semi_spont_arcane% match_parameter2 = 111 STR_VAR match_resource = ~d5zz020~ END
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 5 opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 111 timing = 1 STR_VAR resource = ~d5zz020~ END
	END
END
*/

END		//	end with_tra

/*
LAF semi_armor_casting END

ACTION_IF (include_divine = 1) BEGIN
  LAF semi_divine_spells END
END

ACTION_IF (include_arcane = 1) BEGIN
  LAF semi_arcane_spells END
END

LAF process_semi_spells END
*/

END		//	end define function


//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION semi_divine_spells BEGIN


//find game install language__________________________________________________________
//
LAF set_lang RET game_lang END

WITH_TRA ~%MOD_FOLDER%/lib/semi_spont/%game_lang%/semi_spont.tra~ BEGIN

ACTION_IF (FILE_EXISTS_IN_GAME ~d5zclons.2da~) BEGIN

  OUTER_SET high_ind = 99
  COPY_EXISTING ~d5zclons.2da~ ~override~
    COUNT_2DA_COLS cols
    READ_2DA_ENTRIES_NOW ~r2en_zclons~ cols
    FOR (row = 0; row < r2en_zclons; ++row) BEGIN
      READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 0 this_ind
      PATCH_IF (this_ind > high_ind) BEGIN
        SET high_ind = this_ind
      END
    END
  BUT_ONLY

  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5__spheres.d5~) BEGIN
    COPY_EXISTING_REGEXP ~^[Ss][Pp][Pp][Rr][1-7]\([0-4][0-9]\|50\)\.spl$~ ~override~
		SET spl_ind = 0
        INNER_ACTION BEGIN
		  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5zclons.2da~ ~%SOURCE_RES%~)) BEGIN
		    COPY_EXISTING ~d5zclons.2da~ ~override~
		      COUNT_2DA_COLS cols
	          READ_2DA_ENTRIES_NOW ~r2en_zclons~ cols
	          FOR (row = 0; row < r2en_zclons; ++row) BEGIN
	            READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 0 prev_ind
	            READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 2 cast_spell
	            PATCH_IF (~%SOURCE_RES%~ STRING_EQUAL_CASE ~%cast_spell%~) BEGIN
	              SET spl_ind = prev_ind
	            END 
	          END
	        BUT_ONLY
	      END
	      ACTION_IF (spl_ind = 0) BEGIN
	        OUTER_SET high_ind = high_ind + 1
		    OUTER_SET spl_ind = high_ind
		  END
          APPEND ~d5zclons.2da~ ~%spl_ind% 	%SOURCE_RES% 	%SOURCE_RES% 	divine 	no ~ UNLESS ~%SOURCE_RES% 	%SOURCE_RES%~
        END
    BUT_ONLY
  END	//	end no FnP

  ACTION_IF (FILE_EXISTS_IN_GAME ~d5fnplst.2da~) BEGIN
    COPY_EXISTING ~d5fnplst.2da~ ~override~
      COUNT_2DA_COLS cols
      READ_2DA_ENTRIES_NOW ~r2en_fnplst~ cols
      FOR (row = 0; row < r2en_fnplst; ++row) BEGIN
        READ_2DA_ENTRY_FORMER ~r2en_fnplst~ row 0 real_spl
        READ_2DA_ENTRY_FORMER ~r2en_fnplst~ row 1 major_spl
        READ_2DA_ENTRY_FORMER ~r2en_fnplst~ row 2 minor_spl
        READ_2DA_ENTRY_FORMER ~r2en_fnplst~ row 3 focus_spl
        SPRINT $fnp_sphere_spells(~%real_spl%~ ~%major_spl%~ ~%minor_spl%~)~%focus_spl%~
      END
    BUT_ONLY    
    ACTION_PHP_EACH fnp_sphere_spells AS res => foc BEGIN
      OUTER_SET spl_ind = 0
	  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5zclons.2da~ ~%real_spell%~)) BEGIN
	    COPY_EXISTING ~d5zclons.2da~ ~override~
	      COUNT_2DA_COLS cols
	      READ_2DA_ENTRIES_NOW ~r2en_zclons~ cols
	      READ_2DA_ENTRY (r2en_zclons - 1) 0 cols last_ind
	      FOR (row = 0; row < r2en_zclons; ++row) BEGIN
	        READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 0 prev_ind
	        READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 0 mem_spell
	        READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 2 cast_spell
	        PATCH_IF (~%res%~ STRING_EQUAL_CASE ~%mem_spell%~) BEGIN
	          SET spl_ind = prev_ind
	        END 
	      END
	    BUT_ONLY
	  END
      ACTION_IF (spl_ind = 0) BEGIN
        OUTER_SET high_ind = high_ind + 1
	    OUTER_SET spl_ind = high_ind
	  END
      APPEND ~d5zclons.2da~ ~%spl_ind% 	%res_1%	%res% 	divine 	no ~ UNLESS ~%res_1%~
      ACTION_IF !(~%res_2%~ STRING_EQUAL_CASE ~%res_1%~) BEGIN
        ACTION_IF !(~%res_2%~ STRING_EQUAL_CASE ~****~) BEGIN
          APPEND ~d5zclons.2da~ ~%spl_ind% 	%res_2% 	%res% 	divine 	no ~ UNLESS ~%res_2%~
        END
      END    
    END

  END	//	end FnP
  
  COPY_EXISTING ~kitlist.2da~ ~override~
    READ_2DA_ENTRIES_NOW ~r2en_kitlist~ 10
    FOR (row = 2; row < r2en_kitlist; row += 1) BEGIN
      READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 5 kit_clab
      SPRINT $clabs_to_check(~%kit_clab%~)~1~
    END
  BUT_ONLY
 
  ACTION_PHP_EACH clabs_to_check AS clab => ind BEGIN
    ACTION_IF (FILE_EXISTS_IN_GAME ~%clab%.2da~) BEGIN
      COPY_EXISTING ~%clab%.2da~ ~override~
        LPF 2DA_MISSING_COLS STR_VAR entry = ~****~ END 
      BUT_ONLY
      COPY_EXISTING ~%clab%.2da~ ~override~
        COUNT_2DA_COLS cols
        READ_2DA_ENTRIES_NOW r2en_clab cols
        FOR (col = 1; col < cols; ++col) BEGIN
          FOR (row = 0; row < r2en_clab; ++row) BEGIN
            READ_2DA_ENTRY_FORMER r2en_clab row col kit_abil
            PATCH_IF (~%kit_abil%~ STRING_CONTAINS_REGEXP ~GA_~) = 0 BEGIN
              SPRINT $ga_abils(~%kit_abil%~)~1~
            END
          END
        END
      BUT_ONLY
    END
  END

  ACTION_PHP_EACH ga_abils AS abil => ind BEGIN
    OUTER_INNER_PATCH_SAVE abil ~%abil%~ BEGIN
      REPLACE_TEXTUALLY ~GA_~ ~~
    END
    ACTION_IF (FILE_EXISTS_IN_GAME ~%abil%.spl~) BEGIN
      COPY_EXISTING ~%abil%.spl~ ~override~
        READ_BYTE 0x1c spl_type
        PATCH_IF (spl_type = 2) BEGIN			//	if a priest spell
          PATCH_IF !(FILE_CONTAINS_EVALUATED (~d5zclons.2da~ ~%abil%~)) BEGIN
            INNER_ACTION BEGIN
	          OUTER_SET high_ind = high_ind + 1
		      OUTER_SET spl_ind = high_ind
              APPEND ~d5zclons.2da~ ~%spl_ind% 	%abil% 	%abil% 	divine 	no ~ UNLESS ~%abil%~
            END
          END
        END
      BUT_ONLY
    END
  END
  
  ACTION_FOR_EACH num IN ~1~ ~2~ ~3~ ~4~ ~5~ ~6~ ~7~ BEGIN
    ACTION_IF (FILE_EXISTS_IN_GAME ~mepr%num%.txt~) BEGIN
      COPY_EXISTING ~mepr%num%.txt~ ~override~
        COUNT_2DA_ROWS 1 rows
        FOR (row = 0; row < rows; ++row) BEGIN
          READ_2DA_ENTRY row 0 1 me_spl
          PATCH_IF (FILE_EXISTS_IN_GAME ~%me_spl%.spl~) BEGIN
            PATCH_IF !(FILE_CONTAINS_EVALUATED (~d5zclons.2da~ ~%me_spl%~)) BEGIN
              INNER_ACTION BEGIN
	            OUTER_SET high_ind = high_ind + 1
		        OUTER_SET spl_ind = high_ind
                APPEND ~d5zclons.2da~ ~%spl_ind% 	%me_spl% 	%me_spl% 	divine 	no ~ UNLESS ~%me_spl%~
              END             
            END
          END
        END
    END
  END

  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_marker.d5~ ~override/d5__5E_casting_divine.d5~

END 

END		//	end with_tra

END // end function


//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION semi_arcane_spells BEGIN


//find game install language__________________________________________________________
//
LAF set_lang RET game_lang END

WITH_TRA ~%MOD_FOLDER%/lib/semi_spont/%game_lang%/semi_spont.tra~ BEGIN

ACTION_IF (FILE_EXISTS_IN_GAME ~d5zclons.2da~) BEGIN

  OUTER_SET high_ind = 99
  COPY_EXISTING ~d5zclons.2da~ ~override~
    COUNT_2DA_COLS cols
    READ_2DA_ENTRIES_NOW ~r2en_zclons~ cols
    FOR (row = 0; row < r2en_zclons; ++row) BEGIN
      READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 0 this_ind
      PATCH_IF (this_ind > high_ind) BEGIN
        SET high_ind = this_ind
      END
    END
  BUT_ONLY

  COPY_EXISTING ~d5zclons.2da~ ~override~
    COUNT_2DA_COLS cols
    COUNT_2DA_ROWS cols rows
    READ_2DA_ENTRY (rows - 1) 0 cols last_ind
  BUT_ONLY

  OUTER_SET scroll_spell_ind = 0
  OUTER_SPRINT $scroll_spells(~spell~) ~0~ // ~%scroll_spell_ind%~
  COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
    READ_BYTE     0x2f current ELSE 0
    READ_BYTE     0x2b current2 ELSE 0
    READ_LONG 0x64 headoffset  ELSE 0
    READ_SHORT 0x68 headcount  ELSE 0
    READ_LONG 0x6a effectsoffset  ELSE 0
    haslearn = 0
    hascast = 0
//    PATCH_IF (headcount > 1) BEGIN
      FOR (headcyc = 0; headcyc < headcount ; headcyc = headcyc + 1) BEGIN
        thishead = 0
        READ_SHORT (headoffset + (headcyc * 0x38) + 0x1e) effcount  ELSE 0
        READ_SHORT (headoffset + (headcyc * 0x38) + 0x20) effectsindex  ELSE 0
        FOR (effcyc = 0; effcyc < effcount; effcyc = effcyc + 1) BEGIN
          READ_SHORT (effectsoffset + (effectsindex + effcyc)* 0x30) opcode ELSE 0
          PATCH_IF (opcode = 0x93) AND (thishead = 0) BEGIN
            READ_ASCII (effectsoffset + 0x14 + (effectsindex + effcyc)* 0x30) resref_learn  ELSE 0
            INNER_PATCH_FILE ~%resref_learn%.spl~ BEGIN
              READ_SHORT 0x1c type
            END
            PATCH_IF (type = 1) BEGIN // arcane spell scroll
              thishead = 1
              haslearn = 1
            END
          END 
          PATCH_IF ((opcode = 0x92) OR (opcode = 0x94)) AND (thishead = 0) BEGIN
            READ_ASCII (effectsoffset + 0x14 + (effectsindex + effcyc)* 0x30) resref_cast  ELSE 0
            INNER_PATCH_FILE ~%resref_cast%.spl~ BEGIN
              READ_SHORT 0x1c type
            END
            PATCH_IF (type = 1) BEGIN // arcane spell scroll
              thishead = 1
              hascast = 1
            END
          END 
        END 
      END 
//    END // end has >1 headers
    PATCH_IF (haslearn = 1) AND (hascast = 1) AND (~%resref_cast%~ STRING_EQUAL_CASE ~%resref_learn%~) BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~%resref_learn%.spl~) BEGIN
        SPRINT $scroll_spells(~%resref_learn%~) ~1~ // ~%scroll_spell_ind%~
        SET ++scroll_spell_ind
      END
    END
  BUT_ONLY

  COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
	PATCH_IF (%SOURCE_SIZE% > 0x71) BEGIN
	  READ_SHORT 0x1c spell_type
	  READ_BYTE 0x1c spell_school
	  PATCH_IF (spell_type = 1) AND (spell_school = 9) BEGIN
		SPRINT $scroll_spells(~%SOURCE_RES%~) ~1~
	  END
	END
  BUT_ONLY

  ACTION_FOR_EACH hla IN
	~spwi920~
	~spwi921~
	~spwi922~
	~spwi923~
	~spwi924~
	~spwi925~
	~TG#DRGB~
	~TG#CLEA~
	~TG#BONU~
	~TG#DTHF~
	~TG#AEGI~
	~TG#FORS~
	~LI#SCRB~		BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%hla%.spl~) BEGIN
      COPY_EXISTING ~%hla%.spl~ ~override~
	    READ_SHORT 0x1c spell_type
	    PATCH_IF (spell_type = 1) BEGIN
	      SPRINT $scroll_spells(~%hla%~) ~1~
	    END
      IF_EXISTS BUT_ONLY
    END
  END

  ACTION_FOR_EACH wild_spell IN
	~spwi124~
	~spwi222~
	~spwi723~
  BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%wild_spell%.spl~) BEGIN
      COPY_EXISTING ~%wild_spell%.spl~ ~override~
	    READ_SHORT 0x1c spell_type
	    PATCH_IF (spell_type = 1) BEGIN
	      SPRINT $scroll_spells(~%wild_spell%~) ~1~
	    END
      IF_EXISTS BUT_ONLY
    END
  END
  ACTION_IF (FILE_EXISTS_IN_GAME ~d5nahal.spl~) BEGIN
    OUTER_SPRINT $scroll_spells(~d5nahal~) ~1~
  END
  
  ACTION_PHP_EACH scroll_spells AS arcane_spell => ind BEGIN
    ACTION_IF (%ind% > 0) BEGIN
      OUTER_SET spl_ind = 0
	  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5zclons.2da~ ~%arcane_spell%~)) BEGIN
		COPY_EXISTING ~d5zclons.2da~ ~override~
		  COUNT_2DA_COLS cols
	      READ_2DA_ENTRIES_NOW ~r2en_zclons~ cols
	      FOR (row = 0; row < r2en_zclons; ++row) BEGIN
	        READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 0 prev_ind
	        READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 1 mem_spell
	        READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 2 cast_spell
	        PATCH_IF (~%arcane_spell%~ STRING_EQUAL_CASE ~%mem_spell%~) BEGIN
	          SET spl_ind = prev_ind
	        END 
	      END
	    BUT_ONLY
      END
      ACTION_IF (spl_ind = 0) BEGIN
        OUTER_SET high_ind = high_ind + 1
	    OUTER_SET spl_ind = high_ind
	  END
	  ACTION_IF (FILE_EXISTS_IN_GAME ~%arcane_spell%.spl~) BEGIN
        APPEND ~d5zclons.2da~ ~%spl_ind% 	%arcane_spell% 	%arcane_spell% 	arcane 	no ~ UNLESS ~%arcane_spell% 	%arcane_spell%~
      END
    END
  END

  COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
    PATCH_IF (%SOURCE_SIZE% > 0x71) BEGIN
//    SNPRINT 4 spell_prefix ~%SOURCE_RES%~
      READ_SHORT 0x1c spell_type 
      READ_BYTE 0x25 spell_school
      READ_LONG 0x34 spell_level
      PATCH_IF (~%SOURCE_RES%~ STRING_MATCHES_REGEXP ~[Ss][Pp][Ww][Ii][1-9][0-5][0-9]$~ = 0) && (spell_type = 1) && !(spell_school = 10) && !(~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI908~) && !(~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI124~) BEGIN
	    SNPRINT (0 - 3) spell_num ~%SOURCE_RES%~
	    PATCH_IF !(FILE_CONTAINS_EVALUATED (~hidespl.2da~ ~%SOURCE_RES%~)) AND !(FILE_CONTAINS_EVALUATED (~d5zclons.2da~ ~%SOURCE_RES%~)) BEGIN
          SPRINT $more_sorcerer_spells(~%SOURCE_RES%~) ~1~
        END
      END
    END
  BUT_ONLY
  
  ACTION_PHP_EACH more_sorcerer_spells AS sorc_spell => ind BEGIN
    ACTION_IF (%ind% > 0) BEGIN
      OUTER_SET spl_ind = 0
	  ACTION_IF (FILE_CONTAINS_EVALUATED (~d5zclons.2da~ ~%sorc_spell%~)) BEGIN
		COPY_EXISTING ~d5zclons.2da~ ~override~
		  COUNT_2DA_COLS cols
	      READ_2DA_ENTRIES_NOW ~r2en_zclons~ cols
	      FOR (row = 0; row < r2en_zclons; ++row) BEGIN
	        READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 0 prev_ind
	        READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 2 cast_spell
	        PATCH_IF (~%sorc_spell%~ STRING_EQUAL_CASE ~%cast_spell%~) BEGIN
	          SET spl_ind = prev_ind
	        END 
	      END
	    BUT_ONLY
      END
      ACTION_IF (spl_ind = 0) BEGIN
        OUTER_SET high_ind = high_ind + 1
	    OUTER_SET spl_ind = high_ind
	  END
      APPEND ~d5zclons.2da~ ~%spl_ind% 	%sorc_spell% 	%sorc_spell% 	arcane 	no ~ UNLESS ~%sorc_spell% 	%sorc_spell%~
    END
  END

  COPY_EXISTING ~kitlist.2da~ ~override~
    READ_2DA_ENTRIES_NOW ~r2en_kitlist~ 10
    FOR (row = 2; row < r2en_kitlist; row += 1) BEGIN
      READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 5 kit_clab
      SPRINT $clabs_to_check(~%kit_clab%~)~1~
    END
  BUT_ONLY
 
  ACTION_PHP_EACH clabs_to_check AS clab => ind BEGIN
    ACTION_IF (FILE_EXISTS_IN_GAME ~%clab%.2da~) BEGIN
      COPY_EXISTING ~%clab%.2da~ ~override~
        LPF 2DA_MISSING_COLS STR_VAR entry = ~****~ END 
      BUT_ONLY
      COPY_EXISTING ~%clab%.2da~ ~override~
        COUNT_2DA_COLS cols
        READ_2DA_ENTRIES_NOW r2en_clab cols
        FOR (col = 1; col < cols; ++col) BEGIN
          FOR (row = 0; row < r2en_clab; ++row) BEGIN
            READ_2DA_ENTRY_FORMER r2en_clab row col kit_abil
            PATCH_IF (~%kit_abil%~ STRING_CONTAINS_REGEXP ~GA_~) = 0 BEGIN
              SPRINT $ga_abils(~%kit_abil%~)~1~
            END
          END
        END
      BUT_ONLY
    END
  END

  ACTION_PHP_EACH ga_abils AS abil => ind BEGIN
    OUTER_INNER_PATCH_SAVE abil ~%abil%~ BEGIN
      REPLACE_TEXTUALLY ~GA_~ ~~
    END
    ACTION_IF (FILE_EXISTS_IN_GAME ~%abil%.spl~) BEGIN
      COPY_EXISTING ~%abil%.spl~ ~override~
        READ_BYTE 0x1c spl_type
        PATCH_IF (spl_type = 1) BEGIN			// if a wizard spell
          PATCH_IF !(FILE_CONTAINS_EVALUATED (~d5zclons.2da~ ~%abil%~)) BEGIN
            INNER_ACTION BEGIN
	          OUTER_SET high_ind = high_ind + 1
		      OUTER_SET spl_ind = high_ind
              APPEND ~d5zclons.2da~ ~%spl_ind% 	%abil% 	%abil% 	arcane 	no ~ UNLESS ~%abil%~
            END
          END
        END
      BUT_ONLY
    END
  END

  ACTION_FOR_EACH num IN ~1~ ~2~ ~3~ ~4~ ~5~ ~6~ ~7~ ~8~ ~9~ BEGIN
    ACTION_IF (FILE_EXISTS_IN_GAME ~mewi%num%.txt~) BEGIN
      COPY_EXISTING ~mewi%num%.txt~ ~override~
        COUNT_2DA_ROWS 1 rows
        FOR (row = 0; row < rows; ++row) BEGIN
          READ_2DA_ENTRY row 0 1 me_spl
          PATCH_IF (FILE_EXISTS_IN_GAME ~%me_spl%.spl~) BEGIN
            PATCH_IF !(FILE_CONTAINS_EVALUATED (~d5zclons.2da~ ~%me_spl%~)) BEGIN
              INNER_ACTION BEGIN
	            OUTER_SET high_ind = high_ind + 1
		        OUTER_SET spl_ind = high_ind
                APPEND ~d5zclons.2da~ ~%spl_ind% 	%me_spl% 	%me_spl% 	arcane 	no ~ UNLESS ~%me_spl%~
              END             
            END
          END
        END
    END
  END

  LAF semi_armor_casting END

  COPY ~%MOD_FOLDER%/lib/semi_spont/d5_marker.d5~ ~override/d5__5E_casting_arcane.d5~

END

END		//	end with_tra

END 	// end function


//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION process_semi_spells BEGIN


//find game install language__________________________________________________________
//
LAF set_lang RET game_lang END

WITH_TRA ~%MOD_FOLDER%/lib/semi_spont/%game_lang%/semi_spont.tra~ BEGIN


APPEND ~splprot.2da~ ~D5_FATIGUE_0%TAB%30%TAB%0%TAB%1~ UNLESS ~D5_FATIGUE_0~

ACTION_IF (FILE_CONTAINS_EVALUATED (~splstate.ids~ ~D5_SEMI_ARCANE~)) BEGIN
  COPY_EXISTING ~splstate.ids~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 ~state_name~
	  READ_2DA_ENTRY_FORMER rows row 0 ~state_ind~
	  PATCH_IF (~%state_name%~ STRING_EQUAL_CASE ~D5_SEMI_ARCANE~) BEGIN
		SET semi_spont_arcane = %state_ind%
	  END
	END
  BUT_ONLY
END

ACTION_IF (FILE_CONTAINS_EVALUATED (~splstate.ids~ ~D5_SEMI_DIVINE~)) BEGIN
  COPY_EXISTING ~splstate.ids~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 ~state_name~
	  READ_2DA_ENTRY_FORMER rows row 0 ~state_ind~
	  PATCH_IF (~%state_name%~ STRING_EQUAL_CASE ~D5_SEMI_DIVINE~) BEGIN
		SET semi_spont_divine = %state_ind%
	  END
	END
  BUT_ONLY
END

COPY_EXISTING ~splprot.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW rows cols
  FOR (row = 1; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 0 ~stat~
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_FATIGUE_0~) BEGIN
	  SET fatigue_zero = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_PREP_SPLZ~) BEGIN
	  SET prep_spells_row = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_NOT_PREP~) BEGIN
	  SET not_prep_row = %row%
	END
  END
BUT_ONLY

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zlotr.bcs~) BEGIN
<<<<<<<<d5/inline_script.baf
>>>>>>>>

  COPY ~d5/inline_script.baf~ ~weidu_external/d5_semi_cast/d5zlotr.baf~

<<<<<<<<d5/inline_script_end.baf
IF
	True()
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),ApplySpellRes("D5ZPRPD",Myself))
	DestroySelf() 
END
>>>>>>>>

  COPY ~d5/inline_script_end.baf~ ~weidu_external/d5_semi_cast/d5z_end.baf~

END

COPY_EXISTING ~d5zclons.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW ~r2en_zclons~ cols
  FOR (row = 0; row < r2en_zclons; ++row) BEGIN
    READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 0 z_ind
    READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 1 mem_spell
    READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 2 cast_spell
    READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 3 spell_type
    READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 4 spell_proc
    SPRINT innate_spell ~d5z%z_ind%i~
    SPRINT give_spell ~d5z%z_ind%g~
    SPRINT block_spell ~d5z%z_ind%b~
    SPRINT learn_spell ~d5z%z_ind%l~
    PATCH_IF (z_ind > 100) AND (~%spell_proc%~ STRING_EQUAL_CASE ~no~) BEGIN
      INNER_ACTION BEGIN
        COPY_EXISTING ~%mem_spell%.spl~ ~override~
          SET size = %SOURCE_SIZE%
//          READ_SHORT 0x34 spell_typ
          READ_LONG 0x34 level
        IF_EXISTS BUT_ONLY
// create innate spell
       ACTION_IF (size > 155) BEGIN
		COPY_EXISTING ~%cast_spell%.spl~ ~override/%innate_spell%.spl~
//		  SAY NAME1 ~~
//		  SAY UNIDENTIFIED_DESC ~~
		  WRITE_SHORT 0x1c 4
		  WRITE_BYTE 0x27 0									//	no sectype for the innates
		  LPF ALTER_SPELL_HEADER INT_VAR location = 2 END
		  READ_LONG 0x64 abil_offset
		  READ_SHORT 0x68 abil_number
		  READ_BYTE (%abil_offset% + 0x0c) abil_target					
		  READ_SHORT (%abil_offset% + 0x0e) abil_range
		  READ_LONG 0x6a eff_offset
		  WHILE (%abil_number% > 0) BEGIN
			SET abil_number = (%abil_number% - 1)
			WRITE_SHORT (%abil_offset% + 0x26 + (0x28 * %abil_number%)) 1
		  END
		  READ_BYTE (%eff_offset% + 0x02) eff_target
		  LPF DELETE_EFFECT END
		  PATCH_IF (%abil_target% = 4) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 1 power = 0 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%cast_spell%~ END
			PATCH_IF (%abil_range% < 35) BEGIN
			  PATCH_IF (%abil_range% > 4) BEGIN
				LPF ALTER_SPELL_HEADER INT_VAR range = (%abil_range% - 3) END
			  END
			  PATCH_IF (%abil_range% < 5) BEGIN
			 	LPF ALTER_SPELL_HEADER INT_VAR target = 5 END	// might need to carve out exceptions, e.g. burning hands
			  END
			END
		  END
		  ELSE BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 power = 0 parameter2 = 1 timing = 9 STR_VAR resource = EVAL ~%cast_spell%~ END
		  END
// exempt lvl 1 if lv1 1 cantrips
		  PATCH_IF (~%spell_type%~ STRING_EQUAL_CASE ~arcane~) BEGIN
		    PATCH_IF (MOD_IS_INSTALLED ~tomeandblood.tp2~ ~62~) OR (MOD_IS_INSTALLED ~SubtleD_Spell_Tweaks.tp2~ ~62~) BEGIN
		      PATCH_IF (%level% > 1) BEGIN
				LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5src-%level%~ END
		      END
		    END
		    PATCH_IF !(MOD_IS_INSTALLED ~tomeandblood.tp2~ ~62~) AND !(MOD_IS_INSTALLED ~SubtleD_Spell_Tweaks.tp2~ ~62~) BEGIN
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5src-%level%~ END
		    END
		  END
		  PATCH_IF (~%spell_type%~ STRING_EQUAL_CASE ~divine~) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5shm-%level%~ END
		  END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5zz172~ END
//		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_divine% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5zspld~ END
//		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 4 duration = 1  STR_VAR resource = ~d5zspla~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5zspld~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5zspla~ END
          LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %fatigue_zero% timing = 1 STR_VAR resource = ~d5zzfat~ END
// make spells adding the innate spell
		COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/%give_spell%.spl~
          LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%innate_spell%~ END
// make 206 spells preventing the add spell
		COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/%block_spell%.spl~
		  WRITE_SHORT 0x1c 4
	  	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%give_spell%~ END
// add 206 spells to CLAB spell
	    COPY_EXISTING ~d5zz206.spl~ ~override~
	      LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = EVAL ~%block_spell%~ END
	      LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR match_resource = EVAL ~%block_spell%~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%block_spell%~ END
	  	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%block_spell%~ END
// make learn spells canceling the 206
		COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/%learn_spell%.spl~
	  	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%block_spell%~ END
//		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%block_spell%~ END
// add 172 to zz172
	    COPY_EXISTING ~d5zz172.spl~ ~override~
		  LPF ADD_SPELL_EFFECT INT_VAR /*insert_point = 0*/ opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%innate_spell%~ END
// conditionally add 172 to zw172 - use to remove spells upon equipping armor
		ACTION_IF (~%spell_type%~ STRING_EQUAL_CASE ~arcane~) AND (FILE_EXISTS_IN_GAME ~d5zw172.spl~) BEGIN
	      COPY_EXISTING ~d5zw172.spl~ ~override~
	        LPF DELETE_EFFECT INT_VAR match_opcode = 172 STR_VAR match_resource = EVAL ~%innate_spell%~ END
		    LPF ADD_SPELL_EFFECT INT_VAR /*insert_point = 0*/ opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%innate_spell%~ END
		END
// generate slot#x spells
	    ACTION_IF (~%spell_type%~ STRING_EQUAL_CASE ~arcane~) BEGIN
		  ACTION_IF (FILE_EXISTS_IN_GAME ~d5zwot%level%a.spl~) BEGIN
			COPY_EXISTING ~d5zwot%level%a.spl~ ~override~
		      LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			COPY_EXISTING ~d5zwot%level%b.spl~ ~override~
		      LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			COPY_EXISTING ~d5zwot%level%c.spl~ ~override~
		      LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			COPY_EXISTING ~d5zwot%level%d.spl~ ~override~
		      LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
		  END
		END
	    ACTION_IF (~%spell_type%~ STRING_EQUAL_CASE ~divine~) BEGIN
		  ACTION_IF (FILE_EXISTS_IN_GAME ~d5zdot%level%a.spl~) BEGIN
			COPY_EXISTING ~d5zdot%level%a.spl~ ~override~
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			COPY_EXISTING ~d5zdot%level%b.spl~ ~override~
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			COPY_EXISTING ~d5zdot%level%c.spl~ ~override~
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			COPY_EXISTING ~d5zdot%level%d.spl~ ~override~
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%give_spell%~ END
		  END
		END
        APPEND_OUTER ~weidu_external/d5_semi_cast/d5zlotr.baf~ ~
IF
    TriggerOverride(LastSummonerOf(Myself),HaveSpellRES("%mem_spell%"))
THEN
    RESPONSE #100
    ActionOverride(LastSummonerOf(Myself),ApplySpellRes("%learn_spell%",Myself))
    Continue()
END
~
       END
      END
      SET_2DA_ENTRY row 4 cols ~yes~
    END
  END
BUT_ONLY

/* bard casting now installed later
ACTION_IF (FILE_EXISTS_IN_GAME ~d5zw172.spl~) BEGIN
  COPY_EXISTING ~d5zw172.spl~ ~override/d5zw172l.spl~
    PATCH_IF (MOD_IS_INSTALLED ~tomeandblood.tp2~ ~48~) BEGIN
      LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 5 parameter2 = 105 timing = 0 duration = 1 STR_VAR resource = ~d5zw172l~ END
    END
  COPY_EXISTING ~d5zw172.spl~ ~override/d5zw172c.spl~
  COPY_EXISTING ~d5zw172.spl~ ~override/d5zw172p.spl~
END
*/

COPY_EXISTING ~d5spmem.spl~ ~override/d5jpmem.spl~
IF_EXISTS

COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/d5zleav.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %not_prep_row% timing = 1 STR_VAR resource = ~d5zprp~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %not_prep_row% timing = 1 STR_VAR resource = ~d5jpmem~ END

<<<<<<<< d5/leavscpt.baf
IF
	!InParty(Myself)
	Global("D5_LEFT","LOCALS",0)
	Global("D5_PNPC","LOCALS",1)
THEN
	RESPONSE #100
	SetGlobal("D5_LEFT","LOCALS",1)
	ReallyForceSpellRES("D5ZLEAV",Myself)
	Continue()
END
IF
	InParty(Myself)

	Global("D5_LEFT","LOCALS",0)
	Global("D5_PNPC","LOCALS",0)
THEN
	RESPONSE #100
	SetGlobal("D5_PNPC","LOCALS",1)
	Continue()
END
IF
	InParty(Myself)
	Global("D5_LEFT","LOCALS",1)
THEN
	RESPONSE #100
	SetGlobal("D5_LEFT","LOCALS",0)
	Continue()
END
>>>>>>>>
COPY ~d5/leavscpt.baf~ ~weidu_external/%MOD_FOLDER%/compile/leavscpt.baf~

LAM JOINABLE_NPC_ARRAYS

ACTION_PHP_EACH JOINABLE_NPC_ARRAY AS cre => dv BEGIN
// 	PRINT ~%cre% => %dv%~ 
  COPY_EXISTING ~%cre%~ ~override~
    READ_ASCII 0x248 override_script
    PATCH_IF !(~%override_script%~ STRING_EQUAL_CASE ~SHOUT~) BEGIN
      SPRINT $npc_scripts(~%override_script%~)~1~
    END
  BUT_ONLY
END
ACTION_PHP_EACH npc_scripts AS script => ind BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%script%.bcs~) BEGIN
    EXTEND_TOP ~%script%.bcs~ ~weidu_external/%MOD_FOLDER%/compile/leavscpt.baf~
  END
END

// compile script_____________________________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5zlotr.bcs~) BEGIN
  DELETE ~override/d5zlotr.bcs~
END

COMPILE ~weidu_external/d5_semi_cast/d5zlotr.baf~

EXTEND_BOTTOM ~d5zlotr.bcs~ ~weidu_external/d5_semi_cast/d5z_end.baf~

END		//	end with_tra


END		//	end define function


//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION add_semi_spells STR_VAR new_spell = ~x~ cast_spell = ~x~ spell_type = ~x~ BEGIN

// add them to zclons.2da

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5zclons.2da~) BEGIN

<<<<<<<< d5/d5zclons.2da
2DA V1.0 
IND
		MEM 		CAST 		TYPE 	PROCESSED
100		#			#			#		#
>>>>>>>> 

  COPY ~d5/d5zclons.2da~ ~override/d5zclons.2da~ 

END

ACTION_IF (FILE_EXISTS_IN_GAME ~d5zclons.2da~) BEGIN

  COPY_EXISTING ~d5zclons.2da~ ~override~
    COUNT_2DA_COLS cols
    COUNT_2DA_ROWS cols rows
    READ_2DA_ENTRY (rows - 1) 0 cols last_ind
  BUT_ONLY
  OUTER_SET spl_ind = (last_ind + 1)

  APPEND ~d5zclons.2da~ ~%spl_ind% 	%new_spell% 	%cast_spell% 	%spell_type% 	no ~ UNLESS ~%new_spell% 	%cast_spell%~

END

// then just re-run the 'process spells' function
// wait no, better to do that manually

//LAF process_semi_spells END

END		//	end function


//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION free_cast_spells STR_VAR free_spell = ~~ list_spell = ~~ BEGIN

ACTION_IF (FILE_CONTAINS_EVALUATED (~d5zclons.2da~ ~%free_spell%~)) BEGIN
  ACTION_IF !(FILE_EXISTS_IN_GAME ~%list_spell%.spl~) BEGIN
    COPY ~%MOD_FOLDER%/lib/semi_spont/d5_base.spl~ ~override/%list_spell%.spl~
  END
  COPY_EXISTING ~d5zclons.2da~ ~override~
    COUNT_2DA_COLS cols
    READ_2DA_ENTRIES_NOW ~r2en_zclons~ cols
    SET free_spell_ind = 0
    FOR (row = 0; row < r2en_zclons; ++row) BEGIN
      READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 0 z_ind
      READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 1 mem_spell
//      READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 2 cast_spell
      PATCH_IF (~%mem_spell%~ STRING_EQUAL_CASE ~%free_spell%~) BEGIN
        SET free_spell_ind = %z_ind%
      END 
    END
  BUT_ONLY  
  ACTION_IF (free_spell_ind > 0) BEGIN
    COPY_EXISTING ~%list_spell%.spl~ ~override~
 	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5z%free_spell_ind%b~ END
      LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5z%free_spell_ind%b~ END
    BUT_ONLY
  END
END

END		//	end function


//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION find_zclons_spell STR_VAR spell_to_find = ~~ RET zclons_ind spell_to_cast type_of_spell BEGIN

COPY_EXISTING ~d5zclons.2da~ ~override~
      COUNT_2DA_COLS cols
      READ_2DA_ENTRIES_NOW ~r2en_zclons~ cols
      FOR (row = 0; row < r2en_zclons; ++row) BEGIN
        READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 0 z_ind
        READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 1 mem_spell
        READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 2 cast_spell
        READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 3 spell_type
        READ_2DA_ENTRY_FORMER ~r2en_zclons~ row 4 spell_proc
        PATCH_IF (~%mem_spell%~ STRING_EQUAL_CASE ~%spell_to_find%~) BEGIN
          SET zclons_ind = %z_ind%
          SPRINT spell_to_cast ~%cast_spell%~
          SPRINT type_of_spell ~%spell_type%~
        END
      END
BUT_ONLY

END		//	end function


//__________________________________________________________________________________
//__________________________________________________________________________________

