IF
	NumTimesTalkedTo(0)
THEN
	RESPONSE #100
		SetGlobal("D5SOKIT","GLOBAL",1)    // sorcerer selections
	SetNumTimesTalkedTo(1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("d5sokit",Myself))
END

IF
	True()
THEN
	RESPONSE #100
		SetGlobal("D5SOKIT","GLOBAL",0)
		SetNumTimesTalkedTo(0)
		DestroySelf()               // reset all global variables, then destroy self
END
