
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						MULTICLASS TWEAKS
//__________________________________________________________________________________
//__________________________________________________________________________________


//COPY MARKER FILE_________________________________________________________________
//
COPY ~scales_of_balance/mc/d5_multi.d5~ ~override~
//__________________________________________________________________________________

//EDIT DEMIHUMAN STATS______________________________________________________________
//
COPY ~scales_of_balance/mc/abracead.2da~ ~override~
//__________________________________________________________________________________

//ENABLE MORE MULTICLASSES___________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	COPY_EXISTING ~CLSRCREQ.2da~ ~override~
		SET_2DA_ENTRY 34 1 8 ~1~
		SET_2DA_ENTRY 35 1 8 ~1~
		SET_2DA_ENTRY 36 1 8 ~1~
		SET_2DA_ENTRY 37 1 8 ~1~
		SET_2DA_ENTRY 46 1 8 ~1~
		SET_2DA_ENTRY 47 1 8 ~1~
		SET_2DA_ENTRY 48 1 8 ~1~
		SET_2DA_ENTRY 49 1 8 ~1~
		SET_2DA_ENTRY 50 1 8 ~1~
		SET_2DA_ENTRY 51 1 8 ~1~
		SET_2DA_ENTRY 25 2 8 ~1~
		SET_2DA_ENTRY 35 2 8 ~1~
		SET_2DA_ENTRY 47 2 8 ~1~
		SET_2DA_ENTRY 48 2 8 ~1~
		SET_2DA_ENTRY 50 2 8 ~1~
		SET_2DA_ENTRY 51 2 8 ~1~
		SET_2DA_ENTRY 48 3 8 ~1~
		SET_2DA_ENTRY 48 4 8 ~1~
		SET_2DA_ENTRY 35 5 8 ~1~
		SET_2DA_ENTRY 48 5 8 ~1~
		BUT_ONLY
END
ACTION_IF ENGINE_IS ~tob~ THEN BEGIN
	COPY_EXISTING ~CLSRCREQ.2da~ ~override~
		SET_2DA_ENTRY 11 1 7 ~1~
		SET_2DA_ENTRY 12 1 7 ~1~
		SET_2DA_ENTRY 13 1 7 ~1~
		SET_2DA_ENTRY 14 1 7 ~1~
		SET_2DA_ENTRY 15 1 7 ~1~
		SET_2DA_ENTRY 16 1 7 ~1~
		SET_2DA_ENTRY 17 1 7 ~1~
		SET_2DA_ENTRY 18 1 7 ~1~
		SET_2DA_ENTRY 19 1 7 ~1~
		SET_2DA_ENTRY 20 1 7 ~1~
		SET_2DA_ENTRY 5 2 7 ~1~
		SET_2DA_ENTRY 12 2 7 ~1~
		SET_2DA_ENTRY 15 2 7 ~1~
		SET_2DA_ENTRY 16 2 7 ~1~
		SET_2DA_ENTRY 18 2 7 ~1~
		SET_2DA_ENTRY 20 2 7 ~1~
		SET_2DA_ENTRY 16 3 7 ~1~
		SET_2DA_ENTRY 16 4 7 ~1~
		SET_2DA_ENTRY 12 5 7 ~1~
		SET_2DA_ENTRY 16 5 7 ~1~
		BUT_ONLY
END
//___________________________________________________________________________________

//CHECK FOR R/C DRUID SPELLS____________________________________________________________
//
ACTION_IF FILE_EXISTS ~%USER_DIRECTORY%/Baldur.ini~ THEN BEGIN

COPY - ~%USER_DIRECTORY%/Baldur.ini~ ~%USER_DIRECTORY%~
  COUNT_REGEXP_INSTANCES ~'Cleric Ranger Spells',[ %TAB%]*'1'~ cr_bugfix_enabled

ACTION_IF (cr_bugfix_enabled) BEGIN // no druid spells for cleric/rangers
	PRINT @13
END
ELSE BEGIN

//CHANGE RANGERS_____________________________________________________________________
//
//ACTION_IF NOT GAME_IS ~iwdee bg2ee~ THEN BEGIN

	COPY_EXISTING ~dualclas.2da~ ~override~
		SET_2DA_ENTRY 8 2 6 ~0~
		SET_2DA_ENTRY 33 2 6 ~0~
		SET_2DA_ENTRY 34 2 6 ~0~
		SET_2DA_ENTRY 35 2 6 ~0~

	STRING_SET 9580 @7010

//END
//___________________________________________________________________________________

//ADD WOODSCOUT______________________________________________________________________
//
//ACTION_IF NOT GAME_IS ~iwdee bg2ee~ THEN BEGIN

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5MIELI~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MIELI       2 2 2 2 2 2 2 2~
~D5MIELI       2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MIELI           0   9   9   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MIELI           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MIELI           0   15  15  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MIELI           0   15  15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MIELI           1  0  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MIELI           0  1  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/mc/d5_mieli.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~CR0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7011
SAY @7011
SAY @7011
//__________________________________________________________________________________

END

//__________________________________________________________________________________
ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5MIELI~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MIELI       3 3 3 3 3 3 3 3~
~D5MIELI       3 3 3 3 3 3 3 3 0 3 3 3 0 0 3 3 0 3 3 0 3 3 3 0 0 3 0 3 2 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MIELI           0   9   9   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MIELI           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MIELI           0   15  15  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MIELI           0   15  15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MIELI           1  0  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MIELI           0  1  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/mc/d5_mieli.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~CR0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7011
SAY @7011
SAY @7011
//__________________________________________________________________________________

END

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@7011)
		STR_VAR
			kit_name = D5MIELI
			clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//WOODSCOUT ABILITY FILES_____________________________________________________________
//
COPY_EXISTING ~clabpr01.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~scales_of_balance/mc/rcclab.txt~
	BUT_ONLY
COPY ~scales_of_balance/mc/d5_rc.spl~ ~override~
	SAY NAME1 @6
COPY ~scales_of_balance/mc/d5_rc.eff~ ~override~
COPY ~scales_of_balance/mc/d5_rcns.spl~ ~override~
	SAY NAME1 @6
COPY ~scales_of_balance/mc/d5_rcns.eff~ ~override~
COPY ~scales_of_balance/cleric/d5_latns.spl~ ~override~
	SAY NAME1 @6
COPY ~scales_of_balance/mc/d5_mieli.itm~ ~override~
	SAY NAME1 @7012
	SAY NAME2 @7012
	SAY UNIDENTIFIED_DESC @7013
	SAY IDENTIFIED_DESC @7013
COPY ~scales_of_balance/mc/d5_mieli.spl~ ~override~
	SAY NAME1 @9
COPY ~scales_of_balance/mc/d5_mieli.cre~ ~override~
COMPILE ~scales_of_balance/mc/d5_mieli.baf~
ACTION_IF FILE_EXISTS_IN_GAME ~d5_strid.d5~ THEN BEGIN
	COPY_EXISTING ~d5_mieli.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/misc/strirang.txt~
		BUT_ONLY
END
//____________________________________________________________________________________

//ADD FORESTWALKER____________________________________________________________________
//
//ACTION_IF NOT GAME_IS ~iwdee bg2ee~ THEN BEGIN

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5RILLI~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5RILLI       2 2 2 2 2 2 2 2~
~D5RILLI       2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RILLI           0   9   9   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RILLI           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RILLI           0   15  15  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RILLI           0   15  15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5RILLI           1  0  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5RILLI           0  1  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/mc/d5_rilli.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~CR0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7014
SAY @7014
SAY @7014
//__________________________________________________________________________________

END

//__________________________________________________________________________________
ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5RILLI~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5RILLI       3 3 3 3 3 3 3 3~
~D5RILLI       3 3 3 3 3 3 3 3 0 3 3 3 0 0 3 3 0 3 3 0 3 3 3 0 0 3 0 3 2 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RILLI           0   9   9   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RILLI           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RILLI           0   15  15  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RILLI           0   15  15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5RILLI           1  0  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5RILLI           0  1  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/mc/d5_rilli.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~CR0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7014
SAY @7014
SAY @7014
//__________________________________________________________________________________

END

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@7014)
		STR_VAR
			kit_name = D5RILLI
			clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//FORESTWALKER ABILITY FILES__________________________________________________________
//
COPY ~scales_of_balance/mc/d5_rc.spl~ ~override~
	SAY NAME1 @6
COPY ~scales_of_balance/mc/d5_rc.eff~ ~override~
COPY ~scales_of_balance/mc/d5_rilli.cre~ ~override~
COMPILE ~scales_of_balance/mc/d5_rilli.baf~
ACTION_IF FILE_EXISTS_IN_GAME ~d5_strid.d5~ THEN BEGIN
	COPY_EXISTING ~d5_rilli.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/misc/strirang.txt~
		BUT_ONLY
END

//RANGER/CLERIC WEAPONS____________________________________________________________
//
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ // copies all item files
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
		READ_BYTE  0x1f multi 
		READ_SHORT  ~0x1c~ type 
		PATCH_IF (type = 15) BEGIN // bows
			WRITE_BYTE 0x1f (multi BAND 0b11111011)
		END
		PATCH_IF (type = 29) BEGIN // spears
			WRITE_BYTE 0x1f (multi BAND 0b11111011)
		END
		PATCH_IF (type = 19) BEGIN // small swords
			WRITE_BYTE 0x1f (multi BAND 0b11111011)
		END
		PATCH_IF (type = 20) BEGIN // large swords
			WRITE_BYTE 0x1f (multi BAND 0b11111011)
		END
		PATCH_IF (type = 16) BEGIN // daggers
			WRITE_BYTE 0x1f (multi BAND 0b11111011)
		END
	END
	BUT_ONLY
//___________________________________________________________________________________

END
//___________________________________________________________________________________
END


//ADD BLADESINGER____________________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5BLADS~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5BLADS       5 5 1 1 1 1 1 1~
~D5BLADS       5 5 1 1 1 1 1 1 5 5 5 1 0 5 5 5 1 1 0 0 1 1 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BLADS           9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BLADS           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BLADS           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BLADS           15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5BLADS           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5BLADS           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/mc/d5_blads.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00014000 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~FM0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7020
SAY @7020
SAY @7020
//__________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5BLADS~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5BLADS       5 5 1 0 1 1 1 1~
~D5BLADS       5 5 1 0 1 1 1 1 0 5 5 1 0 0 5 5 1 1 0 0 1 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BLADS           9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BLADS           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BLADS           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BLADS           15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5BLADS           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5BLADS           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/mc/d5_blads.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00014000 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~FM0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7020
SAY @7020
SAY @7020
//__________________________________________________________________________________

END

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@7020)
		STR_VAR
			kit_name = D5BLADS
			clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//BLADESINGER ABILITY FILES_____________________________________________________________
//
COPY ~scales_of_balance/misc/d5_acbon.spl~ ~override~
COPY ~scales_of_balance/misc/d5_acmel.spl~ ~override~
COPY ~scales_of_balance/mc/d5_blads.itm~ ~override~
	SAY NAME1 @7021
	SAY NAME2 @7021
	SAY UNIDENTIFIED_DESC @7022
	SAY IDENTIFIED_DESC @7022
COPY ~scales_of_balance/mc/d5_blads.spl~ ~override~
	SAY NAME1 @9
COPY ~scales_of_balance/mc/d5_blads.cre~ ~override~
COMPILE ~scales_of_balance/mc/d5_blads.baf~
COPY ~scales_of_balance/mc/d5_blad1.spl~ ~override~
	SAY NAME1 @7023
	SAY NAME2 @7023
	SAY UNIDENTIFIED_DESC @7024
COPY ~scales_of_balance/mc/d5_bspr1.spl~ ~override~
	SAY NAME1 @6
COPY ~scales_of_balance/mc/d5_bspr2.spl~ ~override~
	SAY NAME1 @6
//____________________________________________________________________________________

//ADD SPELLFILCHER____________________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5FILCH~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5FILCH       1 1 1 0 1 0 0 1~
~D5FILCH       1 1 1 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 0 0 0 0 1 1 1 1 1 1 1 1 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FILCH    	   0   12  0   12  0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FILCH           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FILCH           0   15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FILCH  	       0   15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5FILCH           0  0  0  1  1  1  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5FILCH           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/mc/d5_filch.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 4~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~MT0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7031
SAY @7031
SAY @7031
//__________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@7031)
		STR_VAR
			kit_name = D5FILCH
			clswpbon = ~0 0 3~
			thiefskl = ~50 25~
	END
END
//____________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5FILCH~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5FILCH       3 3 3 0 3 0 0 3~
~D5FILCH       3 3 3 0 3 0 0 3 0 3 3 0 0 0 3 3 0 3 0 0 0 0 3 3 0 3 0 3 0 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FILCH    	   0   12  0   12  0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FILCH           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FILCH           0   15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FILCH  	       0   15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5FILCH           0  0  0  1  1  1  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5FILCH           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/mc/d5_filch.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 4~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~MT0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7031
SAY @7031
SAY @7031
//__________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@7031)
		STR_VAR
			kit_name = D5FILCH
			clswpbon = ~1 0 3~
			thiefskl = ~50 25~
	END
END
//____________________________________________________________________________________

END

//SPELLFILCHER ABILITY FILES__________________________________________________________
//
COPY ~scales_of_balance/mc/d5_filch.itm~ ~override~
	SAY NAME1 @7032
	SAY NAME2 @7032
	SAY UNIDENTIFIED_DESC @7033
	SAY IDENTIFIED_DESC @7033
COPY ~scales_of_balance/mc/d5_filch.spl~ ~override~
	SAY NAME1 @9
COPY ~scales_of_balance/mc/d5_filch.cre~ ~override~
COMPILE ~scales_of_balance/mc/d5_filch.baf~
COPY ~scales_of_balance/misc/d5_ssvbo.spl~ ~override~
COPY ~scales_of_balance/mc/d5_flch1.spl~ ~override~
	SAY NAME1 @7034
	SAY NAME2 @7034
	SAY UNIDENTIFIED_DESC @7035
COPY ~scales_of_balance/mc/d5_flch2.spl~ ~override~
	SAY NAME1 @7036
	SAY NAME2 @7036
	SAY UNIDENTIFIED_DESC @7037
COPY ~scales_of_balance/mc/d5_flch3.spl~ ~override~
COPY ~scales_of_balance/mc/d5_flch4.spl~ ~override~
COPY ~scales_of_balance/mc/d5_flch5.spl~ ~override~
COPY ~scales_of_balance/mc/d5_flch4.eff~ ~override~
COPY ~scales_of_balance/mc/d5_flch5.eff~ ~override~
//__________________________________________________________________________________

//ADD NIGHTRUNNER___________________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5MASK~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MASK        1 1 1 0 1 0 0 1~
~D5MASK        1 1 1 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 0 0 0 0 1 1 1 1 1 1 1 1 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MASK    	       0   12  0   12  0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MASK            0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MASK            0   15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MASK            0   15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MASK            0  0  0  1  1  1  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MASK            0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE____________________________________________________________
~scales_of_balance/mc/d5_mask.2da~

//RACIAL KIT AVAILABILITY___________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~CT0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7041
SAY @7041
SAY @7041
//__________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@7041)
		STR_VAR
			kit_name = D5MASK
			clswpbon = ~0 0 3~
	END
END
//____________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5MASK~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MASK        3 3 3 0 3 0 0 3~
~D5MASK        3 3 3 0 3 0 0 3 0 0 3 0 0 0 3 3 3 3 0 0 0 3 3 3 0 3 0 3 0 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MASK    	       0   12  0   12  0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MASK            0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MASK            0   15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MASK            0   15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MASK            0  0  0  1  1  1  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MASK            0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/mc/d5_mask.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~CT0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7041
SAY @7041
SAY @7041
//__________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@7041)
		STR_VAR
			kit_name = D5MASK
			clswpbon = ~1 0 3~
	END
END
//____________________________________________________________________________________

END

//NIGHTRUNNER ABILITY FILES__________________________________________________________
//
COPY ~scales_of_balance/cleric/d5_shans.spl~ ~override~
COPY ~scales_of_balance/mc/d5_mask.itm~ ~override~
	SAY NAME1 @7042
	SAY NAME2 @7042
	SAY UNIDENTIFIED_DESC @7043
	SAY IDENTIFIED_DESC @7043
COPY ~scales_of_balance/mc/d5_mask.spl~ ~override~
	SAY NAME1 @9
COPY ~scales_of_balance/mc/d5_mask.cre~ ~override~
COMPILE ~scales_of_balance/mc/d5_mask.baf~
COPY ~scales_of_balance/mc/d5_his20.spl~ ~override~
COPY ~scales_of_balance/mc/d5_mask1.spl~ ~override~
	SAY NAME1 @7044
	SAY NAME2 @7044
	SAY UNIDENTIFIED_DESC @7045
COPY ~scales_of_balance/mc/d5_mask2.spl~ ~override~
	SAY NAME1 @7046
	SAY NAME2 @7046
	SAY UNIDENTIFIED_DESC @7047
COPY ~scales_of_balance/mc/d5_mask3.spl~ ~override~
	SAY NAME1 @7048
	SAY NAME2 @7048
	SAY UNIDENTIFIED_DESC @7049
COPY ~scales_of_balance/mc/d5_mask3.eff~ ~override~
COPY ~scales_of_balance/mc/d5_mask3.cre~ ~override~
	SAY NAME1 @7050
//__________________________________________________________________________________

//ADD MISADVENTURER__________________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5MSADV~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MSADV       1 1 1 0 1 0 0 1~
~D5MSADV       1 1 1 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 0 0 0 0 1 1 1 1 1 1 1 1 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MSADV   	       0   12  0   0   9   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MSADV           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MSADV           0   15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MSADV           0   15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MSADV           0  0  0  1  1  1  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MSADV           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/mc/d5_msadv.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~CT0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7060
SAY @7060
SAY @7060
//__________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@7060)
		STR_VAR
			kit_name = D5MSADV
			clswpbon = ~0 0 3~
	END
END
//____________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5MSADV~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MSADV       3 3 3 0 3 0 0 3~
~D5MSADV       3 3 3 0 3 0 0 3 0 3 3 0 0 0 3 3 0 3 0 0 0 3 3 3 0 3 0 3 0 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MSADV           0   12  0   0   9   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MSADV           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MSADV           0   15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MSADV           0   15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MSADV           0  0  0  1  1  1  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MSADV           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/mc/d5_msadv.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~CT0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7060
SAY @7060
SAY @7060
//__________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@7060)
		STR_VAR
			kit_name = D5MSADV
			clswpbon = ~1 0 3~
	END
END
//____________________________________________________________________________________

END

//MISADVENTURER ABILITY FILES_________________________________________________________
//
COPY ~scales_of_balance/cleric/d5_selns.spl~ ~override~
COPY ~scales_of_balance/misc/d5_luckp.spl~ ~override~
	SAY NAME1 @3208
	SAY UNIDENTIFIED_DESC @3208
COPY ~scales_of_balance/mc/d5_msadv.itm~ ~override~
	SAY NAME1 @7061
	SAY NAME2 @7061
	SAY UNIDENTIFIED_DESC @7062
	SAY IDENTIFIED_DESC @7062
COPY ~scales_of_balance/mc/d5_msadv.spl~ ~override~
	SAY NAME1 @9
COPY ~scales_of_balance/mc/d5_msadv.cre~ ~override~
COMPILE ~scales_of_balance/mc/d5_msadv.baf~
COPY ~scales_of_balance/mc/d5_msad2.spl~ ~override~
	SAY NAME1 @7063
	SAY NAME2 @7063
	SAY UNIDENTIFIED_DESC @7064
COPY ~scales_of_balance/mc/d5_msad3.spl~ ~override~
	SAY NAME1 @7065
	SAY NAME2 @7065
	SAY UNIDENTIFIED_DESC @7066
//__________________________________________________________________________________

//ADD HEARTHGUARD____________________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5HARTH~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5HARTH       0 0 0 0 2 2 0 2~
~D5HARTH       0 0 0 0 2 2 0 2 0 0 0 0 0 0 0 0 2 2 0 0 2 2 2 0 0 0 0 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5HARTH           9   0   0   0   9   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5HARTH           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5HARTH           15  0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5HARTH           15  0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5HARTH           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5HARTH           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/mc/d5_harth.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~FC0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7070
SAY @7070
SAY @7070
//__________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5HARTH~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5HARTH       0 0 0 0 3 3 0 3~
~D5HARTH       0 0 0 0 3 3 0 3 0 0 0 0 0 0 0 0 3 3 0 0 3 3 3 0 0 0 0 4 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5HARTH           9   0   0   0   12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5HARTH           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5HARTH           15  0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5HARTH           15  0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5HARTH           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5HARTH           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/mc/d5_harth.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~FC0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7070
SAY @7070
SAY @7070
//__________________________________________________________________________________

END

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@7070)
		STR_VAR
			kit_name = D5HARTH
			clswpbon = ~1 0 3~
	END
END
//____________________________________________________________________________________

//HEARTHGUARD ABILITY FILES___________________________________________________________
//
COPY ~scales_of_balance/cleric/d5_latns.spl~ ~override~
COPY ~scales_of_balance/mc/d5_harth.itm~ ~override~
	SAY NAME1 @7071
	SAY NAME2 @7071
	SAY UNIDENTIFIED_DESC @7072
	SAY IDENTIFIED_DESC @7072
COPY ~scales_of_balance/mc/d5_harth.spl~ ~override~
	SAY NAME1 @9
COPY ~scales_of_balance/mc/d5_harth.cre~ ~override~
COMPILE ~scales_of_balance/mc/d5_harth.baf~
//____________________________________________________________________________________

//ADD ALAGHOR_________________________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5ALAGH~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5ALAGH       0 0 0 0 2 2 0 2~
~D5ALAGH       0 0 0 0 2 2 0 2 0 0 0 0 0 0 0 0 2 2 0 0 2 2 2 0 0 0 0 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5ALAGH           9   0   0   0   9   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5ALAGH           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5ALAGH           15  0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5ALAGH           15  0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5ALAGH           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5ALAGH           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/mc/d5_alagh.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~FC0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7080
SAY @7080
SAY @7080
//____________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5ALAGH~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5ALAGH       0 0 0 0 3 3 0 3~
~D5ALAGH       0 0 0 0 3 3 0 3 0 0 0 4 0 0 0 0 3 3 0 0 3 3 3 0 0 0 0 3 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5ALAGH           9   0   0   0   12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5ALAGH           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5ALAGH           15  0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5ALAGH           15  0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5ALAGH           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5ALAGH           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/mc/d5_alagh.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~FC0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7080
SAY @7080
SAY @7080
//____________________________________________________________________________________

END

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@7080)
		STR_VAR
			kit_name = D5ALAGH
			clswpbon = ~1 0 3~
	END
END
//____________________________________________________________________________________

//ALAGHOR ABILITY FILES_______________________________________________________________
//
COPY ~scales_of_balance/mc/d5_temns.spl~ ~override~
COPY ~scales_of_balance/mc/d5_alagh.itm~ ~override~
	SAY NAME1 @7081
	SAY NAME2 @7081
	SAY UNIDENTIFIED_DESC @7082
	SAY IDENTIFIED_DESC @7082
COPY ~scales_of_balance/mc/d5_alagh.spl~ ~override~
	SAY NAME1 @9
COPY ~scales_of_balance/mc/d5_alagh.cre~ ~override~
COMPILE ~scales_of_balance/mc/d5_alagh.baf~
COPY ~scales_of_balance/mc/d5_alag1.spl~ ~override~
	SAY NAME1 @7083
	SAY UNIDENTIFIED_DESC @7084
COPY ~scales_of_balance/mc/d5_alag2.spl~ ~override~
	SAY NAME1 @7085
	SAY UNIDENTIFIED_DESC @7086
COPY ~scales_of_balance/mc/d5_alag1.itm~ ~override~
	SAY NAME1 @7087
	SAY NAME2 @7087
COPY ~scales_of_balance/mc/d5_alag2.itm~ ~override~
	SAY NAME1 @7087
	SAY NAME2 @7087
COPY ~scales_of_balance/mc/d5_alag3.itm~ ~override~
	SAY NAME1 @7087
	SAY NAME2 @7087
//____________________________________________________________________________________

//ADD GLORYBLOOD______________________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5TEMPU~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0

~D5TEMPU       0 0 0 0 2 2 0 2~
~D5TEMPU       0 0 0 0 2 2 0 2 0 0 0 0 0 0 0 0 2 2 0 0 2 2 2 0 0 0 0 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
//__________________________________________________________________________________

//MINIMUM KIT STATS_________________________________________________________________
//
//                 STR DEX CON INT WIS CHR
~D5TEMPU          0   0   0   0   9   0~
//__________________________________________________________________________________

//KIT STAT MODIFIERS________________________________________________________________
//
//                 STR DEX CON INT WIS CHR
~D5TEMPU           0   0   0   0   0   0~
//__________________________________________________________________________________

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//
//                 STR DEX CON INT WIS CHR
~D5TEMPU           0   0   0   0   15  0~
//_________________________________________________________________________________

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//
//                 STR DEX CON INT WIS CHR
~D5TEMPU           0   0   0   0   15  0~
//_________________________________________________________________________________

//ALIGNMENT RESTRICTIONS____________________________________________________________
//
//                 LG LN LE NG TN NE CG CN CE
~D5TEMPU           0  0  0  1  1  1  1  1  1~
//________________________________________________________________________________

//DUAL CLASS OPTIONS________________________________________________________________
//
//                 FT CL MA TH DR RA
~D5TEMPU           1  0  0  0  0  0~
//____________________________________________________________________________________

//KIT ABILITIES 2DA FILE______________________________________________________________
//
~scales_of_balance/mc/d5_tempu.2da~
//___________________________________________________________________________________

//RACIAL KIT AVAILABILITY_____________________________________________________________
//
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~
//___________________________________________________________________________________

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
//
~0x00004000 3~
//___________________________________________________________________________________

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
//
~Cl0~
//__________________________________________________________________________________

//TOB STARTING EQUIPMENT_____________________________________________________________
//
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~
//____________________________________________________________________________________

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
//
SAY @7090
SAY @7090
SAY @7090
//___________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5TEMPU~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0

~D5TEMPU       0 0 0 0 3 3 0 3~
~D5TEMPU       0 0 0 0 3 3 0 3 0 0 0 4 0 0 0 0 3 3 0 0 3 3 3 1 0 0 0 1 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
//__________________________________________________________________________________

//MINIMUM KIT STATS_________________________________________________________________
//
//                 STR DEX CON INT WIS CHR
~D5TEMPU           12  0   0   0   9   0~
//__________________________________________________________________________________

//KIT STAT MODIFIERS________________________________________________________________
//
//                 STR DEX CON INT WIS CHR
~D5TEMPU           0   0   0   0   0   0~
//__________________________________________________________________________________

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//
//                 STR DEX CON INT WIS CHR
~D5TEMPU           0   0   0   0   15  0~
//_________________________________________________________________________________

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//
//                 STR DEX CON INT WIS CHR
~D5TEMPU           0   0   0   0   15  0~
//_________________________________________________________________________________

//ALIGNMENT RESTRICTIONS____________________________________________________________
//
//                 LG LN LE NG TN NE CG CN CE
~D5TEMPU           0  0  0  1  1  1  1  1  1~
//________________________________________________________________________________

//DUAL CLASS OPTIONS________________________________________________________________
//
//                 FT CL MA TH DR RA
~D5TEMPU           1  0  0  0  0  0~
//____________________________________________________________________________________

//KIT ABILITIES 2DA FILE______________________________________________________________
//
~scales_of_balance/mc/d5_tempu.2da~
//___________________________________________________________________________________

//RACIAL KIT AVAILABILITY_____________________________________________________________
//
~K_C_E K_C_H K_C_HE K_C_G K_C_D K_C_HL K_C_HO~
//___________________________________________________________________________________

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
//
~0x00004000 3~
//___________________________________________________________________________________

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
//
~Cl0~
//__________________________________________________________________________________

//TOB STARTING EQUIPMENT_____________________________________________________________
//
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~
//____________________________________________________________________________________

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
//
SAY @7090
SAY @7090
SAY @7090
//___________________________________________________________________________________

END

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@7090)
		STR_VAR
			kit_name = D5TEMPU
			clswpbon = ~1 0 3~
	END
END
//____________________________________________________________________________________

//GLORYBLOOD ABILITY FILES______________________________________________________________
//
COPY ~scales_of_balance/mc/d5_temns.spl~ ~override~
ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN
	COPY_EXISTING ~d5_tempu.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/mc/tempaxe.txt~
		BUT_ONLY
END
COPY ~scales_of_balance/mc/d5_tempu.itm~ ~override~
	SAY NAME1 @7091
	SAY NAME2 @7091
	SAY UNIDENTIFIED_DESC @7092
	SAY IDENTIFIED_DESC @7092
COPY ~scales_of_balance/mc/d5_tempu.spl~ ~override~
	SAY NAME1 @9
	SAY UNIDENTIFIED_DESC @9
COPY ~scales_of_balance/mc/d5_tempu.cre~ ~override~
COMPILE ~scales_of_balance/mc/d5_tempu.baf~ ~override~
COPY ~scales_of_balance/mc/d5_temp1.spl~ ~override~
COPY ~scales_of_balance/mc/d5_temp1.itm~ ~override~
COPY ~scales_of_balance/mc/d5_temp2.itm~ ~override~
COPY ~scales_of_balance/mc/d5_temp3.itm~ ~override~
//____________________________________________________________________________________

//ADD MONITOR_________________________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ACTION_IF NOT FILE_EXISTS_IN_GAME ~qdtnb00.qd~ THEN BEGIN

ADD_KIT ~D5MYSTR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MYSTR       1 1 1 1 1 1 1 1~
~D5MYSTR       1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   14  13  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MYSTR           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MYSTR           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/mc/d5_mystr.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000400 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ma0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7100
SAY @7101
SAY @7102
//__________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~qdtnb00.qd~ THEN BEGIN

ADD_KIT ~D5MYSTR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MYSTR       1 1 1 1 1 1 1 1~
~D5MYSTR       1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   14  13  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MYSTR           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MYSTR           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/mc/d5_mystr.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000080 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ma0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7100
SAY @7101
SAY @7102
//__________________________________________________________________________________

END

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@7102)
		STR_VAR
			kit_name = D5MYSTR
			clswpbon = ~0 0 3~
	END
END
//____________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ACTION_IF NOT FILE_EXISTS_IN_GAME ~qdtnb00.qd~ THEN BEGIN

ADD_KIT ~D5MYSTR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MYSTR       2 2 2 0 2 2 0 2~
~D5MYSTR       2 2 2 2 2 2 0 2 0 0 0 0 0 0 0 2 2 2 0 0 2 2 2 2 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   14  13  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MYSTR           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MYSTR           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/mc/d5_mystr.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000400 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ma0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7100
SAY @7101
SAY @7102
//__________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~qdtnb00.qd~ THEN BEGIN

ADD_KIT ~D5MYSTR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MYSTR       2 2 2 0 2 2 0 2~
~D5MYSTR       2 2 2 2 2 2 0 2 0 0 0 0 0 0 0 2 2 2 0 0 2 2 2 2 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   14  13  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MYSTR           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MYSTR           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/mc/d5_mystr.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000080 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ma0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7100
SAY @7101
SAY @7102
//__________________________________________________________________________________

END

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@7102)
		STR_VAR
			kit_name = D5MYSTR
			clswpbon = ~1 0 3~
	END
END
//____________________________________________________________________________________

END

//MONITOR ABILITY FILES_______________________________________________________________
//
COPY ~scales_of_balance/cleric/d5_selns.spl~ ~override~
COPY ~scales_of_balance/mc/d5_mystr.itm~ ~override~
	SAY NAME1 @7103
	SAY NAME2 @7103
	SAY UNIDENTIFIED_DESC @7104
	SAY IDENTIFIED_DESC @7104
COPY ~scales_of_balance/mc/d5_mystr.spl~ ~override~
	SAY NAME1 @9
COPY ~scales_of_balance/mc/d5_mystr.cre~ ~override~
COMPILE ~scales_of_balance/mc/d5_mystr.baf~
COPY ~scales_of_balance/misc/d5_cllv1.spl~ ~override~
COPY ~scales_of_balance/misc/d5_mglv1.spl~ ~override~
COPY ~scales_of_balance/misc/d5_mglv2.spl~ ~override~
ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN
	COPY ~scales_of_balance/mc/d5_mystr.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~scales_of_balance/profs/pcstaf.txt~
		BUT_ONLY
END
//____________________________________________________________________________________


//ADD SPELLBENDER_____________________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5BENDR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5BENDR       1 1 1 1 1 1 1 1~
~D5BENDR       1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BENDR           0   0   0   14  13  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BENDR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BENDR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BENDR           0   0   0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5BENDR           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5BENDR           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/mc/d5_bendr.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000400 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ma0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7100
SAY @7101
SAY @7102
//__________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@7112)
		STR_VAR
			kit_name = D5BENDR
			clswpbon = ~1 0 3~
	END
END
//____________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5BENDR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5BENDR       2 2 2 0 2 2 0 2~
~D5BENDR       2 2 2 0 2 2 0 2 0 0 0 0 0 0 0 2 2 2 0 0 2 2 2 2 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BENDR           0   0   0   14  13  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BENDR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BENDR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BENDR           0   0   0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5BENDR           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5BENDR           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~scales_of_balance/mc/d5_bendr.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000080 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ma0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @7111
SAY @7111
SAY @7112
//__________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@7112)
		STR_VAR
			kit_name = D5BENDR
			clswpbon = ~1 0 3~
	END
END
//____________________________________________________________________________________

END

//SPELLBENDER ABILITY FILES___________________________________________________________
//
COPY ~scales_of_balance/mc/d5_bendr.itm~ ~override~
	SAY NAME1 @7113
	SAY NAME2 @7113
	SAY UNIDENTIFIED_DESC @7114
	SAY IDENTIFIED_DESC @7114
COPY ~scales_of_balance/mc/d5_bendr.spl~ ~override~
	SAY NAME1 @9
COPY ~scales_of_balance/mc/d5_bendr.cre~ ~override~
COMPILE ~scales_of_balance/mc/d5_bendr.baf~
COPY ~scales_of_balance/mc/d5_arcm1.spl~ ~override~
	SAY NAME1 @7115
	SAY UNIDENTIFIED_DESC @7116
COPY ~scales_of_balance/mc/d5_arcm1.2da~ ~override~
COPY ~scales_of_balance/mc/d5_arc1b.bam~ ~override~
COPY ~scales_of_balance/mc/d5_arc1c.bam~ ~override~
COPY ~scales_of_balance/mc/d5_arcm2.spl~ ~override~
	SAY NAME1 @7117
	SAY UNIDENTIFIED_DESC @7118
COPY ~scales_of_balance/mc/d5_arcm2.2da~ ~override~
COPY ~scales_of_balance/mc/d5_arc2b.bam~ ~override~
COPY ~scales_of_balance/mc/d5_arc2c.bam~ ~override~
COPY ~scales_of_balance/mc/d5_arcm3.spl~ ~override~
	SAY NAME1 @7119
	SAY UNIDENTIFIED_DESC @7120
COPY ~scales_of_balance/mc/d5_arcm3.2da~ ~override~
COPY ~scales_of_balance/mc/d5_arc3b.bam~ ~override~
COPY ~scales_of_balance/mc/d5_arc3c.bam~ ~override~
COPY ~scales_of_balance/mc/d5_arcm4.spl~ ~override~
	SAY NAME1 @7121
	SAY UNIDENTIFIED_DESC @7122
COPY ~scales_of_balance/mc/d5_arcm4.2da~ ~override~
COPY ~scales_of_balance/mc/d5_arc4b.bam~ ~override~
COPY ~scales_of_balance/mc/d5_arc4c.bam~ ~override~
COPY ~scales_of_balance/mc/d5_arcm5.spl~ ~override~
	SAY NAME1 @7123
	SAY UNIDENTIFIED_DESC @7124
COPY ~scales_of_balance/mc/d5_arcm5.2da~ ~override~
COPY ~scales_of_balance/mc/d5_arc5b.bam~ ~override~
COPY ~scales_of_balance/mc/d5_arc5c.bam~ ~override~
COPY ~scales_of_balance/mc/d5_arcm6.spl~ ~override~
	SAY NAME1 @7125
	SAY UNIDENTIFIED_DESC @7126
COPY ~scales_of_balance/mc/d5_arcm6.2da~ ~override~
COPY ~scales_of_balance/mc/d5_arc6b.bam~ ~override~
COPY ~scales_of_balance/mc/d5_arc6c.bam~ ~override~
COPY ~scales_of_balance/mc/d5_divm1.spl~ ~override~
	SAY NAME1 @7127
	SAY UNIDENTIFIED_DESC @7128
COPY ~scales_of_balance/mc/d5_divm1.2da~ ~override~
COPY ~scales_of_balance/mc/d5_div1b.bam~ ~override~
COPY ~scales_of_balance/mc/d5_div1c.bam~ ~override~
COPY ~scales_of_balance/mc/d5_divm2.spl~ ~override~
	SAY NAME1 @7129
	SAY UNIDENTIFIED_DESC @7130
COPY ~scales_of_balance/mc/d5_divm2.2da~ ~override~
COPY ~scales_of_balance/mc/d5_div2b.bam~ ~override~
COPY ~scales_of_balance/mc/d5_div2c.bam~ ~override~
COPY ~scales_of_balance/mc/d5_divm3.spl~ ~override~
	SAY NAME1 @7131
	SAY UNIDENTIFIED_DESC @7132
COPY ~scales_of_balance/mc/d5_divm3.2da~ ~override~
COPY ~scales_of_balance/mc/d5_div3b.bam~ ~override~
COPY ~scales_of_balance/mc/d5_div3c.bam~ ~override~
COPY ~scales_of_balance/mc/d5_divm4.spl~ ~override~
	SAY NAME1 @7133
	SAY UNIDENTIFIED_DESC @7134
COPY ~scales_of_balance/mc/d5_divm4.2da~ ~override~
COPY ~scales_of_balance/mc/d5_div4b.bam~ ~override~
COPY ~scales_of_balance/mc/d5_div4c.bam~ ~override~
COPY ~scales_of_balance/mc/d5_divm5.spl~ ~override~
	SAY NAME1 @7135
	SAY UNIDENTIFIED_DESC @7136
COPY ~scales_of_balance/mc/d5_divm5.2da~ ~override~
COPY ~scales_of_balance/mc/d5_div5b.bam~ ~override~
COPY ~scales_of_balance/mc/d5_div5c.bam~ ~override~
COPY ~scales_of_balance/mc/d5_divm6.spl~ ~override~
	SAY NAME1 @7137
	SAY UNIDENTIFIED_DESC @7138
COPY ~scales_of_balance/mc/d5_divm6.2da~ ~override~
COPY ~scales_of_balance/mc/d5_div6b.bam~ ~override~
COPY ~scales_of_balance/mc/d5_div6c.bam~ ~override~
//___________________________________________________________________________________


//CHECK FOR NEW WIZARD SLAYER________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_nuwsl.d5~ THEN BEGIN
	COPY ~scales_of_balance/mc/d5_nuwsl.itm~ ~override~
		SAY NAME1 @7139
		SAY NAME2 @7139
		SAY UNIDENTIFIED_DESC @7140
		SAY IDENTIFIED_DESC @7140
	COPY ~scales_of_balance/mc/d5_nuwsl.spl~ ~override~
		SAY NAME1 @9
	COPY ~scales_of_balance/mc/d5_nuwsl.cre~ ~override~
	COMPILE ~scales_of_balance/mc/d5_nuwsl.baf~
//
//COPY MARKER FILE__________________________________________________________________
//
	COPY ~scales_of_balance/mc/d5_nuwslm.d5~ ~override~
END
//__________________________________________________________________________________



//ADD KIT ITEMS______________________________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~tem2601.sto~)THEN BEGIN
	COPY_EXISTING ~tem2601.sto~ ~override~
		ADD_STORE_ITEM ~d5_mystr~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_tempu~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_blads~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_filch~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_bendr~ #0 #0 #0 ~identified~ #1
		BUT_ONLY
	ACTION_IF FILE_EXISTS_IN_GAME ~d5_nuwsl.d5~ THEN BEGIN
		COPY_EXISTING ~tem2601.sto~ ~override~
			ADD_STORE_ITEM ~d5_nuwsl~ #0 #0 #0 ~identified~ #1
			BUT_ONLY
	END
END
ACTION_IF (FILE_EXISTS_IN_GAME ~shop08.sto~)THEN BEGIN
	COPY_EXISTING ~shop08.sto~ ~override~
		ADD_STORE_ITEM ~d5_blads~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_filch~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_bendr~ #0 #0 #0 ~identified~ #1
		BUT_ONLY
	ACTION_IF FILE_EXISTS_IN_GAME ~d5_nuwsl.d5~ THEN BEGIN
		COPY_EXISTING ~shop08.sto~ ~override~
			ADD_STORE_ITEM ~d5_nuwsl~ #0 #0 #0 ~identified~ #1
			BUT_ONLY
	END
END
ACTION_IF (FILE_EXISTS_IN_GAME ~kuoswald.sto~) THEN BEGIN
	COPY_EXISTING ~kuoswald.sto~ ~override~
		ADD_STORE_ITEM ~d5_mystr~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_msadv~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_harth~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_mask~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_alagh~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_tempu~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_blads~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_filch~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_bendr~ #0 #0 #0 ~identified~ #1
		BUT_ONLY
	ACTION_IF FILE_EXISTS_IN_GAME ~d5_nuwsl.d5~ THEN BEGIN
		COPY_EXISTING ~kuoswald.sto~ ~override~
			ADD_STORE_ITEM ~d5_nuwsl~ #0 #0 #0 ~identified~ #1
			BUT_ONLY
	END
	COPY_EXISTING ~ehpomab.sto~ ~override~
		ADD_STORE_ITEM ~d5_mystr~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_msadv~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_harth~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_mask~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_alagh~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_tempu~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_blads~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_filch~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_bendr~ #0 #0 #0 ~identified~ #1
		BUT_ONLY
	ACTION_IF FILE_EXISTS_IN_GAME ~d5_nuwsl.d5~ THEN BEGIN
		COPY_EXISTING ~ehpomab.sto~ ~override~
			ADD_STORE_ITEM ~d5_nuwsl~ #0 #0 #0 ~identified~ #1
			BUT_ONLY
	END
END
ACTION_IF FILE_EXISTS_IN_GAME ~shop06.sto~ THEN BEGIN
	COPY_EXISTING ~shop06.sto~ ~override~
		ADD_STORE_ITEM ~d5_msadv~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_harth~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_tempu~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_mystr~ #0 #0 #0 ~identified~ #1
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~caldo.cre~ THEN BEGIN
	COPY_EXISTING ~caldo.cre~ ~override~
		ADD_CRE_ITEM ~d5_mieli~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~duecla01.cre~ THEN BEGIN
	COPY_EXISTING ~duecla01.cre~ ~override~
		ADD_CRE_ITEM ~d5_mieli~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		ADD_CRE_ITEM ~d5_alagh~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~zhurlo.cre~ THEN BEGIN
	COPY_EXISTING ~zhurlo.cre~ ~override~
		ADD_CRE_ITEM ~d5_mask~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~irethf05.cre~ THEN BEGIN
	COPY_EXISTING ~irethf05.cre~ ~override~
		ADD_CRE_ITEM ~d5_mask~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~ogrema03.cre~ THEN BEGIN
	COPY_EXISTING ~ogrema03.cre~ ~override~
		ADD_CRE_ITEM ~d5_alagh~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~jenkal.cre~ THEN BEGIN
	COPY_EXISTING ~jenkal.cre~ ~override~
		ADD_CRE_ITEM ~d5_msadv~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		ADD_CRE_ITEM ~d5_harth~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
END
//____________________________________________________________________________________
