
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							IMOEN BARD
//__________________________________________________________________________________
//__________________________________________________________________________________


ACTION_FOR_EACH char IN ~imoen1~ ~imoen2~ ~imoen4~ ~imoen6~ ~imoen6_~ ~imoen10~ ~imoen15~ ~imoen211~ ~imoen213~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%char%.cre~ BEGIN
	COPY_EXISTING ~%char%.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1 //sets level to 1
		WRITE_BYTE 0x0236 1 //sets level to 1
		WRITE_BYTE 0x273 5 // sets class
		WRITE_BYTE 0x0045 10 // hide in shadows
		WRITE_BYTE 0x0064 5  // detect illusion
		WRITE_BYTE 0x0065 5  // set traps
		WRITE_BYTE 0x0066 10 // lore
		WRITE_BYTE 0x0067 5  // open locks
		WRITE_BYTE 0x0068 10 // move silently
		WRITE_BYTE 0x0069 5  // find traps
		WRITE_BYTE 0x006a 5  // pick pockets
		WRITE_SHORT 0x0024 8 // hit points
		WRITE_SHORT 0x0026 8 // max hit points
	BUT_ONLY
  END
END

ACTION_IF FILE_EXISTS_IN_GAME ~imoen.bcs~ BEGIN
	EXTEND_BOTTOM ~imoen.bcs~ ~npc_ee/npcs/imoen/imoen_bard.baf~
END

//__________________________________________________________________________________

