IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),3,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","3")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),4,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","4")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),5,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","5")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),6,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","6")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),7,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","7")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),8,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","8")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),9,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","9")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),10,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","10")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),11,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","11")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),12,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","12")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),13,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","13")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),14,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","14")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),15,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","15")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),16,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","16")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),17,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","17")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),18,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","18")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),19,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","19")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),20,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","20")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),21,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","21")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),22,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","22")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),23,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","23")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),24,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","24")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5STRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),25,STR)
THEN
	RESPONSE #100
	SetToken("d5_cur_str","25")
	SetGlobal("D5STRSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),3,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","3")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),4,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","4")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),5,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","5")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),6,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","6")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),7,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","7")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),8,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","8")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),9,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","9")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),10,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","10")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),11,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","11")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),12,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","12")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),13,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","13")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),14,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","14")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),15,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","15")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),16,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","16")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),17,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","17")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),18,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","18")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),19,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","19")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),20,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","20")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),21,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","21")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),22,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","22")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),23,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","23")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),24,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","24")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5DEXSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),25,DEX)
THEN
	RESPONSE #100
	SetToken("d5_cur_dex","25")
	SetGlobal("D5DEXSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),3,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","3")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),4,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","4")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),5,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","5")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),6,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","6")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),7,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","7")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),8,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","8")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),9,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","9")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),10,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","10")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),11,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","11")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),12,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","12")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),13,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","13")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),14,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","14")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),15,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","15")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),16,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","16")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),17,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","17")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),18,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","18")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),19,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","19")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),20,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","20")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),21,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","21")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),22,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","22")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),23,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","23")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),24,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","24")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5CONSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),25,CON)
THEN
	RESPONSE #100
	SetToken("d5_cur_con","25")
	SetGlobal("D5CONSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),3,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","3")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),4,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","4")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),5,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","5")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),6,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","6")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),7,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","7")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),8,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","8")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),9,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","9")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),10,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","10")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),11,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","11")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),12,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","12")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),13,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","13")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),14,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","14")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),15,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","15")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),16,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","16")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),17,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","17")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),18,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","18")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),19,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","19")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),20,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","20")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),21,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","21")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),22,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","22")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),23,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","23")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),24,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","24")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5INTSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),25,INT)
THEN
	RESPONSE #100
	SetToken("d5_cur_int","25")
	SetGlobal("D5INTSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),3,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","3")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),4,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","4")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),5,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","5")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),6,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","6")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),7,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","7")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),8,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","8")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),9,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","9")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),10,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","10")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),11,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","11")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),12,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","12")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),13,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","13")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),14,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","14")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),15,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","15")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),16,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","16")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),17,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","17")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),18,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","18")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),19,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","19")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),20,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","20")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),21,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","21")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),22,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","22")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),23,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","23")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),24,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","24")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5WISSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),25,WIS)
THEN
	RESPONSE #100
	SetToken("d5_cur_wis","25")
	SetGlobal("D5WISSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),3,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","3")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),4,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","4")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),5,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","5")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),6,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","6")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),7,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","7")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),8,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","8")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),9,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","9")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),10,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","10")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),11,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","11")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),12,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","12")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),13,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","13")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),14,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","14")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),15,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","15")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),16,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","16")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),17,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","17")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),18,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","18")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),19,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","19")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),20,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","20")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),21,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","21")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),22,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","22")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),23,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","23")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),24,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","24")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
IF
	Global("D5CHRSET","GLOBAL",0)
	CheckStat(LastSummonerOf(Myself),25,CHR)
THEN
	RESPONSE #100
	SetToken("d5_cur_chr","25")
	SetGlobal("D5CHRSET","GLOBAL",1)
END
