IF
	NumTimesTalkedTo(0)
THEN
	RESPONSE #100
		SetGlobal("D5PAKIT","GLOBAL",1)    // paladin selections
	SetNumTimesTalkedTo(1)
	ActionOverride(LastSummonerOf(Myself),StartDialogOverride("d5pakit",Myself))
END

IF
	True()
THEN
	RESPONSE #100
		SetGlobal("D5PAKIT","GLOBAL",0)
		SetNumTimesTalkedTo(0)
		DestroySelf()               // reset all global variables, then destroy self
END
