
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							JAHEIRA DRUID
//__________________________________________________________________________________
//__________________________________________________________________________________


ACTION_FOR_EACH char IN ~%tutu_var%jaheir~ ~%tutu_var%jaheir2~ ~%tutu_var%jaheir4~ ~%tutu_var%jaheir6~ ~%jaheir7_var%~ ~jaheir8~ ~jaheir11~ ~jaheir12~ ~jahei12b~ ~jahei14~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%char%.cre~ BEGIN
	COPY_EXISTING ~%char%.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x273 11 // sets class
		WRITE_SHORT 0x0024 10
		WRITE_SHORT 0x0026 10
		WRITE_BYTE 0x0066 10
	ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN
		COPY_EXISTING ~%char%.cre~ ~override~
			LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
		BUT_ONLY
		COPY_EXISTING ~%char%.cre~ ~override~
			SET_BG2_PROFICIENCY 115 1
			SET_BG2_PROFICIENCY 102 1
			SET_BG2_PROFICIENCY 107 1
	END
  END
END

//__________________________________________________________________________________

