
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							MINSC FIGHTER
//__________________________________________________________________________________
//__________________________________________________________________________________


ACTION_FOR_EACH char IN ~%tutu_var%minsc~ ~%tutu_var%minsc2~ ~%tutu_var%minsc4~ ~%tutu_var%minsc6~ ~%minsc7_var%~ ~minsc8~ ~minsc9~ ~minsc10~ ~minsc12~ ~minsc14~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%char%.cre~ BEGIN
	COPY_EXISTING ~%char%.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x273 2 // fighter
		WRITE_BYTE 0x0045 15
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0068 15
		WRITE_SHORT 0x0024 14
		WRITE_SHORT 0x0026 14
	ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN
		COPY_EXISTING ~%char%.cre~ ~override~
			LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
		BUT_ONLY
		COPY_EXISTING ~%char%.cre~ ~override~
			SET_BG2_PROFICIENCY 114 2
			SET_BG2_PROFICIENCY 104 1
			SET_BG2_PROFICIENCY 101 1
			SET_BG2_PROFICIENCY 93 1
	END
  END
END

//__________________________________________________________________________________

