
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							MONTARON THIEF
//__________________________________________________________________________________
//__________________________________________________________________________________


ACTION_FOR_EACH char IN ~%tutu_var%montar~ ~%tutu_var%montar2~ ~%tutu_var%montar4~ ~%tutu_var%montar6~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%char%.cre~ BEGIN
	COPY_EXISTING ~%char%.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x273 4 // sets class
		WRITE_BYTE 0x0045 10
		WRITE_BYTE 0x0064 5
		WRITE_BYTE 0x0065 5
		WRITE_BYTE 0x0066 7
		WRITE_BYTE 0x0067 5
		WRITE_BYTE 0x0068 10
		WRITE_BYTE 0x0069 5
		WRITE_BYTE 0x006a 5
		WRITE_SHORT 0x0024 9
		WRITE_SHORT 0x0026 9
		ADD_CRE_ITEM ~xbow04~ #0 #0 #0 ~IDENTIFIED~ ~WEAPON2~ TWOHANDED
	BUT_ONLY
	ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN
		COPY_EXISTING ~%char%.cre~ ~override~
			LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
		BUT_ONLY
		COPY_EXISTING ~%char%.cre~ ~override~
			SET_BG2_PROFICIENCY 91 2
			SET_BG2_PROFICIENCY 103 1
		BUT_ONLY
	END
  END
END
//__________________________________________________________________________________

