
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							KHALID RANGER
//__________________________________________________________________________________
//__________________________________________________________________________________


ACTION_FOR_EACH char IN ~khalid~ ~khalid2~ ~khalid4~ ~khalid6~ ~khalid7~ ~zikhalid~ ~zikhalid25~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%char%.cre~ BEGIN
	COPY_EXISTING ~%char%.cre~ ~override~
		WRITE_BYTE 0x0234 1 //sets level to 1
		WRITE_BYTE 0x0235 1
		WRITE_BYTE 0x0236 1
		WRITE_BYTE 0x273 12 // sets class
		WRITE_BYTE 0x0045 15
		WRITE_BYTE 0x0066 10
		WRITE_BYTE 0x0068 15
		WRITE_SHORT 0x0024 14
		WRITE_SHORT 0x0026 14
	ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN
		COPY_EXISTING ~%char%.cre~ ~override~
			LPF DELETE_EFFECT INT_VAR match_opcode = 233 END
		BUT_ONLY
		COPY_EXISTING ~%char%.cre~ ~override~
			SET_BG2_PROFICIENCY 90 2
			SET_BG2_PROFICIENCY 102 1
			SET_BG2_PROFICIENCY 104 1
			SET_BG2_PROFICIENCY 114 2
		BUT_ONLY
	END
  END
END

//__________________________________________________________________________________
